// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindTargets() {
  return window['go']['synapse']['App']['BindTargets']();
}

export function Context() {
  return window['go']['synapse']['App']['Context']();
}

export function GetMonitorHeartbeat() {
  return window['go']['synapse']['App']['GetMonitorHeartbeat']();
}

export function ListNotifications() {
  return window['go']['synapse']['App']['ListNotifications']();
}

export function RegisterSpotlightHotkey() {
  return window['go']['synapse']['App']['RegisterSpotlightHotkey']();
}

export function ServiceRegistry() {
  return window['go']['synapse']['App']['ServiceRegistry']();
}

export function SetDesktopNotifications(arg1) {
  return window['go']['synapse']['App']['SetDesktopNotifications'](arg1);
}

export function StartAgent(arg1, arg2, arg3) {
  return window['go']['synapse']['App']['StartAgent'](arg1, arg2, arg3);
}

export function StartChat(arg1, arg2, arg3) {
  return window['go']['synapse']['App']['StartChat'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['synapse']['App']['Startup'](arg1);
}

export function StopChat(arg1) {
  return window['go']['synapse']['App']['StopChat'](arg1);
}
