// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {synapse} from '../models';

export function GetSettings():Promise<synapse.AppSettings>;

export function UpdateSettings(arg1:synapse.AppSettings):Promise<void>;
