// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveRenovatePR(arg1, arg2) {
  return window['go']['synapse']['IntegrationService']['ApproveRenovatePR'](arg1, arg2);
}

export function FetchAssignedIssues() {
  return window['go']['synapse']['IntegrationService']['FetchAssignedIssues']();
}

export function FetchRenovatePRs() {
  return window['go']['synapse']['IntegrationService']['FetchRenovatePRs']();
}

export function FixRenovateCI(arg1, arg2, arg3, arg4) {
  return window['go']['synapse']['IntegrationService']['FixRenovateCI'](arg1, arg2, arg3, arg4);
}

export function GetProviderHealth() {
  return window['go']['synapse']['IntegrationService']['GetProviderHealth']();
}

export function GetTodoistProjects() {
  return window['go']['synapse']['IntegrationService']['GetTodoistProjects']();
}

export function MergeRenovatePR(arg1, arg2) {
  return window['go']['synapse']['IntegrationService']['MergeRenovatePR'](arg1, arg2);
}

export function ProviderHealthEnabled() {
  return window['go']['synapse']['IntegrationService']['ProviderHealthEnabled']();
}

export function RerunRenovateChecks(arg1, arg2) {
  return window['go']['synapse']['IntegrationService']['RerunRenovateChecks'](arg1, arg2);
}

export function SetProviderAutoFailover(arg1) {
  return window['go']['synapse']['IntegrationService']['SetProviderAutoFailover'](arg1);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['synapse']['IntegrationService']['SetProviderEnabled'](arg1, arg2);
}

export function SyncTodoist() {
  return window['go']['synapse']['IntegrationService']['SyncTodoist']();
}

export function TodoistEnabled() {
  return window['go']['synapse']['IntegrationService']['TodoistEnabled']();
}
