// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLoopAgent(arg1) {
  return window['go']['synapse']['LoopAgentService']['CreateLoopAgent'](arg1);
}

export function DeleteLoopAgent(arg1) {
  return window['go']['synapse']['LoopAgentService']['DeleteLoopAgent'](arg1);
}

export function GetLoopAgent(arg1) {
  return window['go']['synapse']['LoopAgentService']['GetLoopAgent'](arg1);
}

export function ListLoopAgentRuns(arg1, arg2) {
  return window['go']['synapse']['LoopAgentService']['ListLoopAgentRuns'](arg1, arg2);
}

export function ListLoopAgents() {
  return window['go']['synapse']['LoopAgentService']['ListLoopAgents']();
}

export function RunLoopAgentNow(arg1) {
  return window['go']['synapse']['LoopAgentService']['RunLoopAgentNow'](arg1);
}

export function UpdateLoopAgent(arg1) {
  return window['go']['synapse']['LoopAgentService']['UpdateLoopAgent'](arg1);
}
