// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOrchestratorAgentID():Promise<string>;

export function IsOrchestratorRunning():Promise<boolean>;

export function StartOrchestrator():Promise<void>;

export function StopOrchestrator():Promise<void>;
