// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOrchestratorAgentID() {
  return window['go']['synapse']['OrchestratorService']['GetOrchestratorAgentID']();
}

export function IsOrchestratorRunning() {
  return window['go']['synapse']['OrchestratorService']['IsOrchestratorRunning']();
}

export function StartOrchestrator() {
  return window['go']['synapse']['OrchestratorService']['StartOrchestrator']();
}

export function StopOrchestrator() {
  return window['go']['synapse']['OrchestratorService']['StopOrchestrator']();
}
