// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2) {
  return window['go']['synapse']['ProjectService']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['synapse']['ProjectService']['DeleteProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['synapse']['ProjectService']['GetProject'](arg1);
}

export function ListProjects() {
  return window['go']['synapse']['ProjectService']['ListProjects']();
}

export function ListWorktrees(arg1) {
  return window['go']['synapse']['ProjectService']['ListWorktrees'](arg1);
}

export function OpenInEditor(arg1) {
  return window['go']['synapse']['ProjectService']['OpenInEditor'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['synapse']['ProjectService']['OpenInTerminal'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['synapse']['ProjectService']['UpdateProject'](arg1, arg2);
}
