// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteWorkflow(arg1) {
  return window['go']['synapse']['WorkflowService']['DeleteWorkflow'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['synapse']['WorkflowService']['GetWorkflow'](arg1);
}

export function HandleHumanAction(arg1, arg2, arg3) {
  return window['go']['synapse']['WorkflowService']['HandleHumanAction'](arg1, arg2, arg3);
}

export function ListWorkflows() {
  return window['go']['synapse']['WorkflowService']['ListWorkflows']();
}

export function ResetBuiltin(arg1) {
  return window['go']['synapse']['WorkflowService']['ResetBuiltin'](arg1);
}

export function SaveWorkflow(arg1) {
  return window['go']['synapse']['WorkflowService']['SaveWorkflow'](arg1);
}

export function StartWorkflow(arg1, arg2) {
  return window['go']['synapse']['WorkflowService']['StartWorkflow'](arg1, arg2);
}
