// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Category classifies what a finding is about.
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CatFailureRate = "failure_rate",
    CatCostOutlier = "cost_outlier",
    CatDockerReclaimable = "docker_reclaimable",
    CatStuckTask = "stuck_task",
    CatWorkflowLoop = "workflow_loop",
    CatStatusBounce = "status_bounce",
    CatCostDrift = "cost_drift",
    CatAgentRetryLoop = "agent_retry_loop",
    CatTriageMismatch = "triage_mismatch",
    CatStatusBottleneck = "status_bottleneck",
    CatGHAuthFailure = "gh_auth_failure",
    CatGHPushAuthFailure = "gh_push_auth_failure",
    CatGHAuthUnavailable = "gh_auth_unavailable",
    CatSandboxCleanup = "sandbox_cleanup_failure",
    CatTaskUnreadable = "task_unreadable",
};

/**
 * Finding is a single health issue detected by the checker.
 */
export class Finding {
    "category": Category;
    "severity": Severity;
    "title": string;
    "description": string;
    "taskId"?: string;
    "agentId"?: string;
    "role"?: string;
    "logFile"?: string;
    "evidence": { [_ in string]?: any };
    "detectedAt": string;

    /**
     * Fingerprint is a stable dedup key derived from (Category, TaskID,
     * Evidence). Populated by the Checker after each tick; downstream
     * consumers (selfmonitor, issue sinks) use it as a cross-run identity.
     */
    "fingerprint"?: string;

    /** Creates a new Finding instance. */
    constructor($$source: Partial<Finding> = {}) {
        if (!("category" in $$source)) {
            this["category"] = Category.$zero;
        }
        if (!("severity" in $$source)) {
            this["severity"] = Severity.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = {};
        }
        if (!("detectedAt" in $$source)) {
            this["detectedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finding instance from a string or object.
     */
    static createFrom($$source: any = {}): Finding {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField8_0($$parsedSource["evidence"]);
        }
        return new Finding($$parsedSource as Partial<Finding>);
    }
}

/**
 * Score is the rollup verdict across all findings in a report.
 */
export enum Score {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ScoreGood = "good",
    ScoreWarning = "warning",
    ScoreCritical = "critical",
};

/**
 * Severity indicates how urgent a finding is.
 */
export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityWarning = "warning",
    SeverityCritical = "critical",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
