// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MethodMeta carries per-method HTTP metadata used by admission hooks.
 */
export class MethodMeta {
    "ReadOnly": boolean;

    /** Creates a new MethodMeta instance. */
    constructor($$source: Partial<MethodMeta> = {}) {
        if (!("ReadOnly" in $$source)) {
            this["ReadOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MethodMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): MethodMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MethodMeta($$parsedSource as Partial<MethodMeta>);
    }
}
