// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Status is a point-in-time health snapshot for a single provider.
 */
export class Status {
    "provider": string;
    "healthy": boolean;
    "reason": string;
    "detail"?: string;
    "lastCheck": time$0.Time;
    "ratelimitedUntil"?: time$0.Time;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("healthy" in $$source)) {
            this["healthy"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("lastCheck" in $$source)) {
            this["lastCheck"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
