// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Verdict is the structured classification returned by the LLM.
 */
export class Verdict {
    "title": string;
    "description"?: string;
    "tags": string[];
    "size": string;
    "type": string;
    "mode": string;
    "project_id"?: string;
    "original_title"?: string;

    /** Creates a new Verdict instance. */
    constructor($$source: Partial<Verdict> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("size" in $$source)) {
            this["size"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verdict instance from a string or object.
     */
    static createFrom($$source: any = {}): Verdict {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new Verdict($$parsedSource as Partial<Verdict>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
