// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Actor identifies which subsystem authored the blocker.
 */
export enum Actor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActorWorkflow = "workflow",
    ActorReview = "review",
};

/**
 * Kind classifies why a task is parked or retrying.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindOperatorDecision = "operator_decision",
    KindCredentialRequired = "credential_required",
    KindPolicyApproval = "policy_approval",
    KindTamperDetected = "tamper_detected",
    KindWorktreeRepair = "worktree_repair",
    KindReviewFixExhausted = "review_fix_exhausted",
    KindTriageRetryExhausted = "triage_retry_exhausted",
    KindWatchdogRateLimitExhausted = "watchdog_rate_limit_exhausted",

    /**
     * KindDependencyScopeUnmet marks a task blocked on a depends_on issue
     * whose closure a prior agent/human run explicitly verified did NOT
     * satisfy the scope this task actually needs (e.g. the closing PR only
     * covered part of the referenced issue). Code names the specific
     * depends_on ref the verdict applies to. The umbrella dependency gate
     * (internal/sybra/app_umbrella_gate.go) trusts this over a bare "done"
     * status: it never silently re-releases a child carrying this kind for
     * one of its own depends_on refs — it escalates to human-required
     * instead, so a fresh confirmation is required before the same,
     * already-known-negative implementation cycle repeats (sybra#2637).
     */
    KindDependencyScopeUnmet = "dependency_scope_unmet",

    /**
     * KindDependencyConditionUnmet marks a task blocked on a task.DepCondition
     * of kind "note" attached to one of its depends_on refs: the referenced
     * task is Done, but the free-text acceptance note the condition names has
     * not been confirmed by a human. Deliberately distinct from
     * KindDependencyScopeUnmet — that kind marks a reactive verdict a prior
     * agent/human run recorded *after* observing a closed dependency fall
     * short of scope, whereas this kind marks a proactive condition set
     * *before* the dependency ever closed. Keeping them separate means a
     * human clearing one can never be misread as having confirmed the other
     * (internal/sybra/app_umbrella_gate.go's holdUnmetConditions is the sole
     * writer).
     */
    KindDependencyConditionUnmet = "dependency_condition_unmet",
};

/**
 * State is the structured blocker payload persisted on a task.
 */
export class State {
    "kind"?: Kind;
    "actor"?: Actor;
    "code"?: string;
    "nextAction"?: string;
    "retryAfter"?: string | null;
    "exhausted"?: boolean;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State($$parsedSource as Partial<State>);
    }
}
