// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as limits$0 from "../limits/models.js";

export class Agent {
    "id": string;
    "taskId": string;
    "mode": string;
    "state": State;
    "sessionId": string;
    "costUsd": number;
    "inputTokens"?: number;
    "outputTokens"?: number;
    "cacheCreationInputTokens"?: number;
    "cacheReadInputTokens"?: number;
    "reasoningTokens"?: number;

    /**
     * PremiumRequests is Copilot's billing unit (AI credits). Sybra keeps the
     * raw count alongside the estimated USD equivalent persisted on task runs.
     */
    "premiumRequests"?: number;
    "startedAt": string;
    "lastEventAt": string;
    "logPath"?: string;
    "external": boolean;
    "pid"?: number;
    "command"?: string;
    "name"?: string;
    "project"?: string;
    "provider"?: string;
    "model"?: string;
    "experimentId"?: string;
    "variantId"?: string;
    "assignmentUnit"?: string;
    "assignmentKey"?: string;
    "reasoningEffort"?: string;
    "prompt"?: string;
    "turnCount"?: number;

    /**
     * ToolCalls counts tool_use blocks observed across the run. Persisted to
     * stats.RunRecord at completion so efficiency (tools per turn, tools per
     * landed PR) can be measured. Tracked in-memory during the run.
     */
    "toolCalls"?: number;

    /**
     * MaxTurns is the per-agent turn limit override; zero means use global guardrail.
     */
    "maxTurns"?: number;

    /**
     * PluginErrors holds plugin load failures from the most recent init event.
     */
    "pluginErrors"?: string[];
    "escalationReason"?: string;
    "errorKind"?: string;
    "errorMsg"?: string;
    "awaitingApproval"?: boolean;

    /**
     * Resumable is set when the agent was stopped intentionally via StopAgent
     * and CC exited with a valid session_id, meaning the next run can pass
     * --resume to continue the conversation.
     */
    "resumable"?: boolean;

    /**
     * CanSteer reports whether SendMessage will currently be accepted for this
     * agent — i.e. it has a live stdin transport and is not finalizing. It is a
     * backend-authoritative capability so the UI does not have to re-derive
     * steerability from mode/provider/state heuristics (which are wrong for a
     * rollback-disabled or legacy-reattached run that has no stdin transport).
     * The stored value is ignored: MarshalJSON always overrides it with the
     * live computation, so it is never stale on the wire.
     */
    "canSteer": boolean;

    /** Creates a new Agent instance. */
    constructor($$source: Partial<Agent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastEventAt" in $$source)) {
            this["lastEventAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("external" in $$source)) {
            this["external"] = false;
        }
        if (!("canSteer" in $$source)) {
            this["canSteer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     */
    static createFrom($$source: any = {}): Agent {
        const $$createField31_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pluginErrors" in $$parsedSource) {
            $$parsedSource["pluginErrors"] = $$createField31_0($$parsedSource["pluginErrors"]);
        }
        return new Agent($$parsedSource as Partial<Agent>);
    }
}

/**
 * ConvoEvent is a rich event for conversational mode, preserving full tool
 * call structure for the chat UI.
 */
export class ConvoEvent {
    "type": string;
    "subtype"?: string;
    "sessionId"?: string;
    "text"?: string;
    "toolUses"?: ToolUseBlock[];
    "toolResults"?: ToolResultBlock[];
    "costUsd"?: number;
    "inputTokens"?: number;
    "outputTokens"?: number;
    "cacheCreationInputTokens"?: number;
    "cacheReadInputTokens"?: number;
    "reasoningTokens"?: number;
    "premiumRequests"?: number;
    "limitSnapshot"?: limits$0.Snapshot | null;
    "isPartial"?: boolean;
    "timestamp": string;
    "raw"?: json$0.RawMessage;

    /**
     * ErrorType and ErrorStatus carry structured fields from the Anthropic error
     * envelope (e.g. "overloaded_error", 529) when subtype == "error".
     */
    "errorType"?: string;
    "errorStatus"?: number;

    /** Creates a new ConvoEvent instance. */
    constructor($$source: Partial<ConvoEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvoEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ConvoEvent {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolUses" in $$parsedSource) {
            $$parsedSource["toolUses"] = $$createField4_0($$parsedSource["toolUses"]);
        }
        if ("toolResults" in $$parsedSource) {
            $$parsedSource["toolResults"] = $$createField5_0($$parsedSource["toolResults"]);
        }
        if ("limitSnapshot" in $$parsedSource) {
            $$parsedSource["limitSnapshot"] = $$createField13_0($$parsedSource["limitSnapshot"]);
        }
        return new ConvoEvent($$parsedSource as Partial<ConvoEvent>);
    }
}

/**
 * PlanStep represents a single item from a TodoWrite tool call.
 */
export class PlanStep {
    "content": string;

    /**
     * "pending", "in_progress", "completed"
     */
    "status": string;

    /** Creates a new PlanStep instance. */
    constructor($$source: Partial<PlanStep> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanStep instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanStep($$parsedSource as Partial<PlanStep>);
    }
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",
    StateRunning = "running",
    StatePaused = "paused",
    StateStopped = "stopped",
};

export class StreamEvent {
    "type": string;
    "content"?: string;
    "session_id"?: string;
    "cost_usd"?: number;
    "input_tokens"?: number;
    "output_tokens"?: number;
    "cache_creation_input_tokens"?: number;
    "cache_read_input_tokens"?: number;
    "reasoning_tokens"?: number;

    /**
     * PremiumRequests is Copilot's per-result billing-unit count (result event)
     * or 0 for claude/codex.
     */
    "premium_requests"?: number;
    "subtype"?: string;
    "timestamp": string;

    /**
     * ErrorType and ErrorStatus carry structured fields from the Anthropic error
     * envelope (e.g. "overloaded_error", 529) when subtype == "error".
     */
    "error_type"?: string;
    "error_status"?: number;

    /**
     * PlanSteps is populated when the assistant calls TodoWrite; contains the
     * latest snapshot of the agent's todo list at this point in the stream.
     */
    "plan_steps"?: PlanStep[];

    /**
     * PluginErrors carries plugin load failures surfaced by the init event.
     */
    "plugin_errors"?: string[];

    /**
     * ToolCalls is the number of tool_use blocks in this event: all tool uses
     * in a Claude assistant turn, or a single Codex tool_use. The runner
     * accumulates these into Agent.ToolCalls.
     */
    "tool_calls"?: number;

    /**
     * LimitSnapshot carries provider quota status emitted by CLIs such as
     * Codex. It is forwarded to the limits ledger and not rendered as normal
     * assistant output.
     */
    "limit_snapshot"?: limits$0.Snapshot | null;

    /** Creates a new StreamEvent instance. */
    constructor($$source: Partial<StreamEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamEvent {
        const $$createField14_0 = $$createType8;
        const $$createField15_0 = $$createType0;
        const $$createField17_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plan_steps" in $$parsedSource) {
            $$parsedSource["plan_steps"] = $$createField14_0($$parsedSource["plan_steps"]);
        }
        if ("plugin_errors" in $$parsedSource) {
            $$parsedSource["plugin_errors"] = $$createField15_0($$parsedSource["plugin_errors"]);
        }
        if ("limit_snapshot" in $$parsedSource) {
            $$parsedSource["limit_snapshot"] = $$createField17_0($$parsedSource["limit_snapshot"]);
        }
        return new StreamEvent($$parsedSource as Partial<StreamEvent>);
    }
}

/**
 * ToolResultBlock represents the result of a tool execution.
 */
export class ToolResultBlock {
    "toolUseId": string;
    "content": string;
    "isError"?: boolean;

    /** Creates a new ToolResultBlock instance. */
    constructor($$source: Partial<ToolResultBlock> = {}) {
        if (!("toolUseId" in $$source)) {
            this["toolUseId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolResultBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolResultBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolResultBlock($$parsedSource as Partial<ToolResultBlock>);
    }
}

/**
 * ToolUseBlock represents a single tool call from the assistant.
 */
export class ToolUseBlock {
    "id": string;
    "name": string;
    "input": { [_ in string]?: any };

    /** Creates a new ToolUseBlock instance. */
    constructor($$source: Partial<ToolUseBlock> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolUseBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolUseBlock {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField2_0($$parsedSource["input"]);
        }
        return new ToolUseBlock($$parsedSource as Partial<ToolUseBlock>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ToolUseBlock.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ToolResultBlock.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = limits$0.Snapshot.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = PlanStep.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
