// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as limits$0 from "../limits/models.js";

export type Agent = any;

/**
 * ConvoEvent is a rich event for conversational mode, preserving full tool
 * call structure for the chat UI.
 */
export class ConvoEvent {
    "type": string;
    "subtype"?: string;
    "sessionId"?: string;
    "text"?: string;
    "toolUses"?: ToolUseBlock[];
    "toolResults"?: ToolResultBlock[];
    "costUsd"?: number;
    "inputTokens"?: number;
    "outputTokens"?: number;
    "cacheCreationInputTokens"?: number;
    "cacheReadInputTokens"?: number;
    "reasoningTokens"?: number;
    "premiumRequests"?: number;
    "limitSnapshot"?: limits$0.Snapshot | null;
    "isPartial"?: boolean;
    "timestamp": string;
    "raw"?: json$0.RawMessage;

    /**
     * ErrorType and ErrorStatus carry structured fields from the Anthropic error
     * envelope (e.g. "overloaded_error", 529) when subtype == "error".
     */
    "errorType"?: string;
    "errorStatus"?: number;

    /** Creates a new ConvoEvent instance. */
    constructor($$source: Partial<ConvoEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvoEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ConvoEvent {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField13_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolUses" in $$parsedSource) {
            $$parsedSource["toolUses"] = $$createField4_0($$parsedSource["toolUses"]);
        }
        if ("toolResults" in $$parsedSource) {
            $$parsedSource["toolResults"] = $$createField5_0($$parsedSource["toolResults"]);
        }
        if ("limitSnapshot" in $$parsedSource) {
            $$parsedSource["limitSnapshot"] = $$createField13_0($$parsedSource["limitSnapshot"]);
        }
        return new ConvoEvent($$parsedSource as Partial<ConvoEvent>);
    }
}

/**
 * PlanStep represents a single item from a TodoWrite tool call.
 */
export class PlanStep {
    "content": string;

    /**
     * "pending", "in_progress", "completed"
     */
    "status": string;

    /** Creates a new PlanStep instance. */
    constructor($$source: Partial<PlanStep> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanStep instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanStep($$parsedSource as Partial<PlanStep>);
    }
}

export class StreamEvent {
    "type": string;
    "content"?: string;
    "session_id"?: string;
    "cost_usd"?: number;
    "input_tokens"?: number;
    "output_tokens"?: number;
    "cache_creation_input_tokens"?: number;
    "cache_read_input_tokens"?: number;
    "reasoning_tokens"?: number;

    /**
     * PremiumRequests is Copilot's per-result billing-unit count (result event)
     * or 0 for claude/codex.
     */
    "premium_requests"?: number;
    "subtype"?: string;
    "timestamp": string;

    /**
     * ErrorType and ErrorStatus carry structured fields from the Anthropic error
     * envelope (e.g. "overloaded_error", 529) when subtype == "error".
     */
    "error_type"?: string;
    "error_status"?: number;

    /**
     * PlanSteps is populated when the assistant calls TodoWrite; contains the
     * latest snapshot of the agent's todo list at this point in the stream.
     */
    "plan_steps"?: PlanStep[];

    /**
     * PluginErrors carries plugin load failures surfaced by the init event.
     */
    "plugin_errors"?: string[];

    /**
     * ToolCalls is the number of tool_use blocks in this event: all tool uses
     * in a Claude assistant turn, or a single Codex tool_use. The runner
     * accumulates these into Agent.ToolCalls.
     */
    "tool_calls"?: number;

    /**
     * LimitSnapshot carries provider quota status emitted by CLIs such as
     * Codex. It is forwarded to the limits ledger and not rendered as normal
     * assistant output.
     */
    "limit_snapshot"?: limits$0.Snapshot | null;

    /** Creates a new StreamEvent instance. */
    constructor($$source: Partial<StreamEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamEvent {
        const $$createField14_0 = $$createType7;
        const $$createField15_0 = $$createType8;
        const $$createField17_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plan_steps" in $$parsedSource) {
            $$parsedSource["plan_steps"] = $$createField14_0($$parsedSource["plan_steps"]);
        }
        if ("plugin_errors" in $$parsedSource) {
            $$parsedSource["plugin_errors"] = $$createField15_0($$parsedSource["plugin_errors"]);
        }
        if ("limit_snapshot" in $$parsedSource) {
            $$parsedSource["limit_snapshot"] = $$createField17_0($$parsedSource["limit_snapshot"]);
        }
        return new StreamEvent($$parsedSource as Partial<StreamEvent>);
    }
}

/**
 * ToolResultBlock represents the result of a tool execution.
 */
export class ToolResultBlock {
    "toolUseId": string;
    "content": string;
    "isError"?: boolean;

    /** Creates a new ToolResultBlock instance. */
    constructor($$source: Partial<ToolResultBlock> = {}) {
        if (!("toolUseId" in $$source)) {
            this["toolUseId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolResultBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolResultBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolResultBlock($$parsedSource as Partial<ToolResultBlock>);
    }
}

/**
 * ToolUseBlock represents a single tool call from the assistant.
 */
export class ToolUseBlock {
    "id": string;
    "name": string;
    "input": { [_ in string]?: any };

    /** Creates a new ToolUseBlock instance. */
    constructor($$source: Partial<ToolUseBlock> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolUseBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolUseBlock {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField2_0($$parsedSource["input"]);
        }
        return new ToolUseBlock($$parsedSource as Partial<ToolUseBlock>);
    }
}

// Private type creation functions
const $$createType0 = ToolUseBlock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ToolResultBlock.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = limits$0.Snapshot.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = PlanStep.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
