// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes agent operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";

/**
 * DiscoverAgents scans running Claude processes and refreshes state.
 */
export function DiscoverAgents(): $CancellablePromise<(agent$0.Agent | null)[]> {
    return $Call.ByID(2190468291).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAgentDiff returns a unified diff of uncommitted changes in the task
 * worktree. Returns an empty string when the worktree does not exist or
 * there are no changes. Untracked files are appended as synthetic new-file
 * diff blocks so the Editor tab can show them alongside modified files.
 */
export function GetAgentDiff(taskID: string): $CancellablePromise<string> {
    return $Call.ByID(1607332780, taskID);
}

/**
 * GetAgentOutput returns buffered stream events for a headless agent.
 */
export function GetAgentOutput(agentID: string): $CancellablePromise<agent$0.StreamEvent[]> {
    return $Call.ByID(3157016970, agentID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAgentRunConvoLog returns conversation events for a past or running
 * interactive agent. Live agents return the in-memory convo buffer;
 * completed agents are replayed from the NDJSON log via the Claude stream
 * parser so tool_use/tool_result/text blocks survive.
 * 
 * This exists because interactive logs are written in the raw Anthropic
 * envelope format; ParseLogFile (flat StreamEvent) silently drops the
 * nested `message.content[]` and the frontend renders empty bubbles.
 */
export function GetAgentRunConvoLog(taskID: string, agentID: string): $CancellablePromise<agent$0.ConvoEvent[]> {
    return $Call.ByID(3723387787, taskID, agentID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetAgentRunLog returns stream events for a past or running agent.
 * Live agents return the in-memory buffer; completed agents are replayed
 * from the NDJSON log file on disk.
 * 
 * Use this for headless-mode agents. Interactive agents persist a different
 * log format (raw Claude stream-json envelope); route those through
 * GetAgentRunConvoLog so the nested message content is preserved.
 */
export function GetAgentRunLog(taskID: string, agentID: string): $CancellablePromise<agent$0.StreamEvent[]> {
    return $Call.ByID(3316322818, taskID, agentID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConvoOutput returns the full conversation event buffer for an agent.
 */
export function GetConvoOutput(agentID: string): $CancellablePromise<agent$0.ConvoEvent[]> {
    return $Call.ByID(3984332340, agentID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListAgents returns all in-memory agents (managed and external).
 */
export function ListAgents(): $CancellablePromise<(agent$0.Agent | null)[]> {
    return $Call.ByID(11576428).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenWorktree opens the git worktree for taskID in the OS file manager.
 * Returns an error if the worktree does not exist or the OS command fails.
 */
export function OpenWorktree(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2163935671, taskID);
}

/**
 * RespondApproval sends a tool approval decision from the frontend.
 */
export function RespondApproval(toolUseID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(4028564556, toolUseID, approved);
}

/**
 * RespondEscalation sends a human decision to a guardrail-paused agent.
 * continueRun=true lets the agent keep running; false kills it.
 */
export function RespondEscalation(agentID: string, continueRun: boolean): $CancellablePromise<void> {
    return $Call.ByID(3809015546, agentID, continueRun);
}

/**
 * ResumeInClaudeCode opens a Ghostty terminal tab with a Claude Code session
 * resumed for taskID. If Sybra has a session_id from a prior implementation
 * run, it passes --resume directly. Otherwise the PR URL is copied to the
 * clipboard so the user can paste it into /resume manually.
 */
export function ResumeInClaudeCode(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1675184245, taskID);
}

/**
 * SendMessage sends a follow-up message to a conversational agent.
 */
export function SendMessage(agentID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1968798251, agentID, text);
}

/**
 * StopAgent sends a stop signal to the given agent.
 */
export function StopAgent(agentID: string): $CancellablePromise<void> {
    return $Call.ByID(477984491, agentID);
}

// Private type creation functions
const $$createType0 = agent$0.Agent.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = agent$0.StreamEvent.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = agent$0.ConvoEvent.createFrom;
const $$createType6 = $Create.Array($$createType5);
