// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bgop$0 from "../bgop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notification$0 from "../notification/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BindTargets returns the objects to bind for Wails IPC.
 */
export function BindTargets(): $CancellablePromise<any[]> {
    return $Call.ByID(3335194330).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Context returns the app's running context.
 */
export function Context(): $CancellablePromise<context$0.Context> {
    return $Call.ByID(607127490);
}

/**
 * GetMonitorReport returns the most recent finished report from the
 * in-process monitor service. Ready is false until the first tick completes;
 * the frontend should show an empty state in that window. Enabled mirrors
 * cfg.Monitor.Enabled so the page can hide the panel entirely on opt-out.
 */
export function GetMonitorReport(): $CancellablePromise<$models.MonitorReportBinding> {
    return $Call.ByID(936556103).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListBackgroundOps returns active and recently-completed background operations.
 */
export function ListBackgroundOps(): $CancellablePromise<bgop$0.Operation[]> {
    return $Call.ByID(729571497).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListNotifications returns pending in-app notifications.
 */
export function ListNotifications(): $CancellablePromise<notification$0.Notification[]> {
    return $Call.ByID(706012029).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RegisterSpotlightHotkey binds Ctrl+Space to the Spotlight quick-add panel.
 */
export function RegisterSpotlightHotkey(): $CancellablePromise<void> {
    return $Call.ByID(2283520412);
}

/**
 * ServiceRegistry returns the named service instances for HTTP dispatch.
 * All values are the concrete pointers Wails binds; the HTTP handler uses
 * reflection to call their exported methods.
 */
export function ServiceRegistry(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3128777629).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SetDesktopNotifications enables or disables macOS desktop notifications.
 */
export function SetDesktopNotifications(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(673982569, enabled);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1582773185);
}

/**
 * StartAgent delegates to AgentOrchestrator and is exposed as a Wails-bound method.
 * User-triggered starts are never one-shot — that flag is reserved for workflow
 * steps that expect a single turn.
 */
export function StartAgent(taskID: string, mode: string, prompt: string): $CancellablePromise<agent$0.Agent | null> {
    return $Call.ByID(2345014098, taskID, mode, prompt).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * StartChat creates a new interactive chat bound to projectID using the
 * requested provider ("claude" or "codex"). Each chat gets a dedicated
 * local-only worktree that is cleaned up when StopChat is called.
 */
export function StartChat(projectID: string, providerName: string, prompt: string): $CancellablePromise<agent$0.Agent | null> {
    return $Call.ByID(4013768999, projectID, providerName, prompt).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Startup initializes all subsystems. Returns an error if a critical subsystem
 * fails; callers (Wails OnStartup, HTTP server main) handle the error.
 */
export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2295615836);
}

/**
 * StopChat stops a chat agent, deletes its synthetic task, and removes its
 * worktree. Refuses to operate on agents that are not bound to a chat task
 * so the UI cannot accidentally delete a real task.
 */
export function StopChat(agentID: string): $CancellablePromise<void> {
    return $Call.ByID(2858183885, agentID);
}

/**
 * V3Services exposes the App and its 12 bound services as Wails v3
 * application.Service values, in the same order as BindTargets so the
 * v3 binary keeps method-name parity with the v2 path. Phase 5 cutover
 * retires BindTargets.
 */
export function V3Services(): $CancellablePromise<application$0.Service[]> {
    return $Call.ByID(1114222916).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.MonitorReportBinding.createFrom;
const $$createType2 = bgop$0.Operation.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = notification$0.Notification.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = agent$0.Agent.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = application$0.Service.createFrom;
const $$createType10 = $Create.Array($$createType9);
