// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes settings read/write as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDefaultSettings returns the settings an empty config file resolves to. The
 * UI diffs live values against these to flag "modified from default" fields and
 * to power per-field reset-to-default, without hardcoding defaults in
 * TypeScript.
 */
export function GetDefaultSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2008277869).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPathExplanations(): $CancellablePromise<$models.ConfigPathExplanation[]> {
    return $Call.ByID(2065145936).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRawConfig returns the raw config.yaml text for the Advanced (YAML) editor.
 * Unlike GetSettings this is NOT redacted — it is the user's own local file,
 * surfaced behind an explicit Advanced disclosure with a secrets warning.
 */
export function GetRawConfig(): $CancellablePromise<string> {
    return $Call.ByID(3654655477);
}

/**
 * GetSettings returns the current app settings for the config UI.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1300186602).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReloadFromDisk re-reads ~/.sybra/config.yaml, validates it, diffs against
 * the persisted intent snapshot, and applies only hot-reloadable changes.
 * Restart-required values stay pending until process restart. Never writes to disk.
 */
export function ReloadFromDisk(): $CancellablePromise<$models.ConfigMutationResult> {
    return $Call.ByID(742653545).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveRawConfig validates raw YAML, atomically writes it (preserving the user's
 * formatting and comments), then hot-reloads. Invalid YAML or a value that
 * fails validation is rejected without touching disk.
 */
export function SaveRawConfig(raw: string): $CancellablePromise<void> {
    return $Call.ByID(3088084744, raw);
}

/**
 * UpdateSettings validates, persists, and hot-reloads the provided settings.
 */
export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<$models.ConfigMutationResult> {
    return $Call.ByID(659336121, settings).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $models.ConfigPathExplanation.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ConfigMutationResult.createFrom;
