// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes settings read/write as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings returns the current app settings for the config UI.
 * Secret fields (e.g. Todoist.APIToken) are redacted — callers must use
 * dedicated write-only methods (UpdateTodoistToken) to rotate them.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1300186602).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReloadFromDisk re-reads ~/.sybra/config.yaml, validates it, diffs against
 * the in-memory config, and applies hot-reloadable changes. Returns the list
 * of hot-reloadable keys that changed. On any error the in-memory config is
 * left unchanged. Never writes to disk.
 */
export function ReloadFromDisk(): $CancellablePromise<string[]> {
    return $Call.ByID(742653545).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateSettings validates, persists, and hot-reloads the provided settings.
 */
export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(659336121, settings);
}

/**
 * UpdateTodoistToken sets or clears the Todoist API token and persists the config.
 * Pass an empty string to remove the stored token.
 * This is the only write path for the token — GetSettings never returns it.
 */
export function UpdateTodoistToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(1514278165, token);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $Create.Array($Create.Any);
