// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IntegrationService exposes Todoist, Renovate, and GitHub issue operations
 * as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../github/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as todoist$0 from "../todoist/models.js";

/**
 * ApproveRenovatePR approves a Renovate PR.
 */
export function ApproveRenovatePR(repo: string, $number: number): $CancellablePromise<void> {
    return $Call.ByID(1681784440, repo, $number);
}

/**
 * FetchAssignedIssues returns GitHub issues assigned to the current user.
 */
export function FetchAssignedIssues(): $CancellablePromise<github$0.Issue[]> {
    return $Call.ByID(3893505415).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FetchRenovatePRs returns Renovate PRs for manual refresh.
 */
export function FetchRenovatePRs(): $CancellablePromise<github$0.RenovatePR[]> {
    return $Call.ByID(2636361150).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FixRenovateCI spawns an agent to fix CI failures on a Renovate PR.
 */
export function FixRenovateCI(repo: string, $number: number, branch: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(1544419652, repo, $number, branch, title);
}

/**
 * GetProviderHealth returns the current health snapshot for all providers as
 * a slice (wails generates typed bindings from slice-returning methods more
 * reliably than from map returns). Empty when health check is disabled.
 */
export function GetProviderHealth(): $CancellablePromise<provider$0.Status[]> {
    return $Call.ByID(4199377008).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTodoistProjects returns Todoist projects for the settings UI.
 */
export function GetTodoistProjects(): $CancellablePromise<todoist$0.Project[]> {
    return $Call.ByID(3738725467).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * MergeRenovatePR merges a Renovate PR.
 */
export function MergeRenovatePR(repo: string, $number: number): $CancellablePromise<void> {
    return $Call.ByID(1904139813, repo, $number);
}

/**
 * ProviderHealthEnabled reports whether the background health check loop is
 * active. The frontend uses this to decide whether to show the Providers
 * Settings section.
 */
export function ProviderHealthEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2089253443);
}

/**
 * RerunRenovateChecks reruns failed CI checks on a Renovate PR.
 */
export function RerunRenovateChecks(repo: string, $number: number): $CancellablePromise<void> {
    return $Call.ByID(1729596620, repo, $number);
}

/**
 * SetProviderAutoFailover toggles auto-failover at runtime and persists the
 * change to disk.
 */
export function SetProviderAutoFailover(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3822602923, enabled);
}

/**
 * SetProviderEnabled toggles per-provider probing and persists the change.
 */
export function SetProviderEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3959113611, name, enabled);
}

/**
 * SyncTodoist triggers an immediate Todoist sync.
 */
export function SyncTodoist(): $CancellablePromise<void> {
    return $Call.ByID(3485279706);
}

/**
 * TodoistEnabled returns whether the todoist handler is active.
 */
export function TodoistEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(427671588);
}

// Private type creation functions
const $$createType0 = github$0.Issue.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = github$0.RenovatePR.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = provider$0.Status.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = todoist$0.Project.createFrom;
const $$createType7 = $Create.Array($$createType6);
