// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as artifact$0 from "../artifact/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "../monitor/models.js";

/**
 * AppSettings is the shape of data exchanged with the frontend for the config view.
 * 
 * Every section here is round-tripped by GetSettings → UpdateSettings. Adding a
 * field means updating four sites in lockstep: this struct, settingsToConfig,
 * configToSettings (svc_config_reload.go), and — if it needs validation —
 * validateSettings. applyFromConfig assigns the section into the live config.
 */
export class AppSettings {
    "agent": config$0.AgentDefaults;
    "notification": config$0.NotificationConfig;
    "orchestrator": config$0.OrchestratorConfig;
    "logging": LoggingSettings;
    "audit": config$0.AuditConfig;
    "todoist": config$0.TodoistConfig;
    "renovate": config$0.RenovateConfig;
    "providers": config$0.ProvidersConfig;
    "github": config$0.GitHubConfig;
    "monitor": config$0.MonitorConfig;
    "selfMonitor": config$0.SelfMonitorConfig;
    "triage": config$0.TriageConfig;
    "umbrella": config$0.UmbrellaConfig;
    "testing": config$0.TestingConfig;
    "experience": config$0.ExperienceConfig;
    "metrics": config$0.MetricsConfig;
    "browser": config$0.BrowserConfig;
    "projectTypes": string[];
    "directories": { [_ in string]?: string };

    /**
     * TodoistTokenSet reports whether a Todoist API token is stored, without
     * leaking the token itself (which GetSettings always redacts). The UI uses
     * this to show a "token set" state and route rotation through
     * UpdateTodoistToken rather than the generic UpdateSettings payload.
     */
    "todoistTokenSet": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("agent" in $$source)) {
            this["agent"] = (new config$0.AgentDefaults());
        }
        if (!("notification" in $$source)) {
            this["notification"] = (new config$0.NotificationConfig());
        }
        if (!("orchestrator" in $$source)) {
            this["orchestrator"] = (new config$0.OrchestratorConfig());
        }
        if (!("logging" in $$source)) {
            this["logging"] = (new LoggingSettings());
        }
        if (!("audit" in $$source)) {
            this["audit"] = (new config$0.AuditConfig());
        }
        if (!("todoist" in $$source)) {
            this["todoist"] = (new config$0.TodoistConfig());
        }
        if (!("renovate" in $$source)) {
            this["renovate"] = (new config$0.RenovateConfig());
        }
        if (!("providers" in $$source)) {
            this["providers"] = (new config$0.ProvidersConfig());
        }
        if (!("github" in $$source)) {
            this["github"] = (new config$0.GitHubConfig());
        }
        if (!("monitor" in $$source)) {
            this["monitor"] = (new config$0.MonitorConfig());
        }
        if (!("selfMonitor" in $$source)) {
            this["selfMonitor"] = (new config$0.SelfMonitorConfig());
        }
        if (!("triage" in $$source)) {
            this["triage"] = (new config$0.TriageConfig());
        }
        if (!("umbrella" in $$source)) {
            this["umbrella"] = (new config$0.UmbrellaConfig());
        }
        if (!("testing" in $$source)) {
            this["testing"] = (new config$0.TestingConfig());
        }
        if (!("experience" in $$source)) {
            this["experience"] = (new config$0.ExperienceConfig());
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = (new config$0.MetricsConfig());
        }
        if (!("browser" in $$source)) {
            this["browser"] = (new config$0.BrowserConfig());
        }
        if (!("projectTypes" in $$source)) {
            this["projectTypes"] = [];
        }
        if (!("directories" in $$source)) {
            this["directories"] = {};
        }
        if (!("todoistTokenSet" in $$source)) {
            this["todoistTokenSet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType11;
        const $$createField12_0 = $$createType12;
        const $$createField13_0 = $$createType13;
        const $$createField14_0 = $$createType14;
        const $$createField15_0 = $$createType15;
        const $$createField16_0 = $$createType16;
        const $$createField17_0 = $$createType17;
        const $$createField18_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agent" in $$parsedSource) {
            $$parsedSource["agent"] = $$createField0_0($$parsedSource["agent"]);
        }
        if ("notification" in $$parsedSource) {
            $$parsedSource["notification"] = $$createField1_0($$parsedSource["notification"]);
        }
        if ("orchestrator" in $$parsedSource) {
            $$parsedSource["orchestrator"] = $$createField2_0($$parsedSource["orchestrator"]);
        }
        if ("logging" in $$parsedSource) {
            $$parsedSource["logging"] = $$createField3_0($$parsedSource["logging"]);
        }
        if ("audit" in $$parsedSource) {
            $$parsedSource["audit"] = $$createField4_0($$parsedSource["audit"]);
        }
        if ("todoist" in $$parsedSource) {
            $$parsedSource["todoist"] = $$createField5_0($$parsedSource["todoist"]);
        }
        if ("renovate" in $$parsedSource) {
            $$parsedSource["renovate"] = $$createField6_0($$parsedSource["renovate"]);
        }
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField7_0($$parsedSource["providers"]);
        }
        if ("github" in $$parsedSource) {
            $$parsedSource["github"] = $$createField8_0($$parsedSource["github"]);
        }
        if ("monitor" in $$parsedSource) {
            $$parsedSource["monitor"] = $$createField9_0($$parsedSource["monitor"]);
        }
        if ("selfMonitor" in $$parsedSource) {
            $$parsedSource["selfMonitor"] = $$createField10_0($$parsedSource["selfMonitor"]);
        }
        if ("triage" in $$parsedSource) {
            $$parsedSource["triage"] = $$createField11_0($$parsedSource["triage"]);
        }
        if ("umbrella" in $$parsedSource) {
            $$parsedSource["umbrella"] = $$createField12_0($$parsedSource["umbrella"]);
        }
        if ("testing" in $$parsedSource) {
            $$parsedSource["testing"] = $$createField13_0($$parsedSource["testing"]);
        }
        if ("experience" in $$parsedSource) {
            $$parsedSource["experience"] = $$createField14_0($$parsedSource["experience"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField15_0($$parsedSource["metrics"]);
        }
        if ("browser" in $$parsedSource) {
            $$parsedSource["browser"] = $$createField16_0($$parsedSource["browser"]);
        }
        if ("projectTypes" in $$parsedSource) {
            $$parsedSource["projectTypes"] = $$createField17_0($$parsedSource["projectTypes"]);
        }
        if ("directories" in $$parsedSource) {
            $$parsedSource["directories"] = $$createField18_0($$parsedSource["directories"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * CodexModel is a single entry from `codex debug models`.
 */
export class CodexModel {
    "slug": string;
    "display_name": string;
    "supported_reasoning_levels"?: string[];

    /** Creates a new CodexModel instance. */
    constructor($$source: Partial<CodexModel> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexModel instance from a string or object.
     */
    static createFrom($$source: any = {}): CodexModel {
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supported_reasoning_levels" in $$parsedSource) {
            $$parsedSource["supported_reasoning_levels"] = $$createField2_0($$parsedSource["supported_reasoning_levels"]);
        }
        return new CodexModel($$parsedSource as Partial<CodexModel>);
    }
}

/**
 * CopilotModel is a single Copilot model option (slug + display name).
 */
export class CopilotModel {
    "slug": string;
    "display_name": string;

    /** Creates a new CopilotModel instance. */
    constructor($$source: Partial<CopilotModel> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CopilotModel instance from a string or object.
     */
    static createFrom($$source: any = {}): CopilotModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CopilotModel($$parsedSource as Partial<CopilotModel>);
    }
}

/**
 * LoggingSettings holds the editable subset of LoggingConfig (Dir is read-only).
 */
export class LoggingSettings {
    "level": string;
    "maxSizeMB": number;
    "maxFiles": number;

    /** Creates a new LoggingSettings instance. */
    constructor($$source: Partial<LoggingSettings> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("maxSizeMB" in $$source)) {
            this["maxSizeMB"] = 0;
        }
        if (!("maxFiles" in $$source)) {
            this["maxFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoggingSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): LoggingSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoggingSettings($$parsedSource as Partial<LoggingSettings>);
    }
}

/**
 * LoopAgentRun is a single fire of a loop agent, materialized from the
 * audit log on demand. We don't keep a separate run history store —
 * existing audit + per-agent ndjson logging is the source of truth.
 */
export class LoopAgentRun {
    "agentId": string;
    "startedAt": string;
    "finishedAt": string;
    "costUsd": number;
    "state": string;
    "durationS": number;

    /** Creates a new LoopAgentRun instance. */
    constructor($$source: Partial<LoopAgentRun> = {}) {
        if (!("agentId" in $$source)) {
            this["agentId"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("durationS" in $$source)) {
            this["durationS"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoopAgentRun instance from a string or object.
     */
    static createFrom($$source: any = {}): LoopAgentRun {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoopAgentRun($$parsedSource as Partial<LoopAgentRun>);
    }
}

/**
 * MonitorReportBinding is the Wails-friendly envelope for the latest
 * monitor report. Keeping the struct here (rather than in internal/monitor)
 * avoids the frontend bindings needing to handle a `monitor.Report | null`
 * union — Enabled/Ready flags say whether Report is populated.
 */
export class MonitorReportBinding {
    "enabled": boolean;
    "ready": boolean;
    "report": monitor$0.Report;

    /** Creates a new MonitorReportBinding instance. */
    constructor($$source: Partial<MonitorReportBinding> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("report" in $$source)) {
            this["report"] = (new monitor$0.Report());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorReportBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorReportBinding {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField2_0($$parsedSource["report"]);
        }
        return new MonitorReportBinding($$parsedSource as Partial<MonitorReportBinding>);
    }
}

export class TamperFindingDTO {
    "file": string;
    "category": string;
    "severity": string;
    "rule": string;
    "detail": string;

    /** Creates a new TamperFindingDTO instance. */
    constructor($$source: Partial<TamperFindingDTO> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("rule" in $$source)) {
            this["rule"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TamperFindingDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TamperFindingDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TamperFindingDTO($$parsedSource as Partial<TamperFindingDTO>);
    }
}

export class TamperReportDTO {
    "taskId": string;
    "reportAvailable": boolean;
    "base": string;
    "range": string;
    "files": string[];
    "findings": TamperFindingDTO[];

    /** Creates a new TamperReportDTO instance. */
    constructor($$source: Partial<TamperReportDTO> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("reportAvailable" in $$source)) {
            this["reportAvailable"] = false;
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }
        if (!("range" in $$source)) {
            this["range"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TamperReportDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TamperReportDTO {
        const $$createField4_0 = $$createType17;
        const $$createField5_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField4_0($$parsedSource["files"]);
        }
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField5_0($$parsedSource["findings"]);
        }
        return new TamperReportDTO($$parsedSource as Partial<TamperReportDTO>);
    }
}

export class TaskArtifactDTO {
    "name": string;
    "kind": artifact$0.Kind;
    "producerRole"?: string;

    /**
     * TaskID is the containing task's ID (redundant with the dir name, kept for AC).
     */
    "taskId": string;
    "stepId"?: string;
    "createdAt": string;

    /**
     * SourcePath is the agent-output file that was imported (forensic only).
     */
    "sourcePath"?: string;
    "size": number;

    /**
     * Stream is true for append-only artifacts (trace.jsonl).
     */
    "stream"?: boolean;
    "content"?: string;
    "error"?: string;

    /** Creates a new TaskArtifactDTO instance. */
    constructor($$source: Partial<TaskArtifactDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = artifact$0.Kind.$zero;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskArtifactDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskArtifactDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskArtifactDTO($$parsedSource as Partial<TaskArtifactDTO>);
    }
}

export class TaskAuditEventDTO {
    "ts": string;
    "type": string;
    "taskId"?: string;
    "agentId"?: string;
    "data"?: { [_ in string]?: any };

    /** Creates a new TaskAuditEventDTO instance. */
    constructor($$source: Partial<TaskAuditEventDTO> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskAuditEventDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskAuditEventDTO {
        const $$createField4_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField4_0($$parsedSource["data"]);
        }
        return new TaskAuditEventDTO($$parsedSource as Partial<TaskAuditEventDTO>);
    }
}

export class TaskSetupLogDTO {
    "taskId": string;
    "path"?: string;
    "exists": boolean;
    "content"?: string;
    "truncated"?: boolean;

    /** Creates a new TaskSetupLogDTO instance. */
    constructor($$source: Partial<TaskSetupLogDTO> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSetupLogDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskSetupLogDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskSetupLogDTO($$parsedSource as Partial<TaskSetupLogDTO>);
    }
}

/**
 * VersionInfo holds version strings for the server and client.
 */
export class VersionInfo {
    "server": string;

    /** Creates a new VersionInfo instance. */
    constructor($$source: Partial<VersionInfo> = {}) {
        if (!("server" in $$source)) {
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo($$parsedSource as Partial<VersionInfo>);
    }
}

// Private type creation functions
const $$createType0 = config$0.AgentDefaults.createFrom;
const $$createType1 = config$0.NotificationConfig.createFrom;
const $$createType2 = config$0.OrchestratorConfig.createFrom;
const $$createType3 = LoggingSettings.createFrom;
const $$createType4 = config$0.AuditConfig.createFrom;
const $$createType5 = config$0.TodoistConfig.createFrom;
const $$createType6 = config$0.RenovateConfig.createFrom;
const $$createType7 = config$0.ProvidersConfig.createFrom;
const $$createType8 = config$0.GitHubConfig.createFrom;
const $$createType9 = config$0.MonitorConfig.createFrom;
const $$createType10 = config$0.SelfMonitorConfig.createFrom;
const $$createType11 = config$0.TriageConfig.createFrom;
const $$createType12 = config$0.UmbrellaConfig.createFrom;
const $$createType13 = config$0.TestingConfig.createFrom;
const $$createType14 = config$0.ExperienceConfig.createFrom;
const $$createType15 = config$0.MetricsConfig.createFrom;
const $$createType16 = config$0.BrowserConfig.createFrom;
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = monitor$0.Report.createFrom;
const $$createType20 = TamperFindingDTO.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Map($Create.Any, $Create.Any);
