// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OrchestratorService exposes orchestrator session operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetOrchestratorAgentID returns the current orchestrator agent id, or empty
 * if none is running. The frontend uses this to subscribe to agent:convo:<id>
 * events for live streaming.
 */
export function GetOrchestratorAgentID(): $CancellablePromise<string> {
    return $Call.ByID(326237119);
}

/**
 * IsOrchestratorRunning reports whether an orchestrator agent is currently alive.
 */
export function IsOrchestratorRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3149832742);
}

/**
 * StartOrchestrator launches the orchestrator as an in-app conversational
 * agent rooted at ~/.sybra (where the brain CLAUDE.md + skills live). The
 * detector/dispatch loop runs in-process in the Go backend (see
 * LifecycleManager.startMonitorService); this session handles the
 * judgment-driven work on top of it. Provider is resolved through the A/B suite
 * (ApplyABVariant) like any other role, and health/limit failover stays on so
 * the brain is not stranded when its provider is unavailable.
 */
export function StartOrchestrator(): $CancellablePromise<void> {
    return $Call.ByID(4069016469);
}

export function StartOrchestratorContext(): $CancellablePromise<void> {
    return $Call.ByID(859255404);
}

/**
 * StopOrchestrator cancels the orchestrator agent's context which unwinds
 * the conversational runner and closes the child claude process.
 */
export function StopOrchestrator(): $CancellablePromise<void> {
    return $Call.ByID(913444691);
}
