// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlanningService exposes task planning operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

/**
 * ApprovePlan approves the plan via the workflow engine.
 */
export function ApprovePlan(id: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(147738904, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApproveTestPlan approves the manual test plan via the workflow engine.
 * Workflow-engine-level same as ApprovePlan; named separately so the frontend
 * binding stays explicit about which review page is acting.
 */
export function ApproveTestPlan(id: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(733809700, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * HasLivePlanAgent reports whether a live plan agent exists for the task.
 */
export function HasLivePlanAgent(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2278048380, id);
}

/**
 * HasLiveTestPlanAgent reports whether a live test-plan agent exists for the task.
 */
export function HasLiveTestPlanAgent(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3686057056, id);
}

/**
 * PlanTask starts a workflow for the given task if none is active.
 * If a workflow is already running — or being started concurrently
 * (CreateTask auto-spawns one in a goroutine) — this is a no-op so the
 * UI Plan button stays idempotent.
 */
export function PlanTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1970457364, id);
}

/**
 * RejectPlan rejects the plan with optional feedback via the workflow engine.
 */
export function RejectPlan(id: string, feedback: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(2235944562, id, feedback).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RejectTestPlan rejects the manual test plan with optional feedback.
 */
export function RejectTestPlan(id: string, feedback: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(2281911474, id, feedback).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SendPlanMessage sends a message to a live interactive plan agent.
 */
export function SendPlanMessage(id: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(621463710, id, message);
}

/**
 * SendTestPlanMessage sends a message to a live interactive test-plan agent.
 */
export function SendTestPlanMessage(id: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1515959970, id, message);
}

/**
 * TriageTask starts the triage workflow for the given task. Idempotent:
 * returns nil if a workflow is already running or being started concurrently
 * (CreateTask spawns the same workflow in a goroutine).
 */
export function TriageTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3209087339, id);
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
