// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService exposes project and worktree operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

/**
 * CreateProject registers a GitHub repo and starts a bare clone in the
 * background. It returns immediately with the project in cloning status.
 */
export function CreateProject(url: string, ptype: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(2936951975, url, ptype).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteProject removes a project and its bare clone from disk.
 */
export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(3866330694, id);
}

/**
 * GetProject returns a single project by ID.
 */
export function GetProject(id: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(2035355087, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListProjects returns all registered projects.
 */
export function ListProjects(): $CancellablePromise<project$0.Project[]> {
    return $Call.ByID(3142004932).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListWorktrees returns all git worktrees for the given project's bare clone.
 */
export function ListWorktrees(projectID: string): $CancellablePromise<project$0.Worktree[]> {
    return $Call.ByID(3753253508, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenInEditor opens a worktree path in Zed.
 */
export function OpenInEditor(path: string): $CancellablePromise<void> {
    return $Call.ByID(2008085448, path);
}

/**
 * OpenInTerminal opens a worktree path in a new Ghostty terminal tab.
 */
export function OpenInTerminal(path: string): $CancellablePromise<void> {
    return $Call.ByID(2865986369, path);
}

/**
 * SetProjectSandboxConfig replaces the sandbox configuration for a project.
 */
export function SetProjectSandboxConfig(id: string, cfg: project$0.SandboxConfig | null): $CancellablePromise<project$0.Project> {
    return $Call.ByID(1576743856, id, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetProjectSetupCommands replaces the setup commands for a project.
 */
export function SetProjectSetupCommands(id: string, cmds: string[]): $CancellablePromise<project$0.Project> {
    return $Call.ByID(1973010378, id, cmds).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetProjectWorktreeBaseRef sets the worktree branching base for a project.
 * ref must be "fresh" (branch off origin/<default>) or "head" (branch off local HEAD).
 */
export function SetProjectWorktreeBaseRef(id: string, ref: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(1094675552, id, ref).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateProject changes the type (pet/work) of a registered project.
 */
export function UpdateProject(id: string, ptype: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(3591840136, id, ptype).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = project$0.Project.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = project$0.Worktree.createFrom;
const $$createType3 = $Create.Array($$createType2);
