// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReviewService exposes PR review operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../github/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

/**
 * AddReviewComment adds a review comment at the given line.
 */
export function AddReviewComment(taskID: string, line: number, body: string): $CancellablePromise<task$0.ReviewComment> {
    return $Call.ByID(3725459231, taskID, line, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteReviewComment removes a review comment.
 */
export function DeleteReviewComment(taskID: string, commentID: string): $CancellablePromise<void> {
    return $Call.ByID(711574117, taskID, commentID);
}

/**
 * FetchReviews fetches the current PR review summary from GitHub.
 */
export function FetchReviews(): $CancellablePromise<github$0.ReviewSummary> {
    return $Call.ByID(2791730562).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListReviewComments returns all review comments for a task.
 */
export function ListReviewComments(taskID: string): $CancellablePromise<task$0.ReviewComment[]> {
    return $Call.ByID(3558593281, taskID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * MarkPRReady converts a PR from draft to ready-for-review.
 */
export function MarkPRReady(repo: string, $number: number): $CancellablePromise<void> {
    return $Call.ByID(2928259523, repo, $number);
}

/**
 * ResolveReviewComment marks a comment as resolved.
 */
export function ResolveReviewComment(taskID: string, commentID: string): $CancellablePromise<void> {
    return $Call.ByID(1366694494, taskID, commentID);
}

/**
 * StartFixReview starts a headless fix-review agent that applies unresolved
 * PR review comment fixes for the task's linked PR.
 */
export function StartFixReview(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1172415788, taskID);
}

/**
 * StartReview starts a headless review agent for the task's linked PR.
 */
export function StartReview(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3349085649, taskID);
}

// Private type creation functions
const $$createType0 = task$0.ReviewComment.createFrom;
const $$createType1 = github$0.ReviewSummary.createFrom;
const $$createType2 = $Create.Array($$createType0);
