// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService exposes statistics as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stats$0 from "../stats/models.js";

/**
 * GetStats returns aggregated agent run statistics.
 */
export function GetStats(): $CancellablePromise<stats$0.StatsResponse> {
    return $Call.ByID(1394194723).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = stats$0.StatsResponse.createFrom;
