// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService exposes task CRUD operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as artifact$0 from "../artifact/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssignTask persists a task pushed from the cluster leader into this
 * follower's local store (leader-follower execution mirror, umbrella #1803).
 * The task is written verbatim — the leader owns its canonical ID, status, and
 * workflow — and the file watcher then dispatches it through the normal
 * workflow, so nothing downstream changes. The pushed DTO is validated before
 * it touches disk; a malformed task is rejected with a 400 rather than
 * corrupting the board.
 */
export function AssignTask(t: task$0.Task): $CancellablePromise<void> {
    return $Call.ByID(835614146, t);
}

/**
 * BlessTampering records a human bless for a tamper-flagged task and sends it
 * back to the review workflow.
 */
export function BlessTampering(taskID: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(2730384212, taskID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateTask creates a new task and starts a matching workflow.
 * If the title is a GitHub issue URL, fetches real title/body from GitHub.
 */
export function CreateTask(title: string, body: string, mode: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(1715598451, title, body, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateTaskWithInit is CreateTask plus caller-supplied initial field
 * overrides (e.g. TodoistID) applied atomically in the same first-write as
 * task creation. Callers that need a dedupe key persisted alongside the task
 * — so a crash between create and a second update can never re-import the
 * same source item — should use this instead of CreateTask followed by a
 * separate Update.
 */
export function CreateTaskWithInit(title: string, body: string, mode: string, init: task$0.Update): $CancellablePromise<task$0.Task> {
    return $Call.ByID(1219464293, title, body, mode, init).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteTask removes a task file from disk and cleans up its worktree.
 */
export function DeleteTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1524059340, id);
}

/**
 * DispatchFromHumanRequired flips a task parked in human-required to target
 * (one of in-progress/testing/ready-pr/in-review), recording reason as the
 * audit-visible status_reason. For dispatching targets it synchronously
 * re-enters the workflow via task.status_changed; on any failure to do so it
 * fails closed, reverting the task to human-required with an explanatory
 * status_reason so the operator is never left with a task silently stuck in
 * a target status with no workflow driving it.
 * 
 * The whole check-then-write sequence runs under the workflow engine's
 * per-task human-action lock (shared with plan-review's
 * HandleHumanActionRecovering), so a double-click or a second operator cannot
 * race the same stuck task between the guard reads and the status write.
 */
export function DispatchFromHumanRequired(id: string, target: string, reason: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(3753750864, id, target, reason).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTamperReport returns the detector report artifact for a tamper-flagged task.
 */
export function GetTamperReport(taskID: string): $CancellablePromise<$models.TamperReportDTO> {
    return $Call.ByID(929982993, taskID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTask returns a single task by ID.
 */
export function GetTask(id: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(2262172043, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTaskSetupLog(taskID: string): $CancellablePromise<$models.TaskSetupLogDTO> {
    return $Call.ByID(3273454814, taskID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListTaskArtifacts(taskID: string): $CancellablePromise<$models.TaskArtifactDTO[]> {
    return $Call.ByID(1612534482, taskID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListTaskAuditEvents(taskID: string, days: number): $CancellablePromise<$models.TaskAuditEventDTO[]> {
    return $Call.ByID(1451731527, taskID, days).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListTaskProgress returns the agent-authored progress entries for a task.
 * Empty (not an error) when the task has no progress log yet.
 */
export function ListTaskProgress(taskID: string): $CancellablePromise<artifact$0.ProgressEntry[]> {
    return $Call.ByID(821819796, taskID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListTasks returns all tasks from the store, excluding ephemeral chat tasks.
 * Chat tasks are surfaced exclusively through the Chats view.
 */
export function ListTasks(): $CancellablePromise<task$0.Task[]> {
    return $Call.ByID(3360976520).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ReconcilePendingEnrichment re-attempts GitHub enrichment for URL stubs whose
 * initial async enrichment never completed. A stub is created with the raw URL
 * as its title and the enrich-pending marker; enrichment then runs in a
 * fire-and-forget goroutine that, on any failure (a transient GitHub rate
 * limit / gateway blip, or the app exiting before it finished), simply logs and
 * returns. The marker is never cleared, so the stub keeps its raw-URL title
 * forever and — because URL stubs only dispatch a workflow once the marker
 * clears — never starts one. This is the recovery path for that orphaned state:
 * the still-present marker is the retry signal, and the enrich functions are
 * idempotent, so re-running them either succeeds now or fails the same benign
 * way. Driven from the maintenance pass so recovery is continuous rather than a
 * one-shot at startup.
 */
export function ReconcilePendingEnrichment(): $CancellablePromise<void> {
    return $Call.ByID(4012524128);
}

/**
 * RecoverLostAgent is a follower RPC the leader uses after it has
 * authoritatively detected a lost-agent anomaly on a follower-owned task.
 * It mirrors the local monitor path: best-effort stop the stale running run,
 * then hand the task to recovery for a targeted restart.
 */
export function RecoverLostAgent(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(340379341, taskID);
}

/**
 * UpdateTask applies field updates to a task. The workflow engine drives
 * all status-based transitions; this method only handles cleanup on done.
 * 
 * Moving a task to "testing" is refused if another workflow is still active —
 * the testing workflow needs a clean slate (no in-flight agents or pending
 * human steps) so the user can't accidentally lose context by dragging.
 * 
 * Moving a task to "in-progress" when its workflow is terminal (completed or
 * failed) and no agent is running restarts the workflow — allowing the user to
 * retry implementation after a human-required escalation.
 */
export function UpdateTask(id: string, updates: { [_ in string]?: any }): $CancellablePromise<task$0.Task> {
    return $Call.ByID(3948756754, id, updates).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $models.TamperReportDTO.createFrom;
const $$createType2 = $models.TaskSetupLogDTO.createFrom;
const $$createType3 = $models.TaskArtifactDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.TaskAuditEventDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = artifact$0.ProgressEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType0);
