// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService exposes task CRUD operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as artifact$0 from "../artifact/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BlessTampering records a human bless for a tamper-flagged task and sends it
 * back to the review workflow.
 */
export function BlessTampering(taskID: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(2730384212, taskID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateTask creates a new task and starts a matching workflow.
 * If the title is a GitHub issue URL, fetches real title/body from GitHub.
 */
export function CreateTask(title: string, body: string, mode: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(1715598451, title, body, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteTask removes a task file from disk and cleans up its worktree.
 */
export function DeleteTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1524059340, id);
}

/**
 * DispatchFromHumanRequired flips a task parked in human-required to target
 * (one of in-progress/testing/ready-pr/in-review), recording reason as the
 * audit-visible status_reason. For dispatching targets it synchronously
 * re-enters the workflow via task.status_changed; on any failure to do so it
 * fails closed, reverting the task to human-required with an explanatory
 * status_reason so the operator is never left with a task silently stuck in
 * a target status with no workflow driving it.
 * 
 * The whole check-then-write sequence runs under the workflow engine's
 * per-task human-action lock (shared with plan-review's
 * HandleHumanActionRecovering), so a double-click or a second operator cannot
 * race the same stuck task between the guard reads and the status write.
 */
export function DispatchFromHumanRequired(id: string, target: string, reason: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(3753750864, id, target, reason).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTamperReport returns the detector report artifact for a tamper-flagged task.
 */
export function GetTamperReport(taskID: string): $CancellablePromise<$models.TamperReportDTO> {
    return $Call.ByID(929982993, taskID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTask returns a single task by ID.
 */
export function GetTask(id: string): $CancellablePromise<task$0.Task> {
    return $Call.ByID(2262172043, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListTaskProgress returns the agent-authored progress entries for a task.
 * Empty (not an error) when the task has no progress log yet.
 */
export function ListTaskProgress(taskID: string): $CancellablePromise<artifact$0.ProgressEntry[]> {
    return $Call.ByID(821819796, taskID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListTasks returns all tasks from the store, excluding ephemeral chat tasks.
 * Chat tasks are surfaced exclusively through the Chats view.
 */
export function ListTasks(): $CancellablePromise<task$0.Task[]> {
    return $Call.ByID(3360976520).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ReconcilePendingEnrichment re-attempts GitHub enrichment for URL stubs whose
 * initial async enrichment never completed. A stub is created with the raw URL
 * as its title and the enrich-pending marker; enrichment then runs in a
 * fire-and-forget goroutine that, on any failure (a transient GitHub rate
 * limit / gateway blip, or the app exiting before it finished), simply logs and
 * returns. The marker is never cleared, so the stub keeps its raw-URL title
 * forever and — because URL stubs only dispatch a workflow once the marker
 * clears — never starts one. This is the recovery path for that orphaned state:
 * the still-present marker is the retry signal, and the enrich functions are
 * idempotent, so re-running them either succeeds now or fails the same benign
 * way. Driven from the maintenance pass so recovery is continuous rather than a
 * one-shot at startup.
 */
export function ReconcilePendingEnrichment(): $CancellablePromise<void> {
    return $Call.ByID(4012524128);
}

/**
 * UpdateTask applies field updates to a task. The workflow engine drives
 * all status-based transitions; this method only handles cleanup on done.
 * 
 * Moving a task to "testing" is refused if another workflow is still active —
 * the testing workflow needs a clean slate (no in-flight agents or pending
 * human steps) so the user can't accidentally lose context by dragging.
 * 
 * Moving a task to "in-progress" when its workflow is terminal (completed or
 * failed) and no agent is running restarts the workflow — allowing the user to
 * retry implementation after a human-required escalation.
 */
export function UpdateTask(id: string, updates: { [_ in string]?: any }): $CancellablePromise<task$0.Task> {
    return $Call.ByID(3948756754, id, updates).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $models.TamperReportDTO.createFrom;
const $$createType2 = artifact$0.ProgressEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
