// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkflowService exposes workflow operations as Wails-bound methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflow$0 from "../workflow/models.js";

/**
 * DeleteWorkflow removes a workflow definition.
 */
export function DeleteWorkflow(id: string): $CancellablePromise<void> {
    return $Call.ByID(2564240248, id);
}

/**
 * GetWorkflow returns a workflow definition by ID.
 */
export function GetWorkflow(id: string): $CancellablePromise<workflow$0.Definition> {
    return $Call.ByID(1729656583, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * HandleHumanAction processes approve/reject/input for a waiting workflow step.
 */
export function HandleHumanAction(taskID: string, action: string, data: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(1175600199, taskID, action, data);
}

/**
 * ListWorkflows returns all workflow definitions.
 */
export function ListWorkflows(): $CancellablePromise<workflow$0.Definition[]> {
    return $Call.ByID(775493116).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetBuiltin resets a built-in workflow to its default definition.
 */
export function ResetBuiltin(id: string): $CancellablePromise<void> {
    return $Call.ByID(3225512920, id);
}

/**
 * SaveWorkflow creates or updates a workflow definition.
 */
export function SaveWorkflow(def: workflow$0.Definition): $CancellablePromise<void> {
    return $Call.ByID(1534207134, def);
}

/**
 * StartWorkflow assigns and starts a workflow on a task.
 */
export function StartWorkflow(taskID: string, workflowID: string): $CancellablePromise<void> {
    return $Call.ByID(541729299, taskID, workflowID);
}

// Private type creation functions
const $$createType0 = workflow$0.Definition.createFrom;
const $$createType1 = $Create.Array($$createType0);
