// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Kind classifies an artifact's role in the workflow.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindPlan holds a raw markdown plan snapshot.
     */
    KindPlan = "plan",

    /**
     * KindTrace holds an append-only NDJSON stream of step-completion events.
     */
    KindTrace = "trace",
    KindProgress = "progress",

    /**
     * KindGeneric is a catch-all for helper blobs that don't fit the above.
     */
    KindGeneric = "generic",
};

export class ProgressEntry {
    "ts": time$0.Time;
    "kind": string;
    "role"?: string;
    "message": string;

    /** Creates a new ProgressEntry instance. */
    constructor($$source: Partial<ProgressEntry> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = null;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgressEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressEntry($$parsedSource as Partial<ProgressEntry>);
    }
}
