// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CycleSnapshot captures a provider-reported rolling limit window.
 */
export class CycleSnapshot {
    "usedPercent": number;
    "windowMinutes": number;
    "resetsAt"?: time$0.Time;

    /** Creates a new CycleSnapshot instance. */
    constructor($$source: Partial<CycleSnapshot> = {}) {
        if (!("usedPercent" in $$source)) {
            this["usedPercent"] = 0;
        }
        if (!("windowMinutes" in $$source)) {
            this["windowMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CycleSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): CycleSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CycleSnapshot($$parsedSource as Partial<CycleSnapshot>);
    }
}

/**
 * ProviderSummary is the frontend/statistics view of one provider's limit and
 * API-equivalent spend. Exact quota percentages are included only when a
 * provider exposes them locally.
 */
export class ProviderSummary {
    "provider": string;
    "planType"?: string;
    "limitId"?: string;
    "source"?: string;
    "confidence"?: string;
    "sessionUsedPercent"?: number;
    "sessionResetsAt"?: time$0.Time;
    "sessionWindowMinutes"?: number;
    "weeklyUsedPercent"?: number;
    "weeklyResetsAt"?: time$0.Time;
    "weeklyWindowMinutes"?: number;
    "sessionSpendUsd"?: number;
    "weeklySpendUsd"?: number;
    "sessionInputTokens"?: number;
    "sessionOutputTokens"?: number;
    "sessionCacheReadTokens"?: number;
    "sessionReasoningTokens"?: number;
    "sessionPremiumRequests"?: number;
    "weeklyInputTokens"?: number;
    "weeklyOutputTokens"?: number;
    "weeklyCacheReadTokens"?: number;
    "weeklyReasoningTokens"?: number;
    "weeklyPremiumRequests"?: number;
    "monthlySubscriptionUsd"?: number;
    "monthlySubscriptionBurnRate"?: number;
    "quotaLimited"?: boolean;
    "quotaReason"?: string;

    /** Creates a new ProviderSummary instance. */
    constructor($$source: Partial<ProviderSummary> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderSummary($$parsedSource as Partial<ProviderSummary>);
    }
}

/**
 * Snapshot is the latest known quota/limit state for one provider.
 */
export class Snapshot {
    "provider": string;
    "planType"?: string;
    "limitId"?: string;
    "limitName"?: string;
    "rateLimitReachedType"?: string;
    "primary"?: CycleSnapshot | null;
    "secondary"?: CycleSnapshot | null;
    "source": string;
    "confidence": string;
    "capturedAt": time$0.Time;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }
        if (!("capturedAt" in $$source)) {
            this["capturedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary" in $$parsedSource) {
            $$parsedSource["primary"] = $$createField5_0($$parsedSource["primary"]);
        }
        if ("secondary" in $$parsedSource) {
            $$parsedSource["secondary"] = $$createField6_0($$parsedSource["secondary"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

/**
 * Summary is embedded in stats.StatsResponse.
 */
export class Summary {
    "providers": ProviderSummary[];
    "updatedAt"?: time$0.Time;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField0_0($$parsedSource["providers"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = CycleSnapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ProviderSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
