// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * GroupedStat is an aggregate keyed by a dimension (project, mode, etc).
 */
export class GroupedStat {
    "key": string;
    "stats": Summary;

    /** Creates a new GroupedStat instance. */
    constructor($$source: Partial<GroupedStat> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new Summary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupedStat instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupedStat {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField1_0($$parsedSource["stats"]);
        }
        return new GroupedStat($$parsedSource as Partial<GroupedStat>);
    }
}

/**
 * RunRecord captures a single agent execution for analytics.
 */
export class RunRecord {
    "id": string;
    "taskId": string;
    "projectId"?: string;
    "mode": string;
    "role": string;
    "model"?: string;
    "provider"?: string;
    "costUsd": number;
    "durationS": number;
    "inputTokens"?: number;
    "outputTokens"?: number;
    "outcome": string;
    "timestamp": time$0.Time;

    /** Creates a new RunRecord instance. */
    constructor($$source: Partial<RunRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("durationS" in $$source)) {
            this["durationS"] = 0;
        }
        if (!("outcome" in $$source)) {
            this["outcome"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): RunRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunRecord($$parsedSource as Partial<RunRecord>);
    }
}

/**
 * StatsResponse is the full analytics payload returned to the frontend.
 */
export class StatsResponse {
    "today": Summary;
    "thisWeek": Summary;
    "thisMonth": Summary;
    "allTime": Summary;
    "byProject": GroupedStat[];
    "byProjectType": GroupedStat[];
    "byMode": GroupedStat[];
    "byRole": GroupedStat[];
    "byModel": GroupedStat[];
    "byProvider": GroupedStat[];
    "recentRuns": RunRecord[];

    /** Creates a new StatsResponse instance. */
    constructor($$source: Partial<StatsResponse> = {}) {
        if (!("today" in $$source)) {
            this["today"] = (new Summary());
        }
        if (!("thisWeek" in $$source)) {
            this["thisWeek"] = (new Summary());
        }
        if (!("thisMonth" in $$source)) {
            this["thisMonth"] = (new Summary());
        }
        if (!("allTime" in $$source)) {
            this["allTime"] = (new Summary());
        }
        if (!("byProject" in $$source)) {
            this["byProject"] = [];
        }
        if (!("byProjectType" in $$source)) {
            this["byProjectType"] = [];
        }
        if (!("byMode" in $$source)) {
            this["byMode"] = [];
        }
        if (!("byRole" in $$source)) {
            this["byRole"] = [];
        }
        if (!("byModel" in $$source)) {
            this["byModel"] = [];
        }
        if (!("byProvider" in $$source)) {
            this["byProvider"] = [];
        }
        if (!("recentRuns" in $$source)) {
            this["recentRuns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsResponse {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("today" in $$parsedSource) {
            $$parsedSource["today"] = $$createField0_0($$parsedSource["today"]);
        }
        if ("thisWeek" in $$parsedSource) {
            $$parsedSource["thisWeek"] = $$createField1_0($$parsedSource["thisWeek"]);
        }
        if ("thisMonth" in $$parsedSource) {
            $$parsedSource["thisMonth"] = $$createField2_0($$parsedSource["thisMonth"]);
        }
        if ("allTime" in $$parsedSource) {
            $$parsedSource["allTime"] = $$createField3_0($$parsedSource["allTime"]);
        }
        if ("byProject" in $$parsedSource) {
            $$parsedSource["byProject"] = $$createField4_0($$parsedSource["byProject"]);
        }
        if ("byProjectType" in $$parsedSource) {
            $$parsedSource["byProjectType"] = $$createField5_0($$parsedSource["byProjectType"]);
        }
        if ("byMode" in $$parsedSource) {
            $$parsedSource["byMode"] = $$createField6_0($$parsedSource["byMode"]);
        }
        if ("byRole" in $$parsedSource) {
            $$parsedSource["byRole"] = $$createField7_0($$parsedSource["byRole"]);
        }
        if ("byModel" in $$parsedSource) {
            $$parsedSource["byModel"] = $$createField8_0($$parsedSource["byModel"]);
        }
        if ("byProvider" in $$parsedSource) {
            $$parsedSource["byProvider"] = $$createField9_0($$parsedSource["byProvider"]);
        }
        if ("recentRuns" in $$parsedSource) {
            $$parsedSource["recentRuns"] = $$createField10_0($$parsedSource["recentRuns"]);
        }
        return new StatsResponse($$parsedSource as Partial<StatsResponse>);
    }
}

/**
 * Summary holds aggregate metrics over a set of runs.
 */
export class Summary {
    "totalCostUsd": number;
    "totalRuns": number;
    "avgCostPerRun": number;
    "avgDurationS": number;
    "totalDurationS": number;
    "totalInputTokens": number;
    "totalOutputTokens": number;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("totalCostUsd" in $$source)) {
            this["totalCostUsd"] = 0;
        }
        if (!("totalRuns" in $$source)) {
            this["totalRuns"] = 0;
        }
        if (!("avgCostPerRun" in $$source)) {
            this["avgCostPerRun"] = 0;
        }
        if (!("avgDurationS" in $$source)) {
            this["avgDurationS"] = 0;
        }
        if (!("totalDurationS" in $$source)) {
            this["totalDurationS"] = 0;
        }
        if (!("totalInputTokens" in $$source)) {
            this["totalInputTokens"] = 0;
        }
        if (!("totalOutputTokens" in $$source)) {
            this["totalOutputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = Summary.createFrom;
const $$createType1 = GroupedStat.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = RunRecord.createFrom;
const $$createType4 = $Create.Array($$createType3);
