CREATE TABLE IF NOT EXISTS projects (
	id TEXT PRIMARY KEY,
	owner TEXT NOT NULL DEFAULT '',
	repo TEXT NOT NULL DEFAULT '',
	type TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT '',
	clone_path TEXT NOT NULL DEFAULT '',
	updated_at BIGINT NOT NULL DEFAULT 0,
	doc TEXT NOT NULL
)
