// Package attribution stamps Sybra-authored GitHub content with a harness
// attribution footer, so PR replies, PR/issue comments, and similar artifacts
// are identifiable as machine-generated rather than human-written.
//
// Two layers carry the marker, mirroring internal/scrub's floor+ceiling shape:
//   - Go-authored text (e.g. monitor issue comments) is stamped deterministically
//     via Append at the gh call site.
//   - Agent-authored text (e.g. fix-review thread replies) is instructed to end
//     with Footer through skill/prompt copy; the exact string lives here so the
//     two stay in sync.
package attribution

import "strings"

// Footer is the marker appended to harness-authored GitHub text. Keep this in
// sync with the skill copy in internal/skills/data/fix-review-auto.md and the
// fix-agent prompt in internal/sybra/app_reviews_fix.go.
const Footer = "_Generated by Sybra harness_"

// Append returns body with the harness attribution footer appended after a
// blank line. It is idempotent (a body already carrying the footer is returned
// unchanged) and leaves an empty body untouched — there is nothing to attribute.
func Append(body string) string {
	trimmed := strings.TrimRight(body, " \t\r\n")
	if trimmed == "" {
		return body
	}
	if strings.HasSuffix(trimmed, Footer) {
		return body
	}
	return trimmed + "\n\n" + Footer
}
