// Package attribution stamps Sybra-authored GitHub content with a harness
// attribution footer, so PR bodies, PR replies, PR/issue comments, and similar
// artifacts are identifiable as machine-generated rather than human-written.
//
// Two layers carry the marker, mirroring internal/scrub's floor+ceiling shape:
//   - Go-authored text (e.g. monitor issue comments, the stamp_pr_attribution
//     workflow step) is stamped deterministically via Append at the gh call site.
//   - Agent-authored text (e.g. fix-review thread replies, create-pr PR bodies,
//     pr-review workflow review comments) is instructed to end with Footer
//     through skill/prompt copy; the exact string lives here so the two stay
//     in sync.
package attribution

import "strings"

// Footer is the marker appended to harness-authored GitHub text. The pr-fix
// prompt renders this constant into its reply templates
// (internal/sybra/review/prompts/fix-review.md); the operator-invocable
// fix-review-auto skill spells the same string out and must stay in sync.
const Footer = "_Generated by Sybra harness_"

// Append returns body with the harness attribution footer appended after a
// blank line. It is idempotent (a body already carrying the footer is returned
// unchanged) and leaves an empty body untouched — there is nothing to attribute.
func Append(body string) string {
	trimmed := strings.TrimRight(body, " \t\r\n")
	if trimmed == "" {
		return body
	}
	if strings.HasSuffix(trimmed, Footer) {
		return body
	}
	return trimmed + "\n\n" + Footer
}
