// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentDefaults {
    "provider": string;
    "model": string;
    "mode": string;
    "maxConcurrent": number;
    "researchMachineDir": string;
    "maxCostUsd": number;
    "maxTurns": number;

    /**
     * TurnCostFraction is the fraction of MaxCostUSD below which a turns
     * escalation is auto-continued. Default 0.8 when unset.
     */
    "turnCostFraction": number;

    /**
     * TurnMultiplier scales the turn limit on each auto-continuation. Default 2 when unset.
     */
    "turnMultiplier": number;

    /**
     * RequirePermissions sets the default permission requirement for agents.
     * nil means not configured (falls back to true — safe default).
     * Set to false in config to opt all tasks into skip-permissions mode.
     */
    "requirePermissions": boolean | null;

    /**
     * BashTimeoutSeconds sets the per-bash-tool-call timeout passed to
     * claude -p via the BASH_DEFAULT_TIMEOUT_MS / BASH_MAX_TIMEOUT_MS env
     * vars (claude has no equivalent CLI flag). 0 means use
     * DefaultBashTimeoutSeconds (300).
     */
    "bashTimeoutSeconds": number;

    /**
     * RetryWatchdog sets CLAUDE_CODE_RETRY_WATCHDOG on the claude subprocess
     * for headless (unattended) runs. Replaces CLAUDE_CODE_MAX_RETRIES (now
     * capped at 15) for server/unattended sessions. 0 means use
     * DefaultRetryWatchdog (30). Negative (e.g. -1) disables the watchdog
     * entirely (env var omitted), matching the zero-omit semantics at the
     * RunConfig level.
     */
    "retryWatchdog": number;

    /**
     * FallbackModel, when set, passes --fallback-model to claude for headless
     * runs. Paired with RetryWatchdog so the watchdog can retry with a less
     * loaded model when the primary is overloaded.
     */
    "fallbackModel": string;

    /**
     * MaxLogEvents caps how many NDJSON events are returned when replaying
     * a completed agent's log file. 0 means use DefaultMaxLogEvents (500).
     */
    "maxLogEvents": number;

    /**
     * LogRetentionDays bounds how long per-agent NDJSON log files live
     * under ~/.sybra/logs/agents/. Files older than this (plus all 0-byte
     * files, regardless of age) are swept on app startup and daily
     * thereafter. 0 falls back to DefaultLogRetentionDays (14).
     */
    "logRetentionDays": number;

    /**
     * SurviveRestart keeps agent subprocesses running across an app
     * restart (detached, output streamed to their log files) and reattaches
     * to them on the next startup. nil means not configured (defaults to
     * true). Set false to revert to the legacy behaviour where agents are
     * killed on shutdown and recovered via restart-stale.
     */
    "surviveRestart": boolean | null;

    /**
     * ApprovalPort pins the localhost port of the PreToolUse approval
     * server. The hook URL is baked into a permission-gated agent's
     * --settings at spawn, so a fixed port lets a detached agent's approval
     * requests still resolve after a restart. 0 (default) binds a random
     * port (no cross-restart approval survival).
     */
    "approvalPort": number;

    /** Creates a new AgentDefaults instance. */
    constructor($$source: Partial<AgentDefaults> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("researchMachineDir" in $$source)) {
            this["researchMachineDir"] = "";
        }
        if (!("maxCostUsd" in $$source)) {
            this["maxCostUsd"] = 0;
        }
        if (!("maxTurns" in $$source)) {
            this["maxTurns"] = 0;
        }
        if (!("turnCostFraction" in $$source)) {
            this["turnCostFraction"] = 0;
        }
        if (!("turnMultiplier" in $$source)) {
            this["turnMultiplier"] = 0;
        }
        if (!("requirePermissions" in $$source)) {
            this["requirePermissions"] = null;
        }
        if (!("bashTimeoutSeconds" in $$source)) {
            this["bashTimeoutSeconds"] = 0;
        }
        if (!("retryWatchdog" in $$source)) {
            this["retryWatchdog"] = 0;
        }
        if (!("fallbackModel" in $$source)) {
            this["fallbackModel"] = "";
        }
        if (!("maxLogEvents" in $$source)) {
            this["maxLogEvents"] = 0;
        }
        if (!("logRetentionDays" in $$source)) {
            this["logRetentionDays"] = 0;
        }
        if (!("surviveRestart" in $$source)) {
            this["surviveRestart"] = null;
        }
        if (!("approvalPort" in $$source)) {
            this["approvalPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentDefaults($$parsedSource as Partial<AgentDefaults>);
    }
}

export class AuditConfig {
    "enabled": boolean;
    "retentionDays": number;

    /** Creates a new AuditConfig instance. */
    constructor($$source: Partial<AuditConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("retentionDays" in $$source)) {
            this["retentionDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditConfig($$parsedSource as Partial<AuditConfig>);
    }
}

export class NotificationConfig {
    "desktop": boolean;

    /** Creates a new NotificationConfig instance. */
    constructor($$source: Partial<NotificationConfig> = {}) {
        if (!("desktop" in $$source)) {
            this["desktop"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationConfig($$parsedSource as Partial<NotificationConfig>);
    }
}

export class OrchestratorConfig {
    "autoTriage": boolean;
    "autoPlan": boolean;

    /** Creates a new OrchestratorConfig instance. */
    constructor($$source: Partial<OrchestratorConfig> = {}) {
        if (!("autoTriage" in $$source)) {
            this["autoTriage"] = false;
        }
        if (!("autoPlan" in $$source)) {
            this["autoPlan"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrchestratorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): OrchestratorConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrchestratorConfig($$parsedSource as Partial<OrchestratorConfig>);
    }
}

export class ProviderEntryConfig {
    "enabled": boolean;
    "rateLimitCooldownSeconds": number;

    /** Creates a new ProviderEntryConfig instance. */
    constructor($$source: Partial<ProviderEntryConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("rateLimitCooldownSeconds" in $$source)) {
            this["rateLimitCooldownSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderEntryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderEntryConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderEntryConfig($$parsedSource as Partial<ProviderEntryConfig>);
    }
}

export class ProviderHealthCheckConfig {
    "enabled": boolean;
    "intervalSeconds": number;

    /** Creates a new ProviderHealthCheckConfig instance. */
    constructor($$source: Partial<ProviderHealthCheckConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderHealthCheckConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderHealthCheckConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderHealthCheckConfig($$parsedSource as Partial<ProviderHealthCheckConfig>);
    }
}

/**
 * ProvidersConfig groups per-machine routing for CLI providers (claude, codex)
 * and their background health-check loop. A missing block defaults to "both
 * providers enabled, health check on, auto-failover on, 300s interval".
 */
export class ProvidersConfig {
    "healthCheck": ProviderHealthCheckConfig;
    "claude": ProviderEntryConfig;
    "codex": ProviderEntryConfig;
    "autoFailover": boolean;

    /** Creates a new ProvidersConfig instance. */
    constructor($$source: Partial<ProvidersConfig> = {}) {
        if (!("healthCheck" in $$source)) {
            this["healthCheck"] = (new ProviderHealthCheckConfig());
        }
        if (!("claude" in $$source)) {
            this["claude"] = (new ProviderEntryConfig());
        }
        if (!("codex" in $$source)) {
            this["codex"] = (new ProviderEntryConfig());
        }
        if (!("autoFailover" in $$source)) {
            this["autoFailover"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProvidersConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProvidersConfig {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("healthCheck" in $$parsedSource) {
            $$parsedSource["healthCheck"] = $$createField0_0($$parsedSource["healthCheck"]);
        }
        if ("claude" in $$parsedSource) {
            $$parsedSource["claude"] = $$createField1_0($$parsedSource["claude"]);
        }
        if ("codex" in $$parsedSource) {
            $$parsedSource["codex"] = $$createField2_0($$parsedSource["codex"]);
        }
        return new ProvidersConfig($$parsedSource as Partial<ProvidersConfig>);
    }
}

export class RenovateConfig {
    "enabled": boolean;
    "author": string;

    /** Creates a new RenovateConfig instance. */
    constructor($$source: Partial<RenovateConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenovateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RenovateConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenovateConfig($$parsedSource as Partial<RenovateConfig>);
    }
}

export class TodoistConfig {
    "enabled": boolean;
    "apiToken": string;
    "projectId": string;
    "defaultProjectId": string;
    "pollSeconds": number;

    /** Creates a new TodoistConfig instance. */
    constructor($$source: Partial<TodoistConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("apiToken" in $$source)) {
            this["apiToken"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("defaultProjectId" in $$source)) {
            this["defaultProjectId"] = "";
        }
        if (!("pollSeconds" in $$source)) {
            this["pollSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoistConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoistConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoistConfig($$parsedSource as Partial<TodoistConfig>);
    }
}

// Private type creation functions
const $$createType0 = ProviderHealthCheckConfig.createFrom;
const $$createType1 = ProviderEntryConfig.createFrom;
