// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentDefaults {
    "provider": string;
    "model": string;
    "mode": string;
    "maxConcurrent": number;
    "researchMachineDir": string;
    "maxCostUsd": number;
    "maxTurns": number;

    /**
     * MaxCheckpoints bounds how many times a single workflow step may
     * checkpoint-and-handoff after hitting the per-run turn ceiling. 0 means
     * use DefaultMaxCheckpoints (3).
     */
    "maxCheckpoints": number;

    /**
     * CheckpointOnTurnCeiling swaps the legacy raise-MaxTurns auto-continue for
     * a checkpoint-and-handoff to a fresh run when an eligible code-author
     * headless run hits its per-run turn ceiling. nil means not configured
     * (defaults to true). Set false to restore the legacy in-process
     * auto-continue behavior with no code revert.
     */
    "checkpointOnTurnCeiling": boolean | null;

    /**
     * MaxTaskCostUSD caps the cumulative USD cost across every AgentRun a task
     * has ever had (unlike MaxCostUSD, which resets every run). Closes the gap
     * where each retry stays under the per-run cap but the task's total spend
     * still balloons unbounded. Checked once per dispatch, before an agent is
     * started — StartAgentWithAssignment refuses to start and flips the task
     * to human-required when the task's already-recorded AgentRuns.CostUSD sum
     * meets or exceeds this. 0 (default) disables the check.
     */
    "maxTaskCostUsd": number;

    /**
     * TurnCostFraction is the fraction of MaxCostUSD below which a turns
     * escalation is auto-continued. Default 0.8 when unset.
     */
    "turnCostFraction": number;

    /**
     * TurnMultiplier scales the turn limit on each auto-continuation. Default 2 when unset.
     */
    "turnMultiplier": number;

    /**
     * RequirePermissions sets the default permission requirement for agents.
     * nil means not configured (falls back to true — safe default).
     * Set to false in config to opt all tasks into skip-permissions mode.
     */
    "requirePermissions": boolean | null;

    /**
     * ReviewUntilClean keeps simple-task-review cycling review→fix→review
     * until the reviewer returns a CLEAN verdict, so the fix agent's diff is
     * never the last word. nil means not configured (falls back to true).
     * The cycle is uncapped by design — a round cap would censor the
     * review-rounds distribution the stats page reports — and is bounded only
     * by MaxTaskCostUSD, which is enforced before every dispatch. false falls
     * back to a single review pass per task: cheaper and more predictable when
     * no per-task budget is configured.
     */
    "reviewUntilClean": boolean | null;

    /**
     * BashTimeoutSeconds sets the per-bash-tool-call timeout passed to
     * claude -p via the BASH_DEFAULT_TIMEOUT_MS / BASH_MAX_TIMEOUT_MS env
     * vars (claude has no equivalent CLI flag). 0 means use
     * DefaultBashTimeoutSeconds (300).
     */
    "bashTimeoutSeconds": number;

    /**
     * RetryWatchdog sets CLAUDE_CODE_RETRY_WATCHDOG on the claude subprocess
     * for headless (unattended) runs. Replaces CLAUDE_CODE_MAX_RETRIES (now
     * capped at 15) for server/unattended sessions. 0 means use
     * DefaultRetryWatchdog (30). Negative (e.g. -1) disables the watchdog
     * entirely (env var omitted), matching the zero-omit semantics at the
     * RunConfig level.
     */
    "retryWatchdog": number;

    /**
     * FallbackModel, when set, passes --fallback-model to claude for headless
     * runs. Paired with RetryWatchdog so the watchdog can retry with a less
     * loaded model when the primary is overloaded.
     */
    "fallbackModel": string;

    /**
     * MaxLogEvents caps how many NDJSON events are returned when replaying
     * a completed agent's log file. 0 means use DefaultMaxLogEvents (500).
     */
    "maxLogEvents": number;

    /**
     * LogRetentionDays bounds how long per-agent NDJSON log files live
     * under ~/.sybra/logs/agents/. Files older than this (plus all 0-byte
     * files, regardless of age) are swept on app startup and daily
     * thereafter. 0 falls back to DefaultLogRetentionDays (14). A negative
     * value disables age-based deletion (0-byte files are still removed).
     */
    "logRetentionDays": number;

    /**
     * LogGzipAfterDays bounds how long a retained per-agent NDJSON log
     * stays uncompressed before the retention sweep gzips it in place
     * (original removed once the .gz sibling is written successfully). 0
     * falls back to DefaultLogGzipAfterDays (3). A negative value disables
     * compression entirely.
     */
    "logGzipAfterDays": number;

    /**
     * LogRetentionMaxSizeMB caps the total size (in MB) of the per-agent
     * NDJSON log directory (~/.sybra/logs/agents/, including any
     * gzip-compressed and .stderr sidecar files). When the age/gzip passes
     * still leave the directory over this cap, the sweep deletes the
     * oldest non-active files (by mtime) until it's back under the cap, or
     * only currently-active agents' logs remain. 0 falls back to
     * DefaultLogRetentionMaxSizeMB (1024, i.e. 1 GiB). A negative value
     * disables size-based enforcement entirely.
     */
    "logRetentionMaxSizeMb": number;

    /**
     * SurviveRestart keeps agent subprocesses running across an app
     * restart (detached, output streamed to their log files) and reattaches
     * to them on the next startup. nil means not configured (defaults to
     * true). Set false to revert to the legacy behaviour where agents are
     * killed on shutdown and recovered via restart-stale.
     */
    "surviveRestart": boolean | null;

    /**
     * ApprovalPort pins the localhost port of the PreToolUse approval
     * server. The hook URL is baked into a permission-gated agent's
     * --settings at spawn, so a fixed port lets a detached agent's approval
     * requests still resolve after a restart. 0 (default) binds a random
     * port (no cross-restart approval survival).
     */
    "approvalPort": number;

    /**
     * HeadlessPermissionMode sets the default permission posture for unattended
     * headless claude runs. "bypass" (default) keeps the current
     * --dangerously-skip-permissions behavior. "auto" emits --permission-mode auto
     * which activates the Claude Code auto-mode classifier (blocks destructive ops
     * such as rm -rf $HOME, force-push, terraform destroy). Empty treated as "bypass".
     */
    "headlessPermissionMode": string;

    /**
     * DispatchJitterMs bounds a uniform random delay applied before headless
     * agent dispatch, so a wave of concurrently ready tasks does not all
     * probe the provider health gate in the same tick. 0 disables jitter.
     * Never applied to interactive/chat dispatch. Default 1000 — set 0 to
     * disable.
     */
    "dispatchJitterMs": number;

    /**
     * SandboxMode sets the default OS-level process-sandbox posture for agent
     * subprocesses (darwin: sandbox-exec seatbelt, linux: bwrap). "off"
     * spawns unwrapped with no validation. "report" (default) validates and
     * logs the resolved write allowlist (worktree/sandbox-home/tmp plus
     * task-scoped git metadata) without ever wrapping the spawn, so a
     * profile/wrapper defect can only affect an explicit "enforce" posture,
     * never the default rollout posture. "enforce" actually wraps the spawn
     * and blocks writes outside that allowlist, failing the spawn closed if
     * the wrapper is unavailable.
     * Empty treated as "report".
     */
    "sandboxMode": string;

    /**
     * HeadlessSteerable controls whether headless claude runs launch with the
     * stdin/stream-json shape that accepts mid-run steer messages (instead of
     * the legacy one-shot `-p <prompt>` invocation). nil means not configured
     * (defaults to true). Set false to restore the legacy launch shape with
     * no stdin transport — a config-only rollback with no code revert.
     */
    "headlessSteerable": boolean | null;

    /**
     * DefaultProjectID pins the project a project-less task auto-assigns to
     * when it needs an isolated worktree (e.g. a meta/self-referential task
     * routed to the plan step). Without it, auto-assignment only fires when
     * exactly one project is registered — on a machine with two or more
     * projects, a project-less task can never dispatch and always ends up
     * human-required. Empty means no default (falls back to the
     * sole-project behavior).
     */
    "defaultProjectId": string;

    /**
     * RoleEffort overrides the built-in per-role reasoning-effort baseline
     * (see agent.Role.DefaultReasoningEffort), keyed by role name (e.g.
     * "triage", "implementation"). Still loses to an experiment assignment's
     * or the task's own ReasoningEffort — this only replaces the role
     * fallback, not an explicit per-task/per-run override. Unknown role keys
     * or invalid effort values are ignored (falls back to the built-in
     * default for that role).
     */
    "roleEffort": { [_ in string]?: string };

    /**
     * PlaywrightMCP configures the default-off headless Playwright MCP server
     * attached to test-runner runs that resolve to the Claude provider.
     */
    "playwrightMcp": PlaywrightMCPConfig;

    /**
     * K8sJobs configures an experimental backend that runs headless agents as
     * short-lived Kubernetes Jobs instead of local subprocesses.
     */
    "k8sJobs": K8sJobsConfig;

    /**
     * Queue configures the agent-dispatch admission queue (internal/agentqueue)
     * that a workflow implementation dispatch falls back to when the agent
     * pool is saturated, instead of erroring or wasting a worktree prep.
     */
    "queue": QueueConfig;

    /** Creates a new AgentDefaults instance. */
    constructor($$source: Partial<AgentDefaults> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("researchMachineDir" in $$source)) {
            this["researchMachineDir"] = "";
        }
        if (!("maxCostUsd" in $$source)) {
            this["maxCostUsd"] = 0;
        }
        if (!("maxTurns" in $$source)) {
            this["maxTurns"] = 0;
        }
        if (!("maxCheckpoints" in $$source)) {
            this["maxCheckpoints"] = 0;
        }
        if (!("checkpointOnTurnCeiling" in $$source)) {
            this["checkpointOnTurnCeiling"] = null;
        }
        if (!("maxTaskCostUsd" in $$source)) {
            this["maxTaskCostUsd"] = 0;
        }
        if (!("turnCostFraction" in $$source)) {
            this["turnCostFraction"] = 0;
        }
        if (!("turnMultiplier" in $$source)) {
            this["turnMultiplier"] = 0;
        }
        if (!("requirePermissions" in $$source)) {
            this["requirePermissions"] = null;
        }
        if (!("reviewUntilClean" in $$source)) {
            this["reviewUntilClean"] = null;
        }
        if (!("bashTimeoutSeconds" in $$source)) {
            this["bashTimeoutSeconds"] = 0;
        }
        if (!("retryWatchdog" in $$source)) {
            this["retryWatchdog"] = 0;
        }
        if (!("fallbackModel" in $$source)) {
            this["fallbackModel"] = "";
        }
        if (!("maxLogEvents" in $$source)) {
            this["maxLogEvents"] = 0;
        }
        if (!("logRetentionDays" in $$source)) {
            this["logRetentionDays"] = 0;
        }
        if (!("logGzipAfterDays" in $$source)) {
            this["logGzipAfterDays"] = 0;
        }
        if (!("logRetentionMaxSizeMb" in $$source)) {
            this["logRetentionMaxSizeMb"] = 0;
        }
        if (!("surviveRestart" in $$source)) {
            this["surviveRestart"] = null;
        }
        if (!("approvalPort" in $$source)) {
            this["approvalPort"] = 0;
        }
        if (!("headlessPermissionMode" in $$source)) {
            this["headlessPermissionMode"] = "";
        }
        if (!("dispatchJitterMs" in $$source)) {
            this["dispatchJitterMs"] = 0;
        }
        if (!("sandboxMode" in $$source)) {
            this["sandboxMode"] = "";
        }
        if (!("headlessSteerable" in $$source)) {
            this["headlessSteerable"] = null;
        }
        if (!("defaultProjectId" in $$source)) {
            this["defaultProjectId"] = "";
        }
        if (!("roleEffort" in $$source)) {
            this["roleEffort"] = {};
        }
        if (!("playwrightMcp" in $$source)) {
            this["playwrightMcp"] = (new PlaywrightMCPConfig());
        }
        if (!("k8sJobs" in $$source)) {
            this["k8sJobs"] = (new K8sJobsConfig());
        }
        if (!("queue" in $$source)) {
            this["queue"] = (new QueueConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentDefaults {
        const $$createField28_0 = $$createType0;
        const $$createField29_0 = $$createType1;
        const $$createField30_0 = $$createType2;
        const $$createField31_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roleEffort" in $$parsedSource) {
            $$parsedSource["roleEffort"] = $$createField28_0($$parsedSource["roleEffort"]);
        }
        if ("playwrightMcp" in $$parsedSource) {
            $$parsedSource["playwrightMcp"] = $$createField29_0($$parsedSource["playwrightMcp"]);
        }
        if ("k8sJobs" in $$parsedSource) {
            $$parsedSource["k8sJobs"] = $$createField30_0($$parsedSource["k8sJobs"]);
        }
        if ("queue" in $$parsedSource) {
            $$parsedSource["queue"] = $$createField31_0($$parsedSource["queue"]);
        }
        return new AgentDefaults($$parsedSource as Partial<AgentDefaults>);
    }
}

export class AuditConfig {
    "enabled": boolean;
    "retentionDays": number;

    /** Creates a new AuditConfig instance. */
    constructor($$source: Partial<AuditConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("retentionDays" in $$source)) {
            this["retentionDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditConfig($$parsedSource as Partial<AuditConfig>);
    }
}

/**
 * BrowserConfig controls how the desktop app opens external links (GitHub,
 * PRs, issues). Read once at startup — flipping this value requires an app
 * restart, since the opener closure is wired into the app at boot in main.go.
 */
export class BrowserConfig {
    /**
     * InApp opens links in an in-app Sybra Browser webview window backed by a
     * persistent, app-wide cookie store, so a login is reused across windows
     * and survives restarts. Nil/unset defaults to true (current behavior).
     * Set to false to always open links in the default system browser instead.
     */
    "inApp": boolean | null;

    /** Creates a new BrowserConfig instance. */
    constructor($$source: Partial<BrowserConfig> = {}) {
        if (!("inApp" in $$source)) {
            this["inApp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserConfig($$parsedSource as Partial<BrowserConfig>);
    }
}

export class ExperienceConfig {
    "enabled": boolean;
    "maxRecords": number;

    /**
     * TTLDays expires records older than this many days out of injection —
     * a stale record can otherwise poison a prompt with advice that no
     * longer matches the current codebase. 0 (default) disables expiry, so
     * existing deployments are unaffected until an operator opts in.
     */
    "ttlDays": number;

    /** Creates a new ExperienceConfig instance. */
    constructor($$source: Partial<ExperienceConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("maxRecords" in $$source)) {
            this["maxRecords"] = 0;
        }
        if (!("ttlDays" in $$source)) {
            this["ttlDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExperienceConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ExperienceConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExperienceConfig($$parsedSource as Partial<ExperienceConfig>);
    }
}

/**
 * GitHubAppConfig holds GitHub App installation-token credentials. The private
 * key never leaves disk as plaintext config — only its path is stored.
 */
export class GitHubAppConfig {
    "enabled": boolean;
    "appId": number;
    "installationId": number;
    "privateKeyPath": string;

    /** Creates a new GitHubAppConfig instance. */
    constructor($$source: Partial<GitHubAppConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("appId" in $$source)) {
            this["appId"] = 0;
        }
        if (!("installationId" in $$source)) {
            this["installationId"] = 0;
        }
        if (!("privateKeyPath" in $$source)) {
            this["privateKeyPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubAppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubAppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubAppConfig($$parsedSource as Partial<GitHubAppConfig>);
    }
}

export class GitHubConfig {
    /**
     * Enabled is the top-level kill-switch: false forces every GitHub
     * automation off regardless of the sub-toggles below. Fresh generated
     * configs set this to false so first-run GitHub polling is opt-in. Legacy
     * configs that omit this key keep the old enabled behavior during load.
     * true defers to IssuesEnabled/ReviewsEnabled.
     */
    "enabled": boolean;

    /**
     * IssuesEnabled gates the GitHub Issues fetcher specifically. Defaults to
     * true (see DefaultConfig). Effective state is Enabled && IssuesEnabled —
     * use RunsIssuesFetcher() rather than reading this field directly.
     */
    "issuesEnabled": boolean;

    /**
     * ReviewsEnabled gates PR reviewer poll registration specifically.
     * Defaults to true (see DefaultConfig). Effective state is
     * Enabled && ReviewsEnabled — use RunsReviewer() rather than reading this
     * field directly.
     */
    "reviewsEnabled": boolean;

    /**
     * PollerRole splits GitHub search polling (reviews/issues/renovate) across
     * machines sharing one token. "primary" (or empty) runs the search pollers;
     * "secondary" skips them so a sibling instance owns the searches and the
     * shared token isn't billed twice. On-demand per-PR/issue calls still run on
     * every machine — only the periodic searches are gated.
     */
    "pollerRole": string;

    /**
     * Poll-interval overrides in seconds. Zero falls back to the built-in
     * default. Raised defaults (vs. the original 1m/5m) cut steady-state request
     * volume; lower them only on a high-limit (App-token) instance.
     */
    "reviewsFastSeconds": number;

    /**
     * ReviewRoundsPerHour caps automated review runs one PR may receive in a
     * rolling hour before the task is parked for a human. 0 uses the default;
     * negative disables the cap. Rate-based rather than a lifetime total so a
     * long-lived PR that is legitimately re-reviewed after each push is never
     * blocked, while a runaway loop is stopped within the hour (#2164 sustained
     * ~5/hour for 23 hours).
     */
    "reviewRoundsPerHour": number;
    "reviewsSlowSeconds": number;

    /**
     * ReviewsMaxPRsPerTick caps how many non-active linked PRs the known-PR
     * poller fetches in one tick. Zero falls back to the built-in default;
     * resolved non-positive values mean "unlimited".
     */
    "reviewsMaxPRsPerTick": number;

    /**
     * ReviewsStableBackoffMaxTicks caps the exponential skip window for linked
     * PRs whose head SHA and updatedAt stay unchanged across polls. Zero falls
     * back to the built-in default; resolved non-positive values disable the
     * backoff entirely.
     */
    "reviewsStableBackoffMaxTicks": number;
    "issuesSeconds": number;
    "renovateFastSeconds": number;
    "renovateSlowSeconds": number;

    /**
     * App configures GitHub App installation-token auth. When enabled, Sybra
     * mints a short-lived installation token and injects it into the gh
     * subprocess (GH_TOKEN), raising the REST ceiling to 15k/hr. Unset = fall
     * back to gh's own auth.
     */
    "app": GitHubAppConfig;

    /**
     * NativeAutoMerge is a kill-switch for arming GitHub's native
     * `gh pr merge --auto` on pet-project PRs once Sybra's own review/fix
     * cycle is done and the base branch's protection supports it. It is an
     * accelerator on top of the existing green-gated MergePR path, not a
     * replacement — when unsupported or disabled the legacy merge stays the
     * fallback. Default off (zero value = false).
     */
    "nativeAutoMerge": boolean;

    /**
     * AutoResolveCleanMerges is a kill-switch for the deterministic
     * clean-merge fast-path: before dispatching a conflict-recovery agent,
     * Sybra attempts a plain `git merge` of the PR's base branch in Go. When
     * that merge creates a commit with no conflicting hunks, it is pushed and
     * no agent is spawned; conflicts, no-op merges, and errors still fall
     * through to the agent-assisted path. Default off (zero value = false).
     */
    "autoResolveCleanMerges": boolean;

    /** Creates a new GitHubConfig instance. */
    constructor($$source: Partial<GitHubConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("issuesEnabled" in $$source)) {
            this["issuesEnabled"] = false;
        }
        if (!("reviewsEnabled" in $$source)) {
            this["reviewsEnabled"] = false;
        }
        if (!("pollerRole" in $$source)) {
            this["pollerRole"] = "";
        }
        if (!("reviewsFastSeconds" in $$source)) {
            this["reviewsFastSeconds"] = 0;
        }
        if (!("reviewRoundsPerHour" in $$source)) {
            this["reviewRoundsPerHour"] = 0;
        }
        if (!("reviewsSlowSeconds" in $$source)) {
            this["reviewsSlowSeconds"] = 0;
        }
        if (!("reviewsMaxPRsPerTick" in $$source)) {
            this["reviewsMaxPRsPerTick"] = 0;
        }
        if (!("reviewsStableBackoffMaxTicks" in $$source)) {
            this["reviewsStableBackoffMaxTicks"] = 0;
        }
        if (!("issuesSeconds" in $$source)) {
            this["issuesSeconds"] = 0;
        }
        if (!("renovateFastSeconds" in $$source)) {
            this["renovateFastSeconds"] = 0;
        }
        if (!("renovateSlowSeconds" in $$source)) {
            this["renovateSlowSeconds"] = 0;
        }
        if (!("app" in $$source)) {
            this["app"] = (new GitHubAppConfig());
        }
        if (!("nativeAutoMerge" in $$source)) {
            this["nativeAutoMerge"] = false;
        }
        if (!("autoResolveCleanMerges" in $$source)) {
            this["autoResolveCleanMerges"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubConfig {
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField12_0($$parsedSource["app"]);
        }
        return new GitHubConfig($$parsedSource as Partial<GitHubConfig>);
    }
}

export class K8sJobEnvVar {
    "name": string;
    "value": string;

    /** Creates a new K8sJobEnvVar instance. */
    constructor($$source: Partial<K8sJobEnvVar> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new K8sJobEnvVar instance from a string or object.
     */
    static createFrom($$source: any = {}): K8sJobEnvVar {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new K8sJobEnvVar($$parsedSource as Partial<K8sJobEnvVar>);
    }
}

export class K8sJobSecretEnvVar {
    "name": string;
    "secretName": string;
    "secretKey": string;

    /** Creates a new K8sJobSecretEnvVar instance. */
    constructor($$source: Partial<K8sJobSecretEnvVar> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("secretName" in $$source)) {
            this["secretName"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new K8sJobSecretEnvVar instance from a string or object.
     */
    static createFrom($$source: any = {}): K8sJobSecretEnvVar {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new K8sJobSecretEnvVar($$parsedSource as Partial<K8sJobSecretEnvVar>);
    }
}

export class K8sJobVolume {
    "name": string;
    "claimName": string;
    "mountPath": string;
    "readOnly"?: boolean;

    /** Creates a new K8sJobVolume instance. */
    constructor($$source: Partial<K8sJobVolume> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("claimName" in $$source)) {
            this["claimName"] = "";
        }
        if (!("mountPath" in $$source)) {
            this["mountPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new K8sJobVolume instance from a string or object.
     */
    static createFrom($$source: any = {}): K8sJobVolume {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new K8sJobVolume($$parsedSource as Partial<K8sJobVolume>);
    }
}

/**
 * K8sJobsConfig is a PoC execution backend for headless-only Sybra. When
 * enabled, future headless agents are run as Kubernetes Jobs using the
 * in-cluster service account.
 */
export class K8sJobsConfig {
    "enabled": boolean;
    "namespace": string;
    "image": string;
    "command": string[];
    "ttlSecondsAfterFinished": number;
    "mode": string;
    "env": K8sJobEnvVar[];
    "secretEnv": K8sJobSecretEnvVar[];
    "volumes": K8sJobVolume[];

    /** Creates a new K8sJobsConfig instance. */
    constructor($$source: Partial<K8sJobsConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = [];
        }
        if (!("ttlSecondsAfterFinished" in $$source)) {
            this["ttlSecondsAfterFinished"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = [];
        }
        if (!("secretEnv" in $$source)) {
            this["secretEnv"] = [];
        }
        if (!("volumes" in $$source)) {
            this["volumes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new K8sJobsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): K8sJobsConfig {
        const $$createField3_0 = $$createType5;
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType9;
        const $$createField8_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField3_0($$parsedSource["command"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField6_0($$parsedSource["env"]);
        }
        if ("secretEnv" in $$parsedSource) {
            $$parsedSource["secretEnv"] = $$createField7_0($$parsedSource["secretEnv"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField8_0($$parsedSource["volumes"]);
        }
        return new K8sJobsConfig($$parsedSource as Partial<K8sJobsConfig>);
    }
}

/**
 * MetricsConfig controls the OpenTelemetry metrics pipeline. When Enabled is
 * true, sybra-server mounts /metrics on its existing mux and emits
 * Prometheus-format output for external scrapers.
 */
export class MetricsConfig {
    "enabled": boolean;

    /** Creates a new MetricsConfig instance. */
    constructor($$source: Partial<MetricsConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricsConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsConfig($$parsedSource as Partial<MetricsConfig>);
    }
}

/**
 * MonitorConfig controls the in-process monitor service that replaces the
 * /loop 5m /sybra-monitor skill. Each tick snapshots the board + audit
 * window, detects anomalies (lost agents, PR gaps, dwell, failure spikes,
 * bottlenecks), runs idempotent remediations directly, and dispatches a
 * focused headless agent for anomalies that need LLM judgment.
 */
export class MonitorConfig {
    "enabled": boolean;
    "intervalSeconds": number;
    "model": string;
    "issueCooldownMinutes": number;
    "dispatchLimit": number;
    "stuckHumanHours": number;
    "lostAgentMinutes": number;
    "prGapGraceMinutes": number;
    "failureRateThreshold": number;
    "bottleneckHours": { [_ in string]?: number };
    "issueLabel": string;
    "issueRepo": string;

    /** Creates a new MonitorConfig instance. */
    constructor($$source: Partial<MonitorConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("issueCooldownMinutes" in $$source)) {
            this["issueCooldownMinutes"] = 0;
        }
        if (!("dispatchLimit" in $$source)) {
            this["dispatchLimit"] = 0;
        }
        if (!("stuckHumanHours" in $$source)) {
            this["stuckHumanHours"] = 0;
        }
        if (!("lostAgentMinutes" in $$source)) {
            this["lostAgentMinutes"] = 0;
        }
        if (!("prGapGraceMinutes" in $$source)) {
            this["prGapGraceMinutes"] = 0;
        }
        if (!("failureRateThreshold" in $$source)) {
            this["failureRateThreshold"] = 0;
        }
        if (!("bottleneckHours" in $$source)) {
            this["bottleneckHours"] = {};
        }
        if (!("issueLabel" in $$source)) {
            this["issueLabel"] = "";
        }
        if (!("issueRepo" in $$source)) {
            this["issueRepo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorConfig {
        const $$createField9_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bottleneckHours" in $$parsedSource) {
            $$parsedSource["bottleneckHours"] = $$createField9_0($$parsedSource["bottleneckHours"]);
        }
        return new MonitorConfig($$parsedSource as Partial<MonitorConfig>);
    }
}

export class NotificationConfig {
    "desktop": boolean;

    /** Creates a new NotificationConfig instance. */
    constructor($$source: Partial<NotificationConfig> = {}) {
        if (!("desktop" in $$source)) {
            this["desktop"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationConfig($$parsedSource as Partial<NotificationConfig>);
    }
}

/**
 * OrchestratorConfig gates and paces the self-starting automations. Role
 * "full" runs the orchestrator brain session and the auto-dispatch scheduler,
 * preserving single-node behavior. Role "agent-only" fails closed on both: it
 * serves the HTTP API and runs explicitly-started agents but never orchestrates
 * on its own — the posture for a secondary/test deployment (a Kubernetes
 * agent-only server, a scratch instance) that must not race a full instance.
 */
export class OrchestratorConfig {
    /**
     * Role declares which self-starting automations this instance owns:
     * "full" (default) or "agent-only". An invalid value falls back to "full"
     * with a warning, so a typo never silently parks an instance that was meant
     * to orchestrate.
     */
    "role": string;

    /**
     * Enabled overrides Role for the orchestrator brain session — the
     * conversational context auto-started while tasks are active. nil (default)
     * derives from Role. Explicit true re-enables the brain on an agent-only
     * instance; explicit false parks it on a full one. Never gates an
     * operator's manual StartOrchestrator call.
     */
    "enabled": boolean | null;

    /**
     * SchedulerEnabled overrides Role for the auto-dispatch scheduler — the
     * pass that reconciles board tasks, drains the admission queue, releases
     * unblocked children, and restarts stale in-progress agents. nil (default)
     * derives from Role. Maintenance cleanup (orphan worktrees/sandboxes,
     * metrics) always runs, so a parked instance still collects its garbage.
     */
    "schedulerEnabled": boolean | null;

    /**
     * DispatchIntervalSeconds is the cadence of the cheap, latency-sensitive
     * dispatch pass (start the orchestrator, release unblocked children). Kept
     * short — and also fired on demand on every status change — so a
     * freshly-ready task is not left idle for a full tick. Default 10.
     */
    "dispatchIntervalSeconds": number;

    /**
     * MaintenanceIntervalSeconds is the cadence of the expensive recovery/cleanup
     * pass (resume stalled workflows, restart stale agents, prune orphan
     * worktrees) which hits git and may spawn agents, so it must not run hot.
     * Default 60.
     */
    "maintenanceIntervalSeconds": number;

    /**
     * AutoApprovePlansWithoutDecisions lets the workflow engine advance a
     * validated simple-task plan from plan-review to implementation when the
     * planner explicitly recorded that there are no open human decisions.
     * Default false.
     */
    "autoApprovePlansWithoutDecisions": boolean;

    /**
     * Pressure configures the local resource-pressure admission gate that
     * defers new agent dispatch while the host is short on disk, memory, or
     * CPU headroom. See internal/pressure.
     */
    "pressure": PressureConfig;

    /** Creates a new OrchestratorConfig instance. */
    constructor($$source: Partial<OrchestratorConfig> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = null;
        }
        if (!("schedulerEnabled" in $$source)) {
            this["schedulerEnabled"] = null;
        }
        if (!("dispatchIntervalSeconds" in $$source)) {
            this["dispatchIntervalSeconds"] = 0;
        }
        if (!("maintenanceIntervalSeconds" in $$source)) {
            this["maintenanceIntervalSeconds"] = 0;
        }
        if (!("autoApprovePlansWithoutDecisions" in $$source)) {
            this["autoApprovePlansWithoutDecisions"] = false;
        }
        if (!("pressure" in $$source)) {
            this["pressure"] = (new PressureConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrchestratorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): OrchestratorConfig {
        const $$createField6_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pressure" in $$parsedSource) {
            $$parsedSource["pressure"] = $$createField6_0($$parsedSource["pressure"]);
        }
        return new OrchestratorConfig($$parsedSource as Partial<OrchestratorConfig>);
    }
}

/**
 * PlaywrightMCPConfig opts test-runner runs into a headless Playwright MCP
 * server for visual/console verification. Default-off: Manager.prepareRunConfig
 * only attaches it for headless test-runner runs that resolve to the Claude
 * provider and pass a launcher preflight (see internal/agent/mcp.go).
 */
export class PlaywrightMCPConfig {
    /**
     * Enabled opts this machine into attaching the Playwright MCP server.
     */
    "enabled": boolean;

    /**
     * ExtraArgs are appended verbatim to the `npx -y @playwright/mcp@latest
     * --headless --output-dir <dir>` launch command.
     */
    "extraArgs": string[];

    /** Creates a new PlaywrightMCPConfig instance. */
    constructor($$source: Partial<PlaywrightMCPConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("extraArgs" in $$source)) {
            this["extraArgs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaywrightMCPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaywrightMCPConfig {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extraArgs" in $$parsedSource) {
            $$parsedSource["extraArgs"] = $$createField1_0($$parsedSource["extraArgs"]);
        }
        return new PlaywrightMCPConfig($$parsedSource as Partial<PlaywrightMCPConfig>);
    }
}

/**
 * PressureConfig configures internal/pressure.Gate, the local
 * resource-pressure admission gate consulted before dispatching new agent
 * work. Thresholds are captured once at Gate construction, so a change here
 * requires a restart to take effect (see diffConfig's
 * "orchestrator.pressure" restart entry).
 */
export class PressureConfig {
    /**
     * Enabled turns the gate on. Default true. When false, New returns a nil
     * *Gate and every dispatch path admits unconditionally — the same as
     * running without this feature at all.
     */
    "enabled": boolean;

    /**
     * MinDiskFreePercent is the minimum percentage of free disk space (on the
     * filesystem holding SYBRA_HOME) below which new dispatch is deferred.
     * <=0 disables this dimension. Default 5.
     */
    "minDiskFreePercent": number;

    /**
     * MinMemAvailablePercent is the minimum percentage of available memory
     * (reclaimable caches counted as available, matching the kernel's own
     * notion of headroom) below which new dispatch is deferred. <=0 disables
     * this dimension. Default 8.
     */
    "minMemAvailablePercent": number;

    /**
     * MaxLoadPerCPU is the maximum 1-minute load average, normalized by CPU
     * count, above which new dispatch is deferred. <=0 disables this
     * dimension. Default 8.0.
     */
    "maxLoadPerCpu": number;

    /**
     * SampleIntervalSeconds is both the resource-sample cache TTL and the
     * deny-log throttle window. <=0 falls back to
     * pressure.DefaultSampleIntervalSeconds (15). Default 15.
     */
    "sampleIntervalSeconds": number;

    /** Creates a new PressureConfig instance. */
    constructor($$source: Partial<PressureConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("minDiskFreePercent" in $$source)) {
            this["minDiskFreePercent"] = 0;
        }
        if (!("minMemAvailablePercent" in $$source)) {
            this["minMemAvailablePercent"] = 0;
        }
        if (!("maxLoadPerCpu" in $$source)) {
            this["maxLoadPerCpu"] = 0;
        }
        if (!("sampleIntervalSeconds" in $$source)) {
            this["sampleIntervalSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PressureConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PressureConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PressureConfig($$parsedSource as Partial<PressureConfig>);
    }
}

export class ProviderEntryConfig {
    "enabled": boolean;
    "rateLimitCooldownSeconds": number;

    /**
     * MonthlySubscriptionUSD is optional and used only for Stats value
     * comparison. Zero means "not configured".
     */
    "monthlySubscriptionUsd": number;

    /** Creates a new ProviderEntryConfig instance. */
    constructor($$source: Partial<ProviderEntryConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("rateLimitCooldownSeconds" in $$source)) {
            this["rateLimitCooldownSeconds"] = 0;
        }
        if (!("monthlySubscriptionUsd" in $$source)) {
            this["monthlySubscriptionUsd"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderEntryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderEntryConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderEntryConfig($$parsedSource as Partial<ProviderEntryConfig>);
    }
}

export class ProviderHealthCheckConfig {
    "enabled": boolean;
    "intervalSeconds": number;

    /** Creates a new ProviderHealthCheckConfig instance. */
    constructor($$source: Partial<ProviderHealthCheckConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderHealthCheckConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderHealthCheckConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderHealthCheckConfig($$parsedSource as Partial<ProviderHealthCheckConfig>);
    }
}

export class ProviderLimitsConfig {
    "enabled": boolean;
    "sessionThresholdPercent": number;
    "weeklyThresholdPercent": number;
    "preferUnderused": boolean;
    "backfillDays": number;

    /**
     * MaxInFlightPerProvider caps concurrent in-flight agents per provider,
     * distinct from the global agent.max_concurrent ceiling. 0 (default)
     * disables the cap. When set, gateProvider redirects new dispatches away
     * from an at-cap provider even when PreferUnderused is false, so the cap
     * cannot silently no-op.
     */
    "maxInFlightPerProvider": number;

    /** Creates a new ProviderLimitsConfig instance. */
    constructor($$source: Partial<ProviderLimitsConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("sessionThresholdPercent" in $$source)) {
            this["sessionThresholdPercent"] = 0;
        }
        if (!("weeklyThresholdPercent" in $$source)) {
            this["weeklyThresholdPercent"] = 0;
        }
        if (!("preferUnderused" in $$source)) {
            this["preferUnderused"] = false;
        }
        if (!("backfillDays" in $$source)) {
            this["backfillDays"] = 0;
        }
        if (!("maxInFlightPerProvider" in $$source)) {
            this["maxInFlightPerProvider"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderLimitsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderLimitsConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderLimitsConfig($$parsedSource as Partial<ProviderLimitsConfig>);
    }
}

/**
 * ProvidersConfig groups per-machine routing for CLI providers (claude, codex,
 * copilot, opencode) and their background health-check loop. A missing block defaults to
 * "all providers enabled, health check on, auto-failover on, 300s interval".
 */
export class ProvidersConfig {
    "healthCheck": ProviderHealthCheckConfig;
    "claude": ProviderEntryConfig;
    "codex": ProviderEntryConfig;
    "copilot": ProviderEntryConfig;
    "opencode": ProviderEntryConfig;
    "limits": ProviderLimitsConfig;
    "autoFailover": boolean;

    /** Creates a new ProvidersConfig instance. */
    constructor($$source: Partial<ProvidersConfig> = {}) {
        if (!("healthCheck" in $$source)) {
            this["healthCheck"] = (new ProviderHealthCheckConfig());
        }
        if (!("claude" in $$source)) {
            this["claude"] = (new ProviderEntryConfig());
        }
        if (!("codex" in $$source)) {
            this["codex"] = (new ProviderEntryConfig());
        }
        if (!("copilot" in $$source)) {
            this["copilot"] = (new ProviderEntryConfig());
        }
        if (!("opencode" in $$source)) {
            this["opencode"] = (new ProviderEntryConfig());
        }
        if (!("limits" in $$source)) {
            this["limits"] = (new ProviderLimitsConfig());
        }
        if (!("autoFailover" in $$source)) {
            this["autoFailover"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProvidersConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProvidersConfig {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType15;
        const $$createField4_0 = $$createType15;
        const $$createField5_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("healthCheck" in $$parsedSource) {
            $$parsedSource["healthCheck"] = $$createField0_0($$parsedSource["healthCheck"]);
        }
        if ("claude" in $$parsedSource) {
            $$parsedSource["claude"] = $$createField1_0($$parsedSource["claude"]);
        }
        if ("codex" in $$parsedSource) {
            $$parsedSource["codex"] = $$createField2_0($$parsedSource["codex"]);
        }
        if ("copilot" in $$parsedSource) {
            $$parsedSource["copilot"] = $$createField3_0($$parsedSource["copilot"]);
        }
        if ("opencode" in $$parsedSource) {
            $$parsedSource["opencode"] = $$createField4_0($$parsedSource["opencode"]);
        }
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField5_0($$parsedSource["limits"]);
        }
        return new ProvidersConfig($$parsedSource as Partial<ProvidersConfig>);
    }
}

/**
 * QueueConfig configures the agent-dispatch admission queue.
 */
export class QueueConfig {
    /**
     * MaxDepth caps the number of distinct tasks the admission queue holds at
     * once (agentqueue.Options.MaxDepth). 0 means unbounded. Once full, a new
     * task that can't get a pool slot is rejected with a normal dispatch
     * error instead of being queued.
     */
    "maxDepth": number;

    /** Creates a new QueueConfig instance. */
    constructor($$source: Partial<QueueConfig> = {}) {
        if (!("maxDepth" in $$source)) {
            this["maxDepth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueConfig($$parsedSource as Partial<QueueConfig>);
    }
}

export class RenovateConfig {
    "enabled": boolean;
    "author": string;

    /** Creates a new RenovateConfig instance. */
    constructor($$source: Partial<RenovateConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenovateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RenovateConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenovateConfig($$parsedSource as Partial<RenovateConfig>);
    }
}

/**
 * SelfMonitorConfig controls the in-process selfmonitor service that
 * replaces the /loop 6h /sybra-self-monitor skill. Each tick snapshots
 * the latest health report, distills per-finding agent logs into a
 * LogSummary, runs a two-stage LLM judge + synthesizer (Phase C), files
 * deduped issues via the shared monitor.IssueSink, and autonomously
 * remediates a whitelisted set of categories (Phase D). Enabled stays
 * false until users opt in.
 */
export class SelfMonitorConfig {
    "enabled": boolean;
    "intervalHours": number;
    "judgeModel": string;
    "synthesizerModel": string;
    "maxIssuesPerRun": number;
    "maxAutoActionsPerDay": number;
    "autoActCategories": string[];
    "dryRun": boolean;
    "issueCooldownHours": number;
    "issueLabel": string;
    "maxCostPerTickUsd": number;
    "judgeParallelism": number;
    "suppressionDays": number;
    "suppressionThreshold": number;

    /** Creates a new SelfMonitorConfig instance. */
    constructor($$source: Partial<SelfMonitorConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("intervalHours" in $$source)) {
            this["intervalHours"] = 0;
        }
        if (!("judgeModel" in $$source)) {
            this["judgeModel"] = "";
        }
        if (!("synthesizerModel" in $$source)) {
            this["synthesizerModel"] = "";
        }
        if (!("maxIssuesPerRun" in $$source)) {
            this["maxIssuesPerRun"] = 0;
        }
        if (!("maxAutoActionsPerDay" in $$source)) {
            this["maxAutoActionsPerDay"] = 0;
        }
        if (!("autoActCategories" in $$source)) {
            this["autoActCategories"] = [];
        }
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }
        if (!("issueCooldownHours" in $$source)) {
            this["issueCooldownHours"] = 0;
        }
        if (!("issueLabel" in $$source)) {
            this["issueLabel"] = "";
        }
        if (!("maxCostPerTickUsd" in $$source)) {
            this["maxCostPerTickUsd"] = 0;
        }
        if (!("judgeParallelism" in $$source)) {
            this["judgeParallelism"] = 0;
        }
        if (!("suppressionDays" in $$source)) {
            this["suppressionDays"] = 0;
        }
        if (!("suppressionThreshold" in $$source)) {
            this["suppressionThreshold"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelfMonitorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SelfMonitorConfig {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("autoActCategories" in $$parsedSource) {
            $$parsedSource["autoActCategories"] = $$createField6_0($$parsedSource["autoActCategories"]);
        }
        return new SelfMonitorConfig($$parsedSource as Partial<SelfMonitorConfig>);
    }
}

/**
 * TestingConfig controls the autonomous manual-testing phase. A task entering
 * status=testing spawns a single adversarial test-runner agent that starts the
 * real app/cluster in an isolated per-task sandbox and tries to prove the
 * implementation does not satisfy the task. Each test-runner holds its own
 * sandbox (Docker compose project / k3d cluster), so MaxConcurrent bounds
 * real-app/cluster load independently of Agent.MaxConcurrent.
 */
export class TestingConfig {
    /**
     * MaxConcurrent caps simultaneously-running test-runner agents on this
     * machine. 0 falls back to DefaultTestingMaxConcurrent.
     */
    "maxConcurrent": number;

    /**
     * MaxAttempts is the generous absolute backstop for the testing →
     * re-implementation loop. Recurring grounded failure fingerprints escalate
     * independently of this count; this limit only parks a task human-required
     * when distinct grounded defects keep surfacing without convergence. 0
     * falls back to DefaultTestingMaxAttempts.
     */
    "maxAttempts": number;

    /**
     * OpenPROnUnrunnableGate controls what happens when a testing cycle
     * exhausts its auto-retry budget on an infra_failure outcome — the manual
     * gate itself could not be run (harness/tooling limitation), not a
     * product defect (see classifyTestOutcome). nil means not configured
     * (defaults to true): the task opens a PR (ready-pr) so CI and a human
     * reviewer see the real diff, instead of parking at human-required with
     * no PR for anyone to act on. Set false to restore the legacy
     * human-required escalation.
     */
    "openPrOnUnrunnableGate": boolean | null;

    /** Creates a new TestingConfig instance. */
    constructor($$source: Partial<TestingConfig> = {}) {
        if (!("maxConcurrent" in $$source)) {
            this["maxConcurrent"] = 0;
        }
        if (!("maxAttempts" in $$source)) {
            this["maxAttempts"] = 0;
        }
        if (!("openPrOnUnrunnableGate" in $$source)) {
            this["openPrOnUnrunnableGate"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestingConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TestingConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestingConfig($$parsedSource as Partial<TestingConfig>);
    }
}

export class TodoistConfig {
    "enabled": boolean;
    "apiToken": string;
    "projectId": string;
    "defaultProjectId": string;
    "pollSeconds": number;

    /** Creates a new TodoistConfig instance. */
    constructor($$source: Partial<TodoistConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("apiToken" in $$source)) {
            this["apiToken"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("defaultProjectId" in $$source)) {
            this["defaultProjectId"] = "";
        }
        if (!("pollSeconds" in $$source)) {
            this["pollSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoistConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoistConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoistConfig($$parsedSource as Partial<TodoistConfig>);
    }
}

/**
 * TriageConfig controls the background auto-triage worker. When Enabled,
 * sybra periodically classifies tasks in status=new via claude -p and
 * atomically applies the verdict (title, tags, size/type, mode, project).
 */
export class TriageConfig {
    "enabled": boolean;
    "pollSeconds": number;
    "model": string;

    /** Creates a new TriageConfig instance. */
    constructor($$source: Partial<TriageConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("pollSeconds" in $$source)) {
            this["pollSeconds"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TriageConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TriageConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TriageConfig($$parsedSource as Partial<TriageConfig>);
    }
}

/**
 * UmbrellaConfig governs auto-expansion of ☂️ umbrella issues by the GitHub
 * issue fetcher. Disabled by default; project-scoped via the top-level
 * project_types allowlist so only one machine expands a given umbrella.
 */
export class UmbrellaConfig {
    "enabled": boolean;

    /**
     * Model overrides the planner model (empty = claude default).
     */
    "model": string;

    /**
     * Ground gates the optional grounding step that confirms each
     * sub-issue's touches against the real repo's tracked files. Disabled
     * by default (extra git/tool calls); additive on top of planner output.
     */
    "ground": boolean;

    /**
     * GroundMinSubIssues gates grounding on umbrella size: grounding only
     * runs when the umbrella has at least this many sub-issues. Zero or
     * negative means always ground when Ground is enabled.
     */
    "groundMinSubIssues": number;

    /** Creates a new UmbrellaConfig instance. */
    constructor($$source: Partial<UmbrellaConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("ground" in $$source)) {
            this["ground"] = false;
        }
        if (!("groundMinSubIssues" in $$source)) {
            this["groundMinSubIssues"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UmbrellaConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UmbrellaConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UmbrellaConfig($$parsedSource as Partial<UmbrellaConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = PlaywrightMCPConfig.createFrom;
const $$createType2 = K8sJobsConfig.createFrom;
const $$createType3 = QueueConfig.createFrom;
const $$createType4 = GitHubAppConfig.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = K8sJobEnvVar.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = K8sJobSecretEnvVar.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = K8sJobVolume.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
const $$createType13 = PressureConfig.createFrom;
const $$createType14 = ProviderHealthCheckConfig.createFrom;
const $$createType15 = ProviderEntryConfig.createFrom;
const $$createType16 = ProviderLimitsConfig.createFrom;
