// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as health$0 from "../health/models.js";

/**
 * ActionRecord describes an autonomous action the actor took (or would have
 * taken, when DryRun is true) in response to a confirmed finding.
 */
export class ActionRecord {
    "category": string;
    "fingerprint": string;
    "kind": string;
    "reference"?: string;
    "dryRun": boolean;
    "takenAt": string;
    "error"?: string;

    /** Creates a new ActionRecord instance. */
    constructor($$source: Partial<ActionRecord> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }
        if (!("takenAt" in $$source)) {
            this["takenAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionRecord($$parsedSource as Partial<ActionRecord>);
    }
}

/**
 * Correlation is a cross-finding join discovered by the pure-Go correlator.
 * Examples: all failures on the same project sharing a permission_denied
 * error class; cascades where one failed impl triggered a stuck task.
 */
export class Correlation {
    "kind": string;
    "key": string;
    "count": number;
    "fingerprints"?: string[];
    "description"?: string;

    /** Creates a new Correlation instance. */
    constructor($$source: Partial<Correlation> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Correlation instance from a string or object.
     */
    static createFrom($$source: any = {}): Correlation {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fingerprints" in $$parsedSource) {
            $$parsedSource["fingerprints"] = $$createField3_0($$parsedSource["fingerprints"]);
        }
        return new Correlation($$parsedSource as Partial<Correlation>);
    }
}

/**
 * ErrorClass aggregates tool_result / result-event errors by a coarse
 * category (rate_limit, permission_denied, ...). These classifiers deliberately
 * stay local instead of using internal/errclass: they label structured telemetry
 * for reports and correlation, including classes such as not_found and
 * permission_denied, but never choose a runtime retry, cooldown, or park action.
 */
export class ErrorClass {
    "class": string;
    "count": number;
    "sample"?: string;

    /** Creates a new ErrorClass instance. */
    constructor($$source: Partial<ErrorClass> = {}) {
        if (!("class" in $$source)) {
            this["class"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorClass instance from a string or object.
     */
    static createFrom($$source: any = {}): ErrorClass {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorClass($$parsedSource as Partial<ErrorClass>);
    }
}

/**
 * InvestigatedFinding is a single health.Finding after the selfmonitor
 * pipeline has distilled its log, run the judge, and optionally correlated
 * it with others. LogSummary is nil for board-wide findings that have no
 * associated agent log.
 */
export class InvestigatedFinding {
    "finding": health$0.Finding;
    "fingerprint": string;
    "logSummary"?: LogSummary | null;
    "verdict": Verdict;
    "issueNumber"?: number;

    /** Creates a new InvestigatedFinding instance. */
    constructor($$source: Partial<InvestigatedFinding> = {}) {
        if (!("finding" in $$source)) {
            this["finding"] = (new health$0.Finding());
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = (new Verdict());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvestigatedFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): InvestigatedFinding {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("finding" in $$parsedSource) {
            $$parsedSource["finding"] = $$createField0_0($$parsedSource["finding"]);
        }
        if ("logSummary" in $$parsedSource) {
            $$parsedSource["logSummary"] = $$createField2_0($$parsedSource["logSummary"]);
        }
        if ("verdict" in $$parsedSource) {
            $$parsedSource["verdict"] = $$createField3_0($$parsedSource["verdict"]);
        }
        return new InvestigatedFinding($$parsedSource as Partial<InvestigatedFinding>);
    }
}

/**
 * LedgerEntry is one appended row in the selfmonitor ledger. The ledger is
 * the persisted, cross-restart memory of the selfmonitor loop: what
 * fingerprints it has seen, what verdicts the judge handed down, what
 * autonomous actions it took, and whether filed issues have been resolved.
 * 
 * Schema is append-only; add new fields with omitempty so existing rows keep
 * round-tripping. Never rename or remove fields.
 */
export class LedgerEntry {
    "fingerprint": string;
    "category"?: string;
    "taskId"?: string;
    "verdict": string;
    "issueNumber"?: number;
    "issueState"?: string;
    "action"?: string;
    "actionRef"?: string;
    "dryRun"?: boolean;
    "confidence"?: number;
    "summary"?: string;
    "createdAt": string;
    "resolvedAt"?: string;

    /** Creates a new LedgerEntry instance. */
    constructor($$source: Partial<LedgerEntry> = {}) {
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LedgerEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LedgerEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LedgerEntry($$parsedSource as Partial<LedgerEntry>);
    }
}

/**
 * LogSummary is the distilled, structured projection of an agent NDJSON log
 * that downstream consumers (the two-stage LLM judge, the GUI, correlators)
 * read instead of the raw file. Produced by Analyze.
 */
export class LogSummary {
    "schemaVersion": number;
    "path"?: string;
    "totalEvents": number;
    "totalToolCalls": number;
    "totalCostUsd": number;
    "totalInputTokens": number;
    "totalOutputTokens": number;
    "toolHistogram": { [_ in string]?: number };
    "repeatedCalls"?: RepeatedCall[];
    "inferredCostPerTool": { [_ in string]?: number };
    "errorClasses"?: ErrorClass[];
    "lastToolCalls"?: ToolCallTrace[];
    "stallDetected": boolean;
    "stallReason"?: string;
    "finalError"?: string;

    /**
     * SkippedOversizedRecords counts NDJSON lines over maxLogLineBytes that
     * were skipped whole rather than parsed. A run that produced one huge
     * tool result still yields a summary of every other event instead of
     * aborting the whole analysis.
     */
    "skippedOversizedRecords"?: number;

    /** Creates a new LogSummary instance. */
    constructor($$source: Partial<LogSummary> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("totalEvents" in $$source)) {
            this["totalEvents"] = 0;
        }
        if (!("totalToolCalls" in $$source)) {
            this["totalToolCalls"] = 0;
        }
        if (!("totalCostUsd" in $$source)) {
            this["totalCostUsd"] = 0;
        }
        if (!("totalInputTokens" in $$source)) {
            this["totalInputTokens"] = 0;
        }
        if (!("totalOutputTokens" in $$source)) {
            this["totalOutputTokens"] = 0;
        }
        if (!("toolHistogram" in $$source)) {
            this["toolHistogram"] = {};
        }
        if (!("inferredCostPerTool" in $$source)) {
            this["inferredCostPerTool"] = {};
        }
        if (!("stallDetected" in $$source)) {
            this["stallDetected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): LogSummary {
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType8;
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolHistogram" in $$parsedSource) {
            $$parsedSource["toolHistogram"] = $$createField7_0($$parsedSource["toolHistogram"]);
        }
        if ("repeatedCalls" in $$parsedSource) {
            $$parsedSource["repeatedCalls"] = $$createField8_0($$parsedSource["repeatedCalls"]);
        }
        if ("inferredCostPerTool" in $$parsedSource) {
            $$parsedSource["inferredCostPerTool"] = $$createField9_0($$parsedSource["inferredCostPerTool"]);
        }
        if ("errorClasses" in $$parsedSource) {
            $$parsedSource["errorClasses"] = $$createField10_0($$parsedSource["errorClasses"]);
        }
        if ("lastToolCalls" in $$parsedSource) {
            $$parsedSource["lastToolCalls"] = $$createField11_0($$parsedSource["lastToolCalls"]);
        }
        return new LogSummary($$parsedSource as Partial<LogSummary>);
    }
}

/**
 * PipelineState is a coarse, point-in-time verdict for one tick/run of the
 * autonomy feedback pipeline. harnessevolution reuses this type (rather than
 * defining its own) for its own RunResult so every consumer of either report
 * shares one vocabulary for "is this data trustworthy":
 * 
 *   - StateHealthy: ticked/ran normally and produced usable data.
 *   - StateDisabled: the pipeline stage is turned off in config.
 *   - StateStale: the report exists but is older than a caller-defined
 *     freshness window, or was never produced at all (infinitely stale).
 *   - StatePartial: it ticked, but part of the input couldn't be analyzed
 *     (an oversized log record, an unreadable log file, ...).
 *   - StateFailed: the tick/run itself errored before completing.
 */
export enum PipelineState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateHealthy = "healthy",
    StateDisabled = "disabled",
    StateStale = "stale",
    StatePartial = "partial",
    StateFailed = "failed",
};

/**
 * RepeatedCall reports a tool invocation that fired ≥ RepeatedCallThreshold
 * times with structurally identical Input — the classic tool-loop signature.
 */
export class RepeatedCall {
    "tool": string;
    "count": number;
    "inputHash": string;
    "sampleInput"?: { [_ in string]?: any };

    /** Creates a new RepeatedCall instance. */
    constructor($$source: Partial<RepeatedCall> = {}) {
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("inputHash" in $$source)) {
            this["inputHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepeatedCall instance from a string or object.
     */
    static createFrom($$source: any = {}): RepeatedCall {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sampleInput" in $$parsedSource) {
            $$parsedSource["sampleInput"] = $$createField3_0($$parsedSource["sampleInput"]);
        }
        return new RepeatedCall($$parsedSource as Partial<RepeatedCall>);
    }
}

/**
 * Report is the full payload emitted at the end of each selfmonitor tick.
 * It's also what `sybra-cli selfmonitor scan` prints and what the Wails
 * `selfmonitor:report` event carries to the frontend. All fields use
 * omitempty where appropriate so empty-run reports stay compact.
 */
export class Report {
    "schemaVersion": number;
    "generatedAt": string;
    "periodStart": string;
    "periodEnd": string;
    "healthScore"?: health$0.Score;
    "findings": InvestigatedFinding[];
    "correlations"?: Correlation[];
    "issuesCreated"?: number[];
    "issuesCommented"?: number[];
    "actionsTaken"?: ActionRecord[];
    "suppressed": number;
    "falsePositives": number;
    "needsHuman": number;
    "costUsd": number;
    "durationMs": number;

    /**
     * State, FailureReason, and the coverage counters below give downstream
     * consumers (harnessevolution, the GUI) an explicit signal instead of
     * having to infer freshness/completeness from the shape of Findings.
     */
    "state": PipelineState;
    "failureReason"?: string;
    "inputsTotal": number;
    "inputsAnalyzed": number;
    "truncatedRecords"?: number;
    "analysisErrors"?: number;

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("periodStart" in $$source)) {
            this["periodStart"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("periodEnd" in $$source)) {
            this["periodEnd"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }
        if (!("suppressed" in $$source)) {
            this["suppressed"] = 0;
        }
        if (!("falsePositives" in $$source)) {
            this["falsePositives"] = 0;
        }
        if (!("needsHuman" in $$source)) {
            this["needsHuman"] = 0;
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = PipelineState.$zero;
        }
        if (!("inputsTotal" in $$source)) {
            this["inputsTotal"] = 0;
        }
        if (!("inputsAnalyzed" in $$source)) {
            this["inputsAnalyzed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType17;
        const $$createField7_0 = $$createType18;
        const $$createField8_0 = $$createType18;
        const $$createField9_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField5_0($$parsedSource["findings"]);
        }
        if ("correlations" in $$parsedSource) {
            $$parsedSource["correlations"] = $$createField6_0($$parsedSource["correlations"]);
        }
        if ("issuesCreated" in $$parsedSource) {
            $$parsedSource["issuesCreated"] = $$createField7_0($$parsedSource["issuesCreated"]);
        }
        if ("issuesCommented" in $$parsedSource) {
            $$parsedSource["issuesCommented"] = $$createField8_0($$parsedSource["issuesCommented"]);
        }
        if ("actionsTaken" in $$parsedSource) {
            $$parsedSource["actionsTaken"] = $$createField9_0($$parsedSource["actionsTaken"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

/**
 * ToolCallTrace is a trailing tool call recorded verbatim so the judge LLM
 * can see the tail of the run without reading the raw log.
 */
export class ToolCallTrace {
    "tool": string;
    "input"?: { [_ in string]?: any };
    "resultExcerpt"?: string;
    "isError"?: boolean;

    /** Creates a new ToolCallTrace instance. */
    constructor($$source: Partial<ToolCallTrace> = {}) {
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallTrace {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField1_0($$parsedSource["input"]);
        }
        return new ToolCallTrace($$parsedSource as Partial<ToolCallTrace>);
    }
}

/**
 * Verdict is the structured judgment produced by the stage-1 judge LLM for a
 * single finding. The synthesizer reads verdicts and the actor reads
 * verdicts + categories to decide whether to act.
 */
export class Verdict {
    "classification": string;
    "rootCause"?: string;
    "evidenceExcerpt"?: string;
    "confidence"?: number;
    "nextAction"?: string;

    /** Creates a new Verdict instance. */
    constructor($$source: Partial<Verdict> = {}) {
        if (!("classification" in $$source)) {
            this["classification"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verdict instance from a string or object.
     */
    static createFrom($$source: any = {}): Verdict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Verdict($$parsedSource as Partial<Verdict>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = health$0.Finding.createFrom;
const $$createType2 = LogSummary.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Verdict.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = RepeatedCall.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = ErrorClass.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ToolCallTrace.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = InvestigatedFinding.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = Correlation.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = ActionRecord.createFrom;
const $$createType20 = $Create.Array($$createType19);
