// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindTargets() {
  return window['go']['sybra']['App']['BindTargets']();
}

export function Context() {
  return window['go']['sybra']['App']['Context']();
}

export function GetMonitorReport() {
  return window['go']['sybra']['App']['GetMonitorReport']();
}

export function ListBackgroundOps() {
  return window['go']['sybra']['App']['ListBackgroundOps']();
}

export function ListNotifications() {
  return window['go']['sybra']['App']['ListNotifications']();
}

export function RegisterSpotlightHotkey() {
  return window['go']['sybra']['App']['RegisterSpotlightHotkey']();
}

export function ServiceRegistry() {
  return window['go']['sybra']['App']['ServiceRegistry']();
}

export function SetDesktopNotifications(arg1) {
  return window['go']['sybra']['App']['SetDesktopNotifications'](arg1);
}

export function StartAgent(arg1, arg2, arg3) {
  return window['go']['sybra']['App']['StartAgent'](arg1, arg2, arg3);
}

export function StartChat(arg1, arg2, arg3) {
  return window['go']['sybra']['App']['StartChat'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['sybra']['App']['Startup'](arg1);
}

export function StopChat(arg1) {
  return window['go']['sybra']['App']['StopChat'](arg1);
}
