// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sybra} from '../models';

export function GetSettings():Promise<sybra.AppSettings>;

export function ReloadFromDisk():Promise<Array<string>>;

export function UpdateSettings(arg1:sybra.AppSettings):Promise<void>;
