// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sybra} from '../models';

export function GetVersion():Promise<sybra.VersionInfo>;
