// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePlan(arg1) {
  return window['go']['sybra']['PlanningService']['ApprovePlan'](arg1);
}

export function ApproveTestPlan(arg1) {
  return window['go']['sybra']['PlanningService']['ApproveTestPlan'](arg1);
}

export function HasLivePlanAgent(arg1) {
  return window['go']['sybra']['PlanningService']['HasLivePlanAgent'](arg1);
}

export function HasLiveTestPlanAgent(arg1) {
  return window['go']['sybra']['PlanningService']['HasLiveTestPlanAgent'](arg1);
}

export function PlanTask(arg1) {
  return window['go']['sybra']['PlanningService']['PlanTask'](arg1);
}

export function RejectPlan(arg1, arg2) {
  return window['go']['sybra']['PlanningService']['RejectPlan'](arg1, arg2);
}

export function RejectTestPlan(arg1, arg2) {
  return window['go']['sybra']['PlanningService']['RejectTestPlan'](arg1, arg2);
}

export function SendPlanMessage(arg1, arg2) {
  return window['go']['sybra']['PlanningService']['SendPlanMessage'](arg1, arg2);
}

export function SendTestPlanMessage(arg1, arg2) {
  return window['go']['sybra']['PlanningService']['SendTestPlanMessage'](arg1, arg2);
}

export function TriageTask(arg1) {
  return window['go']['sybra']['PlanningService']['TriageTask'](arg1);
}
