// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['sybra']['TaskService']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['sybra']['TaskService']['DeleteTask'](arg1);
}

export function GetTask(arg1) {
  return window['go']['sybra']['TaskService']['GetTask'](arg1);
}

export function ListTasks() {
  return window['go']['sybra']['TaskService']['ListTasks']();
}

export function UpdateTask(arg1, arg2) {
  return window['go']['sybra']['TaskService']['UpdateTask'](arg1, arg2);
}
