// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CheckRunInfo represents a single CI check run.
 */
export class CheckRunInfo {
    "name": string;

    /**
     * COMPLETED, IN_PROGRESS, QUEUED
     */
    "status": string;

    /**
     * SUCCESS, FAILURE, NEUTRAL, CANCELLED, TIMED_OUT
     */
    "conclusion": string;

    /** Creates a new CheckRunInfo instance. */
    constructor($$source: Partial<CheckRunInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("conclusion" in $$source)) {
            this["conclusion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckRunInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckRunInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckRunInfo($$parsedSource as Partial<CheckRunInfo>);
    }
}

/**
 * Issue represents a GitHub issue for display.
 */
export class Issue {
    "number": number;
    "title": string;
    "body": string;
    "url": string;
    "repository": string;
    "repoName": string;
    "labels": string[];
    "author": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Issue instance. */
    constructor($$source: Partial<Issue> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("repoName" in $$source)) {
            this["repoName"] = "";
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     */
    static createFrom($$source: any = {}): Issue {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField6_0($$parsedSource["labels"]);
        }
        return new Issue($$parsedSource as Partial<Issue>);
    }
}

/**
 * PullRequest represents a GitHub pull request for display.
 */
export class PullRequest {
    "number": number;
    "title": string;
    "url": string;
    "repository": string;
    "repoName": string;
    "author": string;
    "isDraft": boolean;
    "labels": string[];
    "headRefName": string;
    "headSha": string;

    /**
     * SUCCESS, FAILURE, PENDING, or ""
     */
    "ciStatus": string;

    /**
     * true when any check is still in-progress/queued
     */
    "hasPendingChecks": boolean;

    /**
     * APPROVED, CHANGES_REQUESTED, REVIEW_REQUIRED, or ""
     */
    "reviewDecision": string;

    /**
     * MERGEABLE, CONFLICTING, UNKNOWN, or ""
     */
    "mergeable": string;
    "unresolvedCount": number;
    "viewerHasApproved": boolean;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new PullRequest instance. */
    constructor($$source: Partial<PullRequest> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("repoName" in $$source)) {
            this["repoName"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("isDraft" in $$source)) {
            this["isDraft"] = false;
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("headRefName" in $$source)) {
            this["headRefName"] = "";
        }
        if (!("headSha" in $$source)) {
            this["headSha"] = "";
        }
        if (!("ciStatus" in $$source)) {
            this["ciStatus"] = "";
        }
        if (!("hasPendingChecks" in $$source)) {
            this["hasPendingChecks"] = false;
        }
        if (!("reviewDecision" in $$source)) {
            this["reviewDecision"] = "";
        }
        if (!("mergeable" in $$source)) {
            this["mergeable"] = "";
        }
        if (!("unresolvedCount" in $$source)) {
            this["unresolvedCount"] = 0;
        }
        if (!("viewerHasApproved" in $$source)) {
            this["viewerHasApproved"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PullRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PullRequest {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField7_0($$parsedSource["labels"]);
        }
        return new PullRequest($$parsedSource as Partial<PullRequest>);
    }
}

/**
 * RenovatePR extends PullRequest with individual check run details.
 */
export class RenovatePR {
    "number": number;
    "title": string;
    "url": string;
    "repository": string;
    "repoName": string;
    "author": string;
    "isDraft": boolean;
    "labels": string[];
    "headRefName": string;
    "headSha": string;

    /**
     * SUCCESS, FAILURE, PENDING, or ""
     */
    "ciStatus": string;

    /**
     * true when any check is still in-progress/queued
     */
    "hasPendingChecks": boolean;

    /**
     * APPROVED, CHANGES_REQUESTED, REVIEW_REQUIRED, or ""
     */
    "reviewDecision": string;

    /**
     * MERGEABLE, CONFLICTING, UNKNOWN, or ""
     */
    "mergeable": string;
    "unresolvedCount": number;
    "viewerHasApproved": boolean;
    "createdAt": string;
    "updatedAt": string;
    "checkRuns": CheckRunInfo[];

    /** Creates a new RenovatePR instance. */
    constructor($$source: Partial<RenovatePR> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("repoName" in $$source)) {
            this["repoName"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("isDraft" in $$source)) {
            this["isDraft"] = false;
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("headRefName" in $$source)) {
            this["headRefName"] = "";
        }
        if (!("headSha" in $$source)) {
            this["headSha"] = "";
        }
        if (!("ciStatus" in $$source)) {
            this["ciStatus"] = "";
        }
        if (!("hasPendingChecks" in $$source)) {
            this["hasPendingChecks"] = false;
        }
        if (!("reviewDecision" in $$source)) {
            this["reviewDecision"] = "";
        }
        if (!("mergeable" in $$source)) {
            this["mergeable"] = "";
        }
        if (!("unresolvedCount" in $$source)) {
            this["unresolvedCount"] = 0;
        }
        if (!("viewerHasApproved" in $$source)) {
            this["viewerHasApproved"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("checkRuns" in $$source)) {
            this["checkRuns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenovatePR instance from a string or object.
     */
    static createFrom($$source: any = {}): RenovatePR {
        const $$createField7_0 = $$createType0;
        const $$createField18_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField7_0($$parsedSource["labels"]);
        }
        if ("checkRuns" in $$parsedSource) {
            $$parsedSource["checkRuns"] = $$createField18_0($$parsedSource["checkRuns"]);
        }
        return new RenovatePR($$parsedSource as Partial<RenovatePR>);
    }
}

/**
 * ReviewSummary contains PRs grouped by relationship to the user.
 */
export class ReviewSummary {
    "createdByMe": PullRequest[];
    "reviewRequested": PullRequest[];

    /** Creates a new ReviewSummary instance. */
    constructor($$source: Partial<ReviewSummary> = {}) {
        if (!("createdByMe" in $$source)) {
            this["createdByMe"] = [];
        }
        if (!("reviewRequested" in $$source)) {
            this["reviewRequested"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewSummary {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("createdByMe" in $$parsedSource) {
            $$parsedSource["createdByMe"] = $$createField0_0($$parsedSource["createdByMe"]);
        }
        if ("reviewRequested" in $$parsedSource) {
            $$parsedSource["reviewRequested"] = $$createField1_0($$parsedSource["reviewRequested"]);
        }
        return new ReviewSummary($$parsedSource as Partial<ReviewSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CheckRunInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PullRequest.createFrom;
const $$createType4 = $Create.Array($$createType3);
