// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Subject identifies the workflow target for prompt and skill experiments.
 */
export class Subject {
    "workflowId"?: string;
    "stepId"?: string;
    "role"?: string;
    "skillName"?: string;

    /** Creates a new Subject instance. */
    constructor($$source: Partial<Subject> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subject instance from a string or object.
     */
    static createFrom($$source: any = {}): Subject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subject($$parsedSource as Partial<Subject>);
    }
}
