// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attachment$0 from "../attachment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as blocker$0 from "../blocker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflow$0 from "../workflow/models.js";

/**
 * AgentRun records one dispatch of an agent process against a task: what was
 * asked, which provider/model ran it, how it concluded, and the metadata
 * downstream deterministic routing (test outcome, tamper detection, A/B
 * evaluation) reads back off the run. A Task accumulates these in
 * Task.AgentRuns across its lifetime, most-recent last.
 */
export class AgentRun {
    "agentId": string;

    /**
     * explicit run role; legacy empty still means implementation
     */
    "role": string;
    "mode": string;
    "provider"?: string;
    "model"?: string;

    /**
     * ExperimentID/VariantID capture deterministic A/B assignment selected
     * before the run started.
     */
    "experimentId"?: string;
    "variantId"?: string;
    "routingReason"?: string;
    "assignmentUnit"?: string;
    "assignmentKey"?: string;
    "decisionVersion"?: number;
    "reasoningEffort"?: string;
    "requestedSkill"?: string;

    /**
     * SkillExecutionMode records how a mandatory workflow skill actually ran:
     * none, native invocation, injected SKILL.md, bundled fallback, or
     * unavailable. Legacy empty values remain readable and normalize to
     * unknown at query time.
     */
    "skillExecutionMode"?: string;

    /**
     * ResolvedSkillSourceHash is a privacy-safe hash of the resolved local or
     * bundled skill source identifier. Empty when the skill ran natively or no
     * source was resolved.
     */
    "resolvedSkillSourceHash"?: string;

    /**
     * SkillConformance records whether the executed skill path exactly matched
     * the requested skill, fell back, was unavailable, or had no skill at all.
     */
    "skillConformance"?: string;
    "state": string;

    /**
     * Outcome records the terminal result the completion handler actually
     * observed (RunOutcomeSuccess/RunOutcomeFailure), independent of State
     * ("stopped" covers both a clean finish and a failed one) and independent
     * of Result (truncated to maxResultLen, so its presence/absence cannot
     * tell success from failure either). Empty means the run never reached a
     * definitive terminal outcome (still running, or stalled/rate-limited and
     * due for retry) — callers must not infer success from Outcome == "".
     */
    "outcome"?: string;

    /**
     * EscalationReason records the guardrail reason that stopped the run
     * ("cost" or "turns"). Empty for ordinary completions.
     */
    "escalationReason"?: string;
    "startedAt": string;
    "costUsd": number;
    "premiumRequests"?: number;
    "prompt"?: string;
    "result": string;
    "oneShot"?: boolean;

    /**
     * Verdict holds the parsed decision for human-review runs ("human" or
     * "sybra_bug"). Extracted from live agent output at completion time so
     * it survives Result truncation.
     */
    "verdict"?: string;

    /**
     * VerdictRendered is set to true after onComplete has successfully applied
     * all side-effects for this run (note appended, issue filed, local task
     * created). Used by verdictAlreadyRendered as the durable rendered-marker
     * instead of body-text patterns which can collide with user content.
     */
    "verdictRendered"?: boolean;
    "logFile": string;
    "sessionId"?: string;

    /**
     * ProtocolViolation records deterministic workflow-level contract failures
     * for this run. Test routing uses it to avoid counting a bad verifier report
     * as an implementation failure across later workflow executions.
     */
    "protocolViolation"?: string;

    /**
     * TestOutcome records the deterministic classification of a test-runner run
     * (product_bug, infra_failure, ambiguous_requirement, etc.). The testing
     * router counts only product_bug outcomes against the implementation budget.
     */
    "testOutcome"?: string;

    /**
     * TestFailureFingerprint is a stable hash of the grounded failure report.
     * Repeated fingerprints mean the same repro survived a fix attempt and should
     * get targeted human/local reproduction instead of another broad retry.
     */
    "testFailureFingerprint"?: string;

    /**
     * HeadSHA is the worktree HEAD commit at this run's completion — what the
     * agent left on the branch. Compared against the merged PR head to detect
     * human edits after the agent (merged_with_edits) and measure edit distance.
     */
    "headSha"?: string;

    /**
     * FinalCommitSource records who owned the branch head that verify_commits
     * settled on: "agent" when the final head came from the agent-pushed remote
     * commit, "fallback" when verify_commits had to auto-commit recovered work.
     */
    "finalCommitSource"?: string;

    /**
     * SubagentCallCount is the number of distinct forked-Claude subagent calls
     * observed in the run. Zero for non-Claude runs and runs recorded before
     * fan-out counting existed.
     */
    "subagentCallCount"?: number;

    /**
     * ResumeZeroOutputStall marks a run whose zero-output watchdog stall fired
     * (errorKind "rate_limit" + errorMsg watchdogreason.ZeroOutputBeforeStartup).
     * It is the durable poison signal agentorch.PickImplementationResumeSession
     * counts to detect a session stuck in a resume-stall loop.
     */
    "zeroOutputStall"?: boolean;

    /** Creates a new AgentRun instance. */
    constructor($$source: Partial<AgentRun> = {}) {
        if (!("agentId" in $$source)) {
            this["agentId"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("logFile" in $$source)) {
            this["logFile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentRun instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentRun {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentRun($$parsedSource as Partial<AgentRun>);
    }
}

/**
 * Attachment re-exports the persisted task attachment metadata type.
 */
export const Attachment = attachment$0.Attachment;

/**
 * Attachment re-exports the persisted task attachment metadata type.
 */
export type Attachment = attachment$0.Attachment;

/**
 * Priority is a task's dispatch priority. PriorityNone (the empty string) is
 * treated as the lowest priority, distinct from an unset/invalid value.
 */
export enum Priority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PriorityNone = "",
    PriorityLow = "low",
    PriorityMedium = "medium",
    PriorityHigh = "high",
    PriorityUrgent = "urgent",
};

/**
 * ReviewComment is an inline comment on a specific line of a plan.
 */
export class ReviewComment {
    "id": string;

    /**
     * 1-based line number in plan body
     */
    "line": number;
    "body": string;
    "resolved": boolean;
    "createdAt": string;

    /** Creates a new ReviewComment instance. */
    constructor($$source: Partial<ReviewComment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("resolved" in $$source)) {
            this["resolved"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewComment instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewComment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviewComment($$parsedSource as Partial<ReviewComment>);
    }
}

/**
 * Status is a task's position in its lifecycle (see the pipeline diagram in
 * the root CLAUDE.md). Transitions are enforced by the workflow engine and
 * callers should validate untrusted input with ValidateStatus rather than
 * casting a string directly.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusNew = "new",
    StatusTodo = "todo",
    StatusInProgress = "in-progress",
    StatusReadyReview = "ready-review",
    StatusInReview = "in-review",
    StatusPlanning = "planning",
    StatusPlanReview = "plan-review",
    StatusTesting = "testing",
    StatusReadyPR = "ready-pr",
    StatusHumanRequired = "human-required",
    StatusBlocked = "blocked",
    StatusDone = "done",
    StatusCancelled = "cancelled",
};

/**
 * Task is the in-memory representation of a task markdown file: YAML
 * frontmatter (everything but Body) plus the GFM markdown Body. Store parses
 * and marshals it to/from tasks/<id>.md; planning/review/critique content
 * lives in separate sidecar files (see Store.Plans, Store.PlanContracts,
 * etc.) and is populated onto these fields only on load.
 */
export class Task {
    "id": string;
    "slug": string;
    "title": string;
    "status": Status;
    "taskType": TaskType;
    "agentMode": string;
    "allowedTools": string[];
    "tags": string[];
    "projectId": string;
    "branch": string;

    /**
     * WorktreeDir, when non-empty, makes Sybra adopt an externally-created git
     * worktree at this path instead of creating its own under
     * ~/.sybra/worktrees. Used for handoff from tools like Orca: every agent
     * for this task runs in this directory, and Sybra never rebases, force-
     * pushes, or removes it — the external tool owns its lifecycle. Empty =
     * Sybra-managed worktree (default).
     */
    "worktreeDir"?: string;
    "prNumber": number;

    /**
     * Issue is the canonical originating GitHub issue this task implements —
     * set once at creation (or by auto-sources like the GitHub poller and
     * umbrella expansion) and consumed verbatim by execEnsurePRClosesIssue to
     * append "Closes <url>" to the task's PR body, by findActiveDuplicate for
     * dedup, and by the umbrella gate/DAG for state tracking. Never overwrite
     * this after creation to attach an unrelated reference — use RefIssue.
     */
    "issue": string;
    "statusReason": string;
    "blocker"?: blocker$0.State;

    /**
     * HandoffSourceProvider records which local agent provider produced the
     * work before a handoff skipped directly into review/testing/PR. Workflow
     * steps with provider=cross use it when there is no Sybra-authored run
     * history to flip from.
     */
    "handoffSourceProvider"?: string;

    /**
     * BlockedByIssue stores the URL of the GitHub issue that put the task
     * into status=blocked. Set by the human-review automation when it
     * concludes the human-required transition was caused by a Sybra bug.
     */
    "blockedByIssue"?: string;

    /**
     * UmbrellaIssue links this task to the ☂️ umbrella issue it was expanded
     * from. Set on child tasks; empty for standalone tasks. The orchestrator's
     * dependency gate reads it with DependsOn to decide when a child may leave
     * `blocked`.
     */
    "umbrellaIssue"?: string;

    /**
     * RefIssue is an ad-hoc reference URL attached after creation — e.g. a
     * related finding or duplicate noted while diagnosing why a task was
     * stuck. Purely informational: unlike Issue, nothing reads RefIssue to
     * drive PR auto-close, dedup, or umbrella state.
     */
    "refIssue"?: string;

    /**
     * DependsOn lists the issue refs (full github.com issue/PR URL or
     * owner/repo#n shorthand) this task waits on — resolved by issue ref only,
     * not task IDs. While the task is `blocked`, the gate holds it until every
     * referenced task has reached `done`; an empty list releases immediately.
     * Used only by umbrella child tasks.
     */
    "dependsOn"?: string[];
    "reviewed": boolean;

    /**
     * pr-fix when fixing review issues, "" for initial impl
     */
    "runRole": string;

    /**
     * SupervisorSteer is a one-shot corrective message left by the watchdog's
     * headless nudge: it stops a looping headless agent (which has no mid-stream
     * channel) and persists the steer here so the recovery loop re-dispatches
     * the resumed agent with the correction prepended to its prompt. Recovery
     * clears it after consuming it exactly once. Empty for tasks with no pending
     * nudge.
     */
    "supervisorSteer"?: string;

    /**
     * ReviewPhase tracks where an inbound PR-review task (tag `review`) sits in
     * the review lifecycle: reviewing → drafted → awaiting-author →
     * needs-approval → approved (plus `manual` for human follow-up). Computed by
     * the PR poller; drives the board's PR Reviews lane.
     * Empty for non-review tasks.
     */
    "reviewPhase"?: string;

    /**
     * Bounds automated re-review per PR commit: the durable backstop against a
     * re-dispatch loop (#2164 spent 112 reviews on one unchanged commit).
     */
    "reviewedHeadSha"?: string;
    "reviewedHeadAttempts"?: number;

    /**
     * PRPhase tracks where an outbound own-PR task (status in-review/ready-review,
     * not tag `review`) sits in its lifecycle: draft → building → fixing →
     * changes-requested → awaiting-approval → approved. Computed by the PR poller;
     * drives the phase glyph on the board's In Review cards. Empty for tasks
     * without an own PR (and for inbound review tasks, which use ReviewPhase).
     */
    "prPhase"?: string;
    "priority"?: Priority;
    "dueDate"?: string | null;
    "closedAt"?: string | null;

    /**
     * Outcome records how a task's own PR concluded: "merged", "merged_with_edits",
     * "closed", or "reverted". Stamped by the PR monitor when the task auto-advances
     * to done (and updated to "reverted" by the revert scanner). Empty for tasks
     * that never produced a PR. Feeds the evaluation scorecard.
     */
    "outcome"?: string;

    /**
     * MergeCommit is the default-branch commit a merged PR produced, recorded at
     * landing so the revert scanner can detect a later revert of it.
     */
    "mergeCommit"?: string;

    /**
     * MaxTurns overrides the global agent turn limit for this task.
     * Zero means "use global default".
     */
    "maxTurns"?: number;

    /**
     * RequirePermissions overrides the system default when set.
     * nil = use system default (true). false = opt out (--dangerously-skip-permissions).
     */
    "requirePermissions"?: boolean | null;

    /**
     * HeadlessPermissionMode overrides the permission posture for headless claude
     * runs on this task. "auto" emits --permission-mode auto; "bypass" keeps
     * --dangerously-skip-permissions. Empty = use config default.
     */
    "headlessPermissionMode"?: string;

    /**
     * ForkSubagent enables CLAUDE_CODE_FORK_SUBAGENT=1 for this task's headless
     * agent, allowing a single prompt to spawn parallel subagent runs. Trades
     * higher token cost for reduced wall-clock time on multi-part prompts.
     */
    "forkSubagent"?: boolean;

    /**
     * Sandbox is an escape hatch for the system default OS-level sandbox
     * posture (see config.AgentDefaults.SandboxMode) for this task's agent
     * processes. nil or true = use system default. false = disable the
     * sandbox-exec wrap entirely for this task's agents. Setting true does
     * NOT tighten posture beyond the system default (ResolveSandboxMode only
     * treats Sandbox=false as meaningful).
     */
    "sandbox"?: boolean | null;

    /**
     * ReasoningEffort sets the reasoning level for this task's agents
     * (low/medium/high/xhigh). Empty = model default. Applied across providers:
     * codex via -c model_reasoning_effort=<v>, claude and copilot via --effort.
     * The value set is the common subset all three CLIs accept.
     */
    "reasoningEffort"?: string;

    /**
     * TestingCycleStartedAt marks the start of the current testing cycle. It is
     * set when a human re-dispatches the task after a human-required escalation,
     * so route_test_result can exclude test-runner runs from prior cycles when
     * counting toward TestingMaxAttempts. Nil means no re-dispatch has occurred
     * and all test-runner runs count (correct for first-ever cycles).
     */
    "testingCycleStartedAt"?: string | null;
    "attachments": Attachment[];
    "agentRuns": AgentRun[];
    "workflow"?: workflow$0.Execution | null;
    "createdAt": string;
    "updatedAt": string;

    /**
     * StatusChangedAt marks the last time Status actually transitioned, as
     * opposed to UpdatedAt which is bumped by any field write (tags, audit
     * sidecars, status_reason, ...). Detectors that need to know "how long
     * has this task been in its current status" (e.g. detectLostAgents'
     * dispatch-latency grace window) must key off this field, not UpdatedAt —
     * see internal/monitor/detector.go.
     */
    "statusChangedAt": string;
    "assignedNode"?: string;
    "nodeOverride"?: string;
    "mirrorRev"?: number;
    "mirrorUpdatedAt"?: string | null;
    "body": string;
    "plan"?: string;
    "planContract"?: string;
    "planCritique"?: string;

    /**
     * Planning sidecars. Plan is the human-readable compact plan; PlanContract
     * is the machine-validated JSON contract consumed by implementation agents.
     * The remaining sidecars hold review/evidence material.
     */
    "planResearch"?: string;
    "planDecisions"?: string;
    "planBrief"?: string;
    "codeReview"?: string;

    /**
     * PlanDrafts holds per-provider raw plan outputs during dual- (or N-)
     * provider planning. Keys are typically the parallel child step ID
     * (e.g. "plan_claude", "plan_codex"). Populated from PlanDraftStore on
     * task load; the convergence step reads this map and writes the merged
     * result to Plan.
     */
    "planDrafts"?: { [_ in string]?: string };
    "filePath": string;

    /**
     * TamperFlagged reports whether this task is parked at human-required
     * pending a tamper bless. Derived from Status/StatusReason (never
     * persisted) so the frontend doesn't need to duplicate
     * workflow.TamperFlaggedReasonPrefix to decide whether to show the bless
     * action. Recomputed on every load/update — see taskFromFrontmatter and
     * Store.UpdateWithPrev.
     */
    "tamperFlagged": boolean;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("taskType" in $$source)) {
            this["taskType"] = TaskType.$zero;
        }
        if (!("agentMode" in $$source)) {
            this["agentMode"] = "";
        }
        if (!("allowedTools" in $$source)) {
            this["allowedTools"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("prNumber" in $$source)) {
            this["prNumber"] = 0;
        }
        if (!("issue" in $$source)) {
            this["issue"] = "";
        }
        if (!("statusReason" in $$source)) {
            this["statusReason"] = "";
        }
        if (!("reviewed" in $$source)) {
            this["reviewed"] = false;
        }
        if (!("runRole" in $$source)) {
            this["runRole"] = "";
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("agentRuns" in $$source)) {
            this["agentRuns"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("statusChangedAt" in $$source)) {
            this["statusChangedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("tamperFlagged" in $$source)) {
            this["tamperFlagged"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        const $$createField19_0 = $$createType0;
        const $$createField39_0 = $$createType3;
        const $$createField40_0 = $$createType5;
        const $$createField41_0 = $$createType7;
        const $$createField57_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedTools" in $$parsedSource) {
            $$parsedSource["allowedTools"] = $$createField6_0($$parsedSource["allowedTools"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        if ("blocker" in $$parsedSource) {
            $$parsedSource["blocker"] = $$createField14_0($$parsedSource["blocker"]);
        }
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField19_0($$parsedSource["dependsOn"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField39_0($$parsedSource["attachments"]);
        }
        if ("agentRuns" in $$parsedSource) {
            $$parsedSource["agentRuns"] = $$createField40_0($$parsedSource["agentRuns"]);
        }
        if ("workflow" in $$parsedSource) {
            $$parsedSource["workflow"] = $$createField41_0($$parsedSource["workflow"]);
        }
        if ("planDrafts" in $$parsedSource) {
            $$parsedSource["planDrafts"] = $$createField57_0($$parsedSource["planDrafts"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

/**
 * TaskType is an internal marker for umbrella tracker tasks.
 */
export enum TaskType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TaskTypeUmbrella is the tracker task for an expanded ☂️ umbrella issue.
     * It runs no agent: it rolls up the status of its child tasks and is the
     * task the dependency gate flips to human-required on a dependency cycle.
     */
    TaskTypeUmbrella = "umbrella",
};

/**
 * Update carries optional field changes for Store.Update.
 * A nil pointer means "leave unchanged"; a non-nil pointer applies the new value.
 * For Workflow: nil = unchanged; non-nil = overwrite (even if pointed-to value is nil).
 */
export class Update {
    "Title": string | null;
    "Slug": string | null;
    "Status": Status | null;
    "StatusReason": string | null;
    "Blocker": blocker$0.State | null;
    "BlockedByIssue": string | null;
    "UmbrellaIssue": string | null;
    "DependsOn": string[] | null;
    "AgentMode": string | null;
    "TaskType": TaskType | null;
    "Body": string | null;
    "Tags": string[] | null;
    "ProjectID": string | null;
    "Branch": string | null;
    "WorktreeDir": string | null;
    "HandoffSourceProvider": string | null;
    "PRNumber": number | null;
    "Issue": string | null;
    "RefIssue": string | null;
    "Reviewed": boolean | null;
    "RunRole": string | null;
    "SupervisorSteer": string | null;
    "ReviewPhase": string | null;
    "ReviewedHeadSHA": string | null;
    "ReviewedHeadAttempts": number | null;
    "PRPhase": string | null;
    "Priority": Priority | null;
    "DueDate": string | null;
    "Workflow": workflow$0.Execution | null;
    "Plan": string | null;
    "PlanContract": string | null;
    "PlanCritique": string | null;
    "PlanResearch": string | null;
    "PlanDecisions": string | null;
    "PlanBrief": string | null;
    "CodeReview": string | null;
    "MaxTurns": number | null;
    "ForkSubagent": boolean | null;
    "Sandbox": boolean | null;
    "ReasoningEffort": string | null;
    "Outcome": string | null;
    "MergeCommit": string | null;
    "TestingCycleStartedAt": string | null;
    "Attachments": Attachment[] | null;

    /** Creates a new Update instance. */
    constructor($$source: Partial<Update> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = null;
        }
        if (!("Slug" in $$source)) {
            this["Slug"] = null;
        }
        if (!("Status" in $$source)) {
            this["Status"] = null;
        }
        if (!("StatusReason" in $$source)) {
            this["StatusReason"] = null;
        }
        if (!("Blocker" in $$source)) {
            this["Blocker"] = null;
        }
        if (!("BlockedByIssue" in $$source)) {
            this["BlockedByIssue"] = null;
        }
        if (!("UmbrellaIssue" in $$source)) {
            this["UmbrellaIssue"] = null;
        }
        if (!("DependsOn" in $$source)) {
            this["DependsOn"] = null;
        }
        if (!("AgentMode" in $$source)) {
            this["AgentMode"] = null;
        }
        if (!("TaskType" in $$source)) {
            this["TaskType"] = null;
        }
        if (!("Body" in $$source)) {
            this["Body"] = null;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = null;
        }
        if (!("ProjectID" in $$source)) {
            this["ProjectID"] = null;
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = null;
        }
        if (!("WorktreeDir" in $$source)) {
            this["WorktreeDir"] = null;
        }
        if (!("HandoffSourceProvider" in $$source)) {
            this["HandoffSourceProvider"] = null;
        }
        if (!("PRNumber" in $$source)) {
            this["PRNumber"] = null;
        }
        if (!("Issue" in $$source)) {
            this["Issue"] = null;
        }
        if (!("RefIssue" in $$source)) {
            this["RefIssue"] = null;
        }
        if (!("Reviewed" in $$source)) {
            this["Reviewed"] = null;
        }
        if (!("RunRole" in $$source)) {
            this["RunRole"] = null;
        }
        if (!("SupervisorSteer" in $$source)) {
            this["SupervisorSteer"] = null;
        }
        if (!("ReviewPhase" in $$source)) {
            this["ReviewPhase"] = null;
        }
        if (!("ReviewedHeadSHA" in $$source)) {
            this["ReviewedHeadSHA"] = null;
        }
        if (!("ReviewedHeadAttempts" in $$source)) {
            this["ReviewedHeadAttempts"] = null;
        }
        if (!("PRPhase" in $$source)) {
            this["PRPhase"] = null;
        }
        if (!("Priority" in $$source)) {
            this["Priority"] = null;
        }
        if (!("DueDate" in $$source)) {
            this["DueDate"] = null;
        }
        if (!("Workflow" in $$source)) {
            this["Workflow"] = null;
        }
        if (!("Plan" in $$source)) {
            this["Plan"] = null;
        }
        if (!("PlanContract" in $$source)) {
            this["PlanContract"] = null;
        }
        if (!("PlanCritique" in $$source)) {
            this["PlanCritique"] = null;
        }
        if (!("PlanResearch" in $$source)) {
            this["PlanResearch"] = null;
        }
        if (!("PlanDecisions" in $$source)) {
            this["PlanDecisions"] = null;
        }
        if (!("PlanBrief" in $$source)) {
            this["PlanBrief"] = null;
        }
        if (!("CodeReview" in $$source)) {
            this["CodeReview"] = null;
        }
        if (!("MaxTurns" in $$source)) {
            this["MaxTurns"] = null;
        }
        if (!("ForkSubagent" in $$source)) {
            this["ForkSubagent"] = null;
        }
        if (!("Sandbox" in $$source)) {
            this["Sandbox"] = null;
        }
        if (!("ReasoningEffort" in $$source)) {
            this["ReasoningEffort"] = null;
        }
        if (!("Outcome" in $$source)) {
            this["Outcome"] = null;
        }
        if (!("MergeCommit" in $$source)) {
            this["MergeCommit"] = null;
        }
        if (!("TestingCycleStartedAt" in $$source)) {
            this["TestingCycleStartedAt"] = null;
        }
        if (!("Attachments" in $$source)) {
            this["Attachments"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     */
    static createFrom($$source: any = {}): Update {
        const $$createField4_0 = $$createType9;
        const $$createField7_0 = $$createType10;
        const $$createField11_0 = $$createType10;
        const $$createField28_0 = $$createType11;
        const $$createField43_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Blocker" in $$parsedSource) {
            $$parsedSource["Blocker"] = $$createField4_0($$parsedSource["Blocker"]);
        }
        if ("DependsOn" in $$parsedSource) {
            $$parsedSource["DependsOn"] = $$createField7_0($$parsedSource["DependsOn"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField11_0($$parsedSource["Tags"]);
        }
        if ("Workflow" in $$parsedSource) {
            $$parsedSource["Workflow"] = $$createField28_0($$parsedSource["Workflow"]);
        }
        if ("Attachments" in $$parsedSource) {
            $$parsedSource["Attachments"] = $$createField43_0($$parsedSource["Attachments"]);
        }
        return new Update($$parsedSource as Partial<Update>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = blocker$0.State.createFrom;
const $$createType2 = attachment$0.Attachment.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AgentRun.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = workflow$0.Execution.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Nullable($$createType1);
const $$createType10 = $Create.Nullable($$createType0);
const $$createType11 = $Create.Nullable($$createType7);
const $$createType12 = $Create.Nullable($$createType3);
