// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attachment$0 from "../attachment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as autonomy$0 from "../autonomy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as blocker$0 from "../blocker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as taskstatus$0 from "../taskstatus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflow$0 from "../workflow/models.js";

/**
 * AgentRun records one dispatch of an agent process against a task: what was
 * asked, which provider/model ran it, how it concluded, and the metadata
 * downstream deterministic routing (test outcome, tamper detection, A/B
 * evaluation) reads back off the run. A Task accumulates these in
 * Task.AgentRuns across its lifetime, most-recent last.
 */
export class AgentRun {
    "agentId": string;

    /**
     * explicit run role; legacy empty still means implementation
     */
    "role": string;
    "mode": string;
    "provider"?: string;
    "model"?: string;

    /**
     * ExperimentID/VariantID capture deterministic A/B assignment selected
     * before the run started.
     */
    "experimentId"?: string;
    "variantId"?: string;
    "routingReason"?: string;
    "assignmentUnit"?: string;
    "assignmentKey"?: string;
    "decisionVersion"?: number;
    "reasoningEffort"?: string;
    "requestedSkill"?: string;

    /**
     * SkillExecutionMode records how a mandatory workflow skill actually ran:
     * none, native invocation, injected SKILL.md, bundled fallback, or
     * unavailable. Legacy empty values remain readable and normalize to
     * unknown at query time.
     */
    "skillExecutionMode"?: string;

    /**
     * ResolvedSkillSourceHash is a privacy-safe hash of the resolved local or
     * bundled skill source identifier. Empty when the skill ran natively or no
     * source was resolved.
     */
    "resolvedSkillSourceHash"?: string;

    /**
     * SkillConformance records whether the executed skill path exactly matched
     * the requested skill, fell back, was unavailable, or had no skill at all.
     */
    "skillConformance"?: string;
    "state": string;

    /**
     * Outcome records the terminal result the completion handler actually
     * observed (RunOutcomeSuccess/RunOutcomeFailure), independent of State
     * ("stopped" covers both a clean finish and a failed one) and independent
     * of Result (truncated to maxResultLen, so its presence/absence cannot
     * tell success from failure either). Empty means the run never reached a
     * definitive terminal outcome (still running, or stalled/rate-limited and
     * due for retry) — callers must not infer success from Outcome == "".
     */
    "outcome"?: string;

    /**
     * EscalationReason records the guardrail reason that stopped the run
     * ("cost" or "turns"). Empty for ordinary completions.
     */
    "escalationReason"?: string;
    "startedAt": string;
    "costUsd": number;
    "toolFailures"?: number;
    "premiumRequests"?: number;
    "prompt"?: string;
    "result": string;
    "oneShot"?: boolean;

    /**
     * Verdict holds the parsed decision for human-review runs ("human" or
     * "sybra_bug"). Extracted from live agent output at completion time so
     * it survives Result truncation.
     */
    "verdict"?: string;

    /**
     * VerdictRendered is set to true after onComplete has successfully applied
     * all side-effects for this run (note appended, issue filed, local task
     * created). Used by verdictAlreadyRendered as the durable rendered-marker
     * instead of body-text patterns which can collide with user content.
     */
    "verdictRendered"?: boolean;

    /**
     * RecoveryReplayRejected records that startup replay evaluated this exact
     * unblocked verdict and permanently rejected it. It is keyed to the run so
     * a newer verdict with identical wording still gets its own evaluation.
     */
    "recoveryReplayRejected"?: boolean;
    "logFile": string;
    "sessionId"?: string;

    /**
     * ProtocolViolation records deterministic workflow-level contract failures
     * for this run. Test routing uses it to avoid counting a bad verifier report
     * as an implementation failure across later workflow executions.
     */
    "protocolViolation"?: string;

    /**
     * TestOutcome records the deterministic classification of a test-runner run
     * (product_bug, infra_failure, ambiguous_requirement, etc.). The testing
     * router counts only product_bug outcomes against the implementation budget.
     */
    "testOutcome"?: string;

    /**
     * TestFailureFingerprint is a stable hash of the grounded failure report.
     * Repeated fingerprints mean the same repro survived a fix attempt and should
     * get targeted human/local reproduction instead of another broad retry.
     */
    "testFailureFingerprint"?: string;

    /**
     * HeadSHA is the worktree HEAD commit at this run's completion — what the
     * agent left on the branch. Compared against the merged PR head to detect
     * human edits after the agent (merged_with_edits) and measure edit distance.
     */
    "headSha"?: string;

    /**
     * FinalCommitSource records who owned the branch head that verify_commits
     * settled on: "agent" when the final head came from the agent-pushed remote
     * commit, "fallback" when verify_commits had to auto-commit recovered work.
     */
    "finalCommitSource"?: string;

    /**
     * SubagentCallCount is the number of distinct forked-Claude subagent calls
     * observed in the run. Zero for non-Claude runs and runs recorded before
     * fan-out counting existed.
     */
    "subagentCallCount"?: number;

    /**
     * ResumeZeroOutputStall marks a run whose zero-output watchdog stall fired
     * (errorKind "silent_hang" + errorMsg watchdogreason.ZeroOutputBeforeStartup).
     * It is the durable poison signal agentorch.PickImplementationResumeSession
     * counts to detect a session stuck in a resume-stall loop.
     */
    "zeroOutputStall"?: boolean;

    /**
     * TurnCount is zero when the child produced nothing, so the run holds no
     * evidence about its instructions and must not spend a conformance budget.
     */
    "turnCount"?: number;

    /** Creates a new AgentRun instance. */
    constructor($$source: Partial<AgentRun> = {}) {
        if (!("agentId" in $$source)) {
            this["agentId"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("logFile" in $$source)) {
            this["logFile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentRun instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentRun {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentRun($$parsedSource as Partial<AgentRun>);
    }
}

/**
 * Attachment re-exports the persisted task attachment metadata type.
 */
export const Attachment = attachment$0.Attachment;

/**
 * Attachment re-exports the persisted task attachment metadata type.
 */
export type Attachment = attachment$0.Attachment;

/**
 * DepCondition attaches a completion condition to one Task.DependsOn ref.
 * Ref must match a current DependsOn entry (by the same ref-matching rules
 * the gate uses elsewhere, e.g. matchesDepRef) or the condition is inert.
 * 
 * Kind "label" mechanically checks the referenced closing issue's GitHub
 * labels (via cached github.FetchIssue) for Value's label name; it holds the
 * child while absent and self-heals the next time the gate ticks after the
 * label is applied — no escalation.
 * 
 * Kind "note" never auto-satisfies: it holds the child and escalates to
 * human-required, naming Value as the free-text acceptance note a human must
 * confirm. Clearing the resulting blocker (blocker.KindDependencyConditionUnmet)
 * alone does not release the child — as long as this condition still names a
 * current DependsOn ref, the gate re-escalates on the next tick it becomes
 * ready again. A human must remove or edit the condition itself (once the
 * scope it names is confirmed to exist) to actually release the child; this
 * mirrors blocker.KindDependencyScopeUnmet's existing require-explicit-
 * human-confirmation design and is an accepted limitation, not a bug.
 */
export class DepCondition {
    "ref": string;
    "kind": string;
    "value": string;

    /** Creates a new DepCondition instance. */
    constructor($$source: Partial<DepCondition> = {}) {
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DepCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): DepCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DepCondition($$parsedSource as Partial<DepCondition>);
    }
}

/**
 * PlanDraftEntry names the one plan draft PlanDraftWrite sets. Unlike every
 * other sidecar field, PlanDrafts is a map (one entry per parallel planner),
 * so a single Update can only ever add or replace one named entry, never
 * express the whole map at once.
 */
export class PlanDraftEntry {
    "Name": string;
    "Content": string;

    /** Creates a new PlanDraftEntry instance. */
    constructor($$source: Partial<PlanDraftEntry> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanDraftEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanDraftEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanDraftEntry($$parsedSource as Partial<PlanDraftEntry>);
    }
}

/**
 * Priority is a task's dispatch priority. PriorityNone (the empty string) is
 * treated as the lowest priority, distinct from an unset/invalid value.
 */
export enum Priority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PriorityNone = "",
    PriorityLow = "low",
    PriorityMedium = "medium",
    PriorityHigh = "high",
    PriorityUrgent = "urgent",
};

/**
 * ReviewComment is an inline comment on a specific line of a plan.
 */
export class ReviewComment {
    "id": string;

    /**
     * 1-based line number in plan body
     */
    "line": number;
    "body": string;
    "resolved": boolean;
    "createdAt": string;

    /** Creates a new ReviewComment instance. */
    constructor($$source: Partial<ReviewComment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("resolved" in $$source)) {
            this["resolved"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewComment instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewComment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviewComment($$parsedSource as Partial<ReviewComment>);
    }
}

/**
 * Status re-exports the task status vocabulary from internal/taskstatus.
 * The type and constants live in a leaf package so internal/workflow can use
 * them too; internal/task imports internal/workflow, so they cannot live here.
 * These aliases keep every existing caller and the Wails bindings unchanged.
 */
export type Status = taskstatus$0.Status;

/**
 * Task is the in-memory representation of a task markdown file: YAML
 * frontmatter (everything but Body) plus the GFM markdown Body. Store parses
 * and marshals it to/from tasks/<id>.md; planning/review/critique content
 * lives in separate sidecar files (see Store.Plans, Store.PlanContracts,
 * etc.) and is populated onto these fields only on load.
 */
export class Task {
    "id": string;
    "slug": string;
    "title": string;
    "status": Status;
    "taskType": TaskType;
    "agentMode": string;
    "allowedTools": string[];
    "tags": string[];
    "projectId": string;
    "branch": string;

    /**
     * WorktreeDir, when non-empty, makes Sybra adopt an externally-created git
     * worktree at this path instead of creating its own under
     * ~/.sybra/worktrees. Used for handoff from tools like Orca: every agent
     * for this task runs in this directory, and Sybra never rebases, force-
     * pushes, or removes it — the external tool owns its lifecycle. Empty =
     * Sybra-managed worktree (default).
     */
    "worktreeDir"?: string;
    "prNumber": number;

    /**
     * Issue is the canonical originating GitHub issue this task implements —
     * set once at creation (or by auto-sources like the GitHub poller and
     * umbrella expansion) and consumed verbatim by execEnsurePRClosesIssue to
     * append "Closes <url>" to the task's PR body, by findActiveDuplicate for
     * dedup, and by the umbrella gate/DAG for state tracking. Never overwrite
     * this after creation to attach an unrelated reference — use RefIssue.
     */
    "issue": string;
    "statusReason": string;

    /**
     * Escalation is the policy authority for the current human-required state.
     * StatusReason remains display text and must never be parsed back into a
     * failure owner or recovery decision. Legacy files load with an explicit
     * unknown/legacy adapter (see taskFromFrontmatter).
     */
    "escalation"?: autonomy$0.EscalationReason;
    "autonomyOutcome"?: autonomy$0.Outcome;
    "blocker"?: blocker$0.State;

    /**
     * HandoffSourceProvider records which local agent provider produced the
     * work before a handoff skipped directly into review/testing/PR. Workflow
     * steps with provider=cross use it when there is no Sybra-authored run
     * history to flip from.
     */
    "handoffSourceProvider"?: string;

    /**
     * BlockedByIssue stores the URL of the GitHub issue that put the task
     * into status=blocked. Set by the human-review automation when it
     * concludes the human-required transition was caused by a Sybra bug.
     */
    "blockedByIssue"?: string;

    /**
     * UmbrellaIssue links this task to the ☂️ umbrella issue it was expanded
     * from. Set on child tasks; empty for standalone tasks. The orchestrator's
     * dependency gate reads it with DependsOn to decide when a child may leave
     * `blocked`.
     */
    "umbrellaIssue"?: string;

    /**
     * RefIssue is an ad-hoc reference URL attached after creation — e.g. a
     * related finding or duplicate noted while diagnosing why a task was
     * stuck. Purely informational: unlike Issue, nothing reads RefIssue to
     * drive PR auto-close, dedup, or umbrella state.
     */
    "refIssue"?: string;

    /**
     * DependsOn lists the issue refs (full github.com issue/PR URL or
     * owner/repo#n shorthand) this task waits on — resolved by issue ref only,
     * not task IDs. While the task is `blocked`, the gate holds it until every
     * referenced task has reached `done`; an empty list releases immediately.
     * Used only by umbrella child tasks. Not exclusively planner-authored: the
     * gate also folds in a ref it parses out of the body as a free-text
     * "after #N" precondition on a different program's issue — one the
     * planner's own schema can never emit, since it only allows refs among an
     * umbrella's own sub-issues (see umbrella.ExternalBlockers) — and persists
     * it here so it survives as structured state instead of being re-derived
     * from prose every gate tick.
     */
    "dependsOn"?: string[];

    /**
     * DependsOnConditions attaches an optional completion condition to one of
     * DependsOn's refs, beyond that task simply reaching Done — the umbrella
     * dependency gate (holdUnmetConditions in
     * internal/sybra/app_umbrella_gate.go) enforces it before releasing a
     * child. A condition whose Ref no longer names a current DependsOn entry
     * is inert (never enforced), the same rule the gate already applies to a
     * stale blocker.KindDependencyScopeUnmet verdict. See DepCondition for the
     * supported Kind values (sybra#2649: a prior run closed a dependency
     * issue via a narrower PR than the scope this task actually needed, and
     * nothing structural caught it before a wasted implementation cycle).
     */
    "dependsOnConditions"?: DepCondition[];
    "reviewed": boolean;

    /**
     * pr-fix when fixing review issues, "" for initial impl
     */
    "runRole": string;

    /**
     * SupervisorSteer is a one-shot corrective message left by the watchdog's
     * headless nudge: it stops a looping headless agent (which has no mid-stream
     * channel) and persists the steer here so the recovery loop re-dispatches
     * the resumed agent with the correction prepended to its prompt. Recovery
     * clears it after consuming it exactly once. Empty for tasks with no pending
     * nudge.
     */
    "supervisorSteer"?: string;

    /**
     * ReviewPhase tracks where an inbound PR-review task (tag `review`) sits in
     * the review lifecycle: reviewing → drafted → awaiting-author →
     * needs-approval → approved (plus `manual` for human follow-up). Computed by
     * the PR poller; drives the board's PR Reviews lane.
     * Empty for non-review tasks.
     */
    "reviewPhase"?: string;

    /**
     * Bounds automated re-review per PR commit: the durable backstop against a
     * re-dispatch loop (#2164 spent 112 reviews on one unchanged commit).
     */
    "reviewedHeadSha"?: string;
    "reviewedHeadAttempts"?: number;

    /**
     * ReconcileFailures counts consecutive non-transient review-phase reconcile
     * failures (#2199); recordReconcileFailure escalates to human-required once
     * it reaches reconcileFailureLimit. Durable so a process restart never
     * hands a permanently-failing task a fresh free budget.
     */
    "reconcileFailures"?: number;

    /**
     * PRPhase tracks where an outbound own-PR task (status in-review/ready-review,
     * not tag `review`) sits in its lifecycle: draft → building → fixing →
     * changes-requested → awaiting-approval → approved. Computed by the PR poller;
     * drives the phase glyph on the board's In Review cards. Empty for tasks
     * without an own PR (and for inbound review tasks, which use ReviewPhase).
     */
    "prPhase"?: string;
    "priority"?: Priority;
    "dueDate"?: string | null;
    "closedAt"?: string | null;

    /**
     * Outcome records how a task's own PR concluded: "merged", "merged_with_edits",
     * "closed", or "reverted". Stamped by the PR monitor when the task auto-advances
     * to done (and updated to "reverted" by the revert scanner). Empty for tasks
     * that never produced a PR. Feeds the evaluation scorecard.
     */
    "outcome"?: string;

    /**
     * MergeCommit is the default-branch commit a merged PR produced, recorded at
     * landing so the revert scanner can detect a later revert of it.
     */
    "mergeCommit"?: string;

    /**
     * MaxTurns overrides the global agent turn limit for this task.
     * Zero means "use global default".
     */
    "maxTurns"?: number;

    /**
     * RequirePermissions overrides the system default when set.
     * nil = use system default (true). false = opt out (--dangerously-skip-permissions).
     */
    "requirePermissions"?: boolean | null;

    /**
     * HeadlessPermissionMode overrides the permission posture for headless claude
     * runs on this task. "auto" emits --permission-mode auto; "bypass" keeps
     * --dangerously-skip-permissions. Empty = use config default.
     */
    "headlessPermissionMode"?: string;

    /**
     * ForkSubagent enables CLAUDE_CODE_FORK_SUBAGENT=1 for this task's headless
     * agent, allowing a single prompt to spawn parallel subagent runs. Trades
     * higher token cost for reduced wall-clock time on multi-part prompts.
     */
    "forkSubagent"?: boolean;

    /**
     * Sandbox is an escape hatch for the system default OS-level sandbox
     * posture (see config.AgentDefaults.SandboxMode) for this task's agent
     * processes. nil or true = use system default. false = disable the
     * sandbox-exec wrap entirely for this task's agents. Setting true does
     * NOT tighten posture beyond the system default (ResolveSandboxMode only
     * treats Sandbox=false as meaningful).
     */
    "sandbox"?: boolean | null;

    /**
     * SandboxOffReason explains why Sandbox is false. Disabling the sandbox
     * hands a task's agents unrestricted write access to the host, so the
     * audit trail needs to say why rather than only that it happened.
     * Meaningful only alongside Sandbox=false; ignored otherwise.
     */
    "sandboxOffReason"?: string;

    /**
     * ReasoningEffort sets the reasoning level for this task's agents
     * (low/medium/high/xhigh). Empty = model default. Applied across providers:
     * codex via -c model_reasoning_effort=<v>, claude and copilot via --effort.
     * The value set is the common subset all three CLIs accept.
     */
    "reasoningEffort"?: string;

    /**
     * TestingCycleStartedAt marks the start of the current testing cycle. It is
     * set when a human re-dispatches the task after a human-required escalation,
     * so route_test_result can exclude test-runner runs from prior cycles when
     * counting toward TestingMaxAttempts. Nil means no re-dispatch has occurred
     * and all test-runner runs count (correct for first-ever cycles).
     */
    "testingCycleStartedAt"?: string | null;
    "attachments": Attachment[];
    "agentRuns": AgentRun[];

    /**
     * EffectLog records durable intent/completion for observer-owned task
     * status effects (pollers, monitor, recovery) that operate outside a live
     * workflow execution.
     */
    "effectLog"?: workflow$0.EffectRecord[];
    "workflow"?: workflow$0.Execution | null;
    "createdAt": string;
    "updatedAt": string;

    /**
     * StatusChangedAt marks the last time Status actually transitioned, as
     * opposed to UpdatedAt which is bumped by any field write (tags, audit
     * sidecars, status_reason, ...). Detectors that need to know "how long
     * has this task been in its current status" (e.g. detectLostAgents'
     * dispatch-latency grace window) must key off this field, not UpdatedAt —
     * see internal/monitor/detector.go.
     */
    "statusChangedAt": string;
    "assignedNode"?: string;
    "nodeOverride"?: string;
    "assignmentRev"?: number;
    "generation"?: number;
    "mirrorRev"?: number;
    "mirrorUpdatedAt"?: string | null;
    "body": string;
    "plan"?: string;
    "planContract"?: string;
    "planCritique"?: string;

    /**
     * Planning sidecars. Plan is the human-readable compact plan; PlanContract
     * is the machine-validated JSON contract consumed by implementation agents.
     * The remaining sidecars hold review/evidence material.
     */
    "planResearch"?: string;
    "planDecisions"?: string;
    "planBrief"?: string;
    "codeReview"?: string;

    /**
     * CodeReviewVerdict is the last review-role step's structured verdict
     * ("CLEAN"/"NEEDS_FIXES"), extracted from the agent's schema-enforced
     * output rather than the CodeReview sidecar markdown (see
     * workflow.ExtractReviewVerdict). Persisted so a re-triggered workflow run
     * can tell a genuine NEEDS_FIXES review from Reviewed=true without
     * re-parsing the sidecar for a literal-prefix marker.
     */
    "codeReviewVerdict"?: string;
    "currentTestFailures"?: string;
    "acceptanceLedger"?: string;
    "specDecision"?: string;

    /**
     * PlanDrafts holds per-provider raw plan outputs during dual- (or N-)
     * provider planning. Keys are typically the parallel child step ID
     * (e.g. "plan_claude", "plan_codex"). Populated from PlanDraftStore on
     * task load; the convergence step reads this map and writes the merged
     * result to Plan.
     */
    "planDrafts"?: { [_ in string]?: string };
    "filePath": string;

    /**
     * Degraded marks a synthetic, read-only board entry created for a task file
     * that could not be parsed. It is never persisted and must never be
     * dispatched or mirrored; fixing the source file makes the entry disappear
     * on the next List.
     */
    "degraded"?: boolean;
    "parseError"?: string;

    /**
     * TamperFlagged reports whether this task is parked at human-required
     * pending a tamper bless. Derived from Status/Blocker (never persisted) so
     * the frontend doesn't need to duplicate the latch logic to decide whether
     * to show the bless action. Recomputed on every load/update — see
     * taskFromFrontmatter and Store.UpdateWithPrev.
     */
    "tamperFlagged": boolean;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = taskstatus$0.Status.$zero;
        }
        if (!("taskType" in $$source)) {
            this["taskType"] = TaskType.$zero;
        }
        if (!("agentMode" in $$source)) {
            this["agentMode"] = "";
        }
        if (!("allowedTools" in $$source)) {
            this["allowedTools"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("prNumber" in $$source)) {
            this["prNumber"] = 0;
        }
        if (!("issue" in $$source)) {
            this["issue"] = "";
        }
        if (!("statusReason" in $$source)) {
            this["statusReason"] = "";
        }
        if (!("reviewed" in $$source)) {
            this["reviewed"] = false;
        }
        if (!("runRole" in $$source)) {
            this["runRole"] = "";
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("agentRuns" in $$source)) {
            this["agentRuns"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("statusChangedAt" in $$source)) {
            this["statusChangedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("tamperFlagged" in $$source)) {
            this["tamperFlagged"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        const $$createField16_0 = $$createType2;
        const $$createField21_0 = $$createType0;
        const $$createField22_0 = $$createType4;
        const $$createField44_0 = $$createType6;
        const $$createField45_0 = $$createType8;
        const $$createField46_0 = $$createType10;
        const $$createField47_0 = $$createType12;
        const $$createField69_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedTools" in $$parsedSource) {
            $$parsedSource["allowedTools"] = $$createField6_0($$parsedSource["allowedTools"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        if ("escalation" in $$parsedSource) {
            $$parsedSource["escalation"] = $$createField14_0($$parsedSource["escalation"]);
        }
        if ("blocker" in $$parsedSource) {
            $$parsedSource["blocker"] = $$createField16_0($$parsedSource["blocker"]);
        }
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField21_0($$parsedSource["dependsOn"]);
        }
        if ("dependsOnConditions" in $$parsedSource) {
            $$parsedSource["dependsOnConditions"] = $$createField22_0($$parsedSource["dependsOnConditions"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField44_0($$parsedSource["attachments"]);
        }
        if ("agentRuns" in $$parsedSource) {
            $$parsedSource["agentRuns"] = $$createField45_0($$parsedSource["agentRuns"]);
        }
        if ("effectLog" in $$parsedSource) {
            $$parsedSource["effectLog"] = $$createField46_0($$parsedSource["effectLog"]);
        }
        if ("workflow" in $$parsedSource) {
            $$parsedSource["workflow"] = $$createField47_0($$parsedSource["workflow"]);
        }
        if ("planDrafts" in $$parsedSource) {
            $$parsedSource["planDrafts"] = $$createField69_0($$parsedSource["planDrafts"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

/**
 * TaskType is an internal marker for umbrella tracker tasks.
 */
export enum TaskType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TaskTypeUmbrella is the tracker task for an expanded ☂️ umbrella issue.
     * It runs no agent: it rolls up the status of its child tasks and is the
     * task the dependency gate flips to human-required on a dependency cycle.
     */
    TaskTypeUmbrella = "umbrella",
};

/**
 * TransitionIntent is a request to move a task to ToStatus through the
 * single sanctioned status-mutation entrypoint, Manager.Apply. It is the
 * narrow command object every production status writer (workflow, review,
 * monitor, watchdog, recovery, service code) should submit instead of
 * calling Manager.Update/UpdateFn with a Status field directly — see #2726.
 */
export class TransitionIntent {
    /**
     * TaskID is the task to transition. Required.
     */
    "TaskID": string;

    /**
     * ToStatus is the target status. Required.
     */
    "ToStatus": Status;

    /**
     * Actor identifies the subsystem submitting the intent (e.g.
     * "workflow.engine", "agentorch.gate") for audit and idempotency-key
     * scoping. Required.
     */
    "Actor": string;

    /**
     * Extra carries additional field mutations applied atomically with the
     * status change (StatusReason, Blocker, Tags, PRNumber, ...). Its Status
     * field must be nil — set ToStatus instead; Apply rejects intents that
     * set both to avoid two conflicting sources of truth for the same write.
     */
    "Extra": Update;

    /**
     * ExpectedGeneration, given, is an optimistic-concurrency precondition:
     * Apply returns a *ConflictError instead of mutating the task if the
     * task's current Generation does not match. Nil skips the check.
     */
    "ExpectedGeneration": number | null;

    /**
     * ExpectedStatus, given, is a precondition on the task's current Status,
     * checked the same way as ExpectedGeneration. Nil skips the check.
     */
    "ExpectedStatus": Status | null;

    /**
     * IdempotencyKey, given, makes replaying the identical intent against a
     * task that has not changed generation since it was applied a no-op
     * instead of reapplying — the safe way to retry after a crash or a
     * timeout between commit and the caller observing success. Empty means
     * every call applies unconditionally (bare unconditional writes, e.g.
     * funneling an existing scattered caller through Apply for the first
     * time without changing its replay semantics).
     */
    "IdempotencyKey": string;

    /**
     * OperatorOverride bypasses the allowed-transition table (see
     * transitions.go): set this only at a human-initiated entry point (a
     * button click or CLI command a person invoked directly), never at an
     * automated call site. It exists for the narrow set of moves that are
     * legitimate only as a deliberate human action — e.g. reopening a
     * terminal task — and must never happen automatically.
     */
    "OperatorOverride": boolean;

    /** Creates a new TransitionIntent instance. */
    constructor($$source: Partial<TransitionIntent> = {}) {
        if (!("TaskID" in $$source)) {
            this["TaskID"] = "";
        }
        if (!("ToStatus" in $$source)) {
            this["ToStatus"] = taskstatus$0.Status.$zero;
        }
        if (!("Actor" in $$source)) {
            this["Actor"] = "";
        }
        if (!("Extra" in $$source)) {
            this["Extra"] = (new Update());
        }
        if (!("ExpectedGeneration" in $$source)) {
            this["ExpectedGeneration"] = null;
        }
        if (!("ExpectedStatus" in $$source)) {
            this["ExpectedStatus"] = null;
        }
        if (!("IdempotencyKey" in $$source)) {
            this["IdempotencyKey"] = "";
        }
        if (!("OperatorOverride" in $$source)) {
            this["OperatorOverride"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransitionIntent instance from a string or object.
     */
    static createFrom($$source: any = {}): TransitionIntent {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Extra" in $$parsedSource) {
            $$parsedSource["Extra"] = $$createField3_0($$parsedSource["Extra"]);
        }
        return new TransitionIntent($$parsedSource as Partial<TransitionIntent>);
    }
}

/**
 * TransitionResult is the outcome of a successful Apply call.
 */
export class TransitionResult {
    /**
     * Task is the task as it stands after Apply returns — either freshly
     * mutated, or (when Applied is false) the unchanged current task.
     */
    "Task": Task;

    /**
     * Applied is false when Apply short-circuited on an idempotent replay:
     * a prior call already consumed this exact IdempotencyKey at the
     * generation this call would have consumed it at, so no audit, dispatch,
     * review, or notification effect fired a second time.
     */
    "Applied": boolean;

    /** Creates a new TransitionResult instance. */
    constructor($$source: Partial<TransitionResult> = {}) {
        if (!("Task" in $$source)) {
            this["Task"] = (new Task());
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransitionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TransitionResult {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Task" in $$parsedSource) {
            $$parsedSource["Task"] = $$createField0_0($$parsedSource["Task"]);
        }
        return new TransitionResult($$parsedSource as Partial<TransitionResult>);
    }
}

/**
 * TrashEntry describes one soft-deleted task generation for ListTrash and
 * PruneTrash callers (CLI table/JSON output, prune logging).
 */
export class TrashEntry {
    "id": string;
    "generation": string;
    "deleted_date": string;
    "deleted_at": string;
    "title": string;

    /** Creates a new TrashEntry instance. */
    constructor($$source: Partial<TrashEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = "";
        }
        if (!("deleted_date" in $$source)) {
            this["deleted_date"] = "";
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TrashEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrashEntry($$parsedSource as Partial<TrashEntry>);
    }
}

/**
 * Update carries optional field changes for Store.Update.
 * A nil pointer means "leave unchanged"; a non-nil pointer applies the new value.
 * For Workflow: nil = unchanged; non-nil = overwrite. A clear goes through ClearWorkflow instead: a non-nil Workflow holding a nil inner pointer works in-process but not over the API, so it is never the right encoding.
 */
export class Update {
    "Title": string | null;
    "Slug": string | null;
    "Status": Status | null;
    "StatusReason": string | null;
    "ClearStatusReason": boolean | null;
    "Escalation": autonomy$0.EscalationReason | null;
    "AutonomyOutcome": autonomy$0.Outcome | null;
    "Blocker": blocker$0.State | null;
    "ClearBlocker": boolean | null;

    /**
     * ClearWorkflow removes the task's workflow execution, and is the only encoding of a clear that survives JSON. Workflow is a **Execution: a non-nil outer pointer holding a nil inner one marshals to null, and unmarshal then nils the outer pointer, so a clear sent over the API read back as "leave unchanged".
     */
    "ClearWorkflow": boolean | null;
    "BlockedByIssue": string | null;
    "UmbrellaIssue": string | null;
    "DependsOn": string[] | null;
    "DependsOnConditions": DepCondition[] | null;
    "AgentMode": string | null;
    "TaskType": TaskType | null;
    "Body": string | null;
    "Tags": string[] | null;
    "ProjectID": string | null;
    "Branch": string | null;
    "WorktreeDir": string | null;
    "HandoffSourceProvider": string | null;
    "PRNumber": number | null;
    "Issue": string | null;
    "RefIssue": string | null;
    "Reviewed": boolean | null;
    "RunRole": string | null;
    "SupervisorSteer": string | null;
    "ReviewPhase": string | null;
    "ReviewedHeadSHA": string | null;
    "ReviewedHeadAttempts": number | null;
    "ReconcileFailures": number | null;
    "PRPhase": string | null;
    "Priority": Priority | null;
    "DueDate": string | null;
    "Workflow": workflow$0.Execution | null;
    "Plan": string | null;
    "PlanContract": string | null;
    "PlanCritique": string | null;
    "PlanResearch": string | null;
    "PlanDecisions": string | null;
    "PlanBrief": string | null;
    "CodeReview": string | null;
    "CurrentTestFailures": string | null;
    "AcceptanceLedger": string | null;
    "SpecDecision": string | null;
    "PlanDraftWrite": PlanDraftEntry | null;
    "CodeReviewVerdict": string | null;
    "MaxTurns": number | null;
    "ForkSubagent": boolean | null;
    "Sandbox": boolean | null;
    "SandboxOffReason": string | null;
    "ReasoningEffort": string | null;
    "Outcome": string | null;
    "MergeCommit": string | null;
    "TestingCycleStartedAt": string | null;
    "Attachments": Attachment[] | null;
    "EffectLog": workflow$0.EffectRecord[] | null;

    /** Creates a new Update instance. */
    constructor($$source: Partial<Update> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = null;
        }
        if (!("Slug" in $$source)) {
            this["Slug"] = null;
        }
        if (!("Status" in $$source)) {
            this["Status"] = null;
        }
        if (!("StatusReason" in $$source)) {
            this["StatusReason"] = null;
        }
        if (!("ClearStatusReason" in $$source)) {
            this["ClearStatusReason"] = null;
        }
        if (!("Escalation" in $$source)) {
            this["Escalation"] = null;
        }
        if (!("AutonomyOutcome" in $$source)) {
            this["AutonomyOutcome"] = null;
        }
        if (!("Blocker" in $$source)) {
            this["Blocker"] = null;
        }
        if (!("ClearBlocker" in $$source)) {
            this["ClearBlocker"] = null;
        }
        if (!("ClearWorkflow" in $$source)) {
            this["ClearWorkflow"] = null;
        }
        if (!("BlockedByIssue" in $$source)) {
            this["BlockedByIssue"] = null;
        }
        if (!("UmbrellaIssue" in $$source)) {
            this["UmbrellaIssue"] = null;
        }
        if (!("DependsOn" in $$source)) {
            this["DependsOn"] = null;
        }
        if (!("DependsOnConditions" in $$source)) {
            this["DependsOnConditions"] = null;
        }
        if (!("AgentMode" in $$source)) {
            this["AgentMode"] = null;
        }
        if (!("TaskType" in $$source)) {
            this["TaskType"] = null;
        }
        if (!("Body" in $$source)) {
            this["Body"] = null;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = null;
        }
        if (!("ProjectID" in $$source)) {
            this["ProjectID"] = null;
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = null;
        }
        if (!("WorktreeDir" in $$source)) {
            this["WorktreeDir"] = null;
        }
        if (!("HandoffSourceProvider" in $$source)) {
            this["HandoffSourceProvider"] = null;
        }
        if (!("PRNumber" in $$source)) {
            this["PRNumber"] = null;
        }
        if (!("Issue" in $$source)) {
            this["Issue"] = null;
        }
        if (!("RefIssue" in $$source)) {
            this["RefIssue"] = null;
        }
        if (!("Reviewed" in $$source)) {
            this["Reviewed"] = null;
        }
        if (!("RunRole" in $$source)) {
            this["RunRole"] = null;
        }
        if (!("SupervisorSteer" in $$source)) {
            this["SupervisorSteer"] = null;
        }
        if (!("ReviewPhase" in $$source)) {
            this["ReviewPhase"] = null;
        }
        if (!("ReviewedHeadSHA" in $$source)) {
            this["ReviewedHeadSHA"] = null;
        }
        if (!("ReviewedHeadAttempts" in $$source)) {
            this["ReviewedHeadAttempts"] = null;
        }
        if (!("ReconcileFailures" in $$source)) {
            this["ReconcileFailures"] = null;
        }
        if (!("PRPhase" in $$source)) {
            this["PRPhase"] = null;
        }
        if (!("Priority" in $$source)) {
            this["Priority"] = null;
        }
        if (!("DueDate" in $$source)) {
            this["DueDate"] = null;
        }
        if (!("Workflow" in $$source)) {
            this["Workflow"] = null;
        }
        if (!("Plan" in $$source)) {
            this["Plan"] = null;
        }
        if (!("PlanContract" in $$source)) {
            this["PlanContract"] = null;
        }
        if (!("PlanCritique" in $$source)) {
            this["PlanCritique"] = null;
        }
        if (!("PlanResearch" in $$source)) {
            this["PlanResearch"] = null;
        }
        if (!("PlanDecisions" in $$source)) {
            this["PlanDecisions"] = null;
        }
        if (!("PlanBrief" in $$source)) {
            this["PlanBrief"] = null;
        }
        if (!("CodeReview" in $$source)) {
            this["CodeReview"] = null;
        }
        if (!("CurrentTestFailures" in $$source)) {
            this["CurrentTestFailures"] = null;
        }
        if (!("AcceptanceLedger" in $$source)) {
            this["AcceptanceLedger"] = null;
        }
        if (!("SpecDecision" in $$source)) {
            this["SpecDecision"] = null;
        }
        if (!("PlanDraftWrite" in $$source)) {
            this["PlanDraftWrite"] = null;
        }
        if (!("CodeReviewVerdict" in $$source)) {
            this["CodeReviewVerdict"] = null;
        }
        if (!("MaxTurns" in $$source)) {
            this["MaxTurns"] = null;
        }
        if (!("ForkSubagent" in $$source)) {
            this["ForkSubagent"] = null;
        }
        if (!("Sandbox" in $$source)) {
            this["Sandbox"] = null;
        }
        if (!("SandboxOffReason" in $$source)) {
            this["SandboxOffReason"] = null;
        }
        if (!("ReasoningEffort" in $$source)) {
            this["ReasoningEffort"] = null;
        }
        if (!("Outcome" in $$source)) {
            this["Outcome"] = null;
        }
        if (!("MergeCommit" in $$source)) {
            this["MergeCommit"] = null;
        }
        if (!("TestingCycleStartedAt" in $$source)) {
            this["TestingCycleStartedAt"] = null;
        }
        if (!("Attachments" in $$source)) {
            this["Attachments"] = null;
        }
        if (!("EffectLog" in $$source)) {
            this["EffectLog"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     */
    static createFrom($$source: any = {}): Update {
        const $$createField5_0 = $$createType16;
        const $$createField7_0 = $$createType17;
        const $$createField12_0 = $$createType18;
        const $$createField13_0 = $$createType19;
        const $$createField17_0 = $$createType18;
        const $$createField35_0 = $$createType20;
        const $$createField46_0 = $$createType22;
        const $$createField56_0 = $$createType23;
        const $$createField57_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Escalation" in $$parsedSource) {
            $$parsedSource["Escalation"] = $$createField5_0($$parsedSource["Escalation"]);
        }
        if ("Blocker" in $$parsedSource) {
            $$parsedSource["Blocker"] = $$createField7_0($$parsedSource["Blocker"]);
        }
        if ("DependsOn" in $$parsedSource) {
            $$parsedSource["DependsOn"] = $$createField12_0($$parsedSource["DependsOn"]);
        }
        if ("DependsOnConditions" in $$parsedSource) {
            $$parsedSource["DependsOnConditions"] = $$createField13_0($$parsedSource["DependsOnConditions"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField17_0($$parsedSource["Tags"]);
        }
        if ("Workflow" in $$parsedSource) {
            $$parsedSource["Workflow"] = $$createField35_0($$parsedSource["Workflow"]);
        }
        if ("PlanDraftWrite" in $$parsedSource) {
            $$parsedSource["PlanDraftWrite"] = $$createField46_0($$parsedSource["PlanDraftWrite"]);
        }
        if ("Attachments" in $$parsedSource) {
            $$parsedSource["Attachments"] = $$createField56_0($$parsedSource["Attachments"]);
        }
        if ("EffectLog" in $$parsedSource) {
            $$parsedSource["EffectLog"] = $$createField57_0($$parsedSource["EffectLog"]);
        }
        return new Update($$parsedSource as Partial<Update>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = autonomy$0.EscalationReason.createFrom;
const $$createType2 = blocker$0.State.createFrom;
const $$createType3 = DepCondition.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = attachment$0.Attachment.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = AgentRun.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = workflow$0.EffectRecord.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = workflow$0.Execution.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = Update.createFrom;
const $$createType15 = Task.createFrom;
const $$createType16 = $Create.Nullable($$createType1);
const $$createType17 = $Create.Nullable($$createType2);
const $$createType18 = $Create.Nullable($$createType0);
const $$createType19 = $Create.Nullable($$createType4);
const $$createType20 = $Create.Nullable($$createType12);
const $$createType21 = PlanDraftEntry.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Nullable($$createType6);
const $$createType24 = $Create.Nullable($$createType10);
