// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverAgents() {
  return window['go']['main']['AgentService']['DiscoverAgents']();
}

export function GetAgentOutput(arg1) {
  return window['go']['main']['AgentService']['GetAgentOutput'](arg1);
}

export function GetAgentRunLog(arg1, arg2) {
  return window['go']['main']['AgentService']['GetAgentRunLog'](arg1, arg2);
}

export function GetConvoOutput(arg1) {
  return window['go']['main']['AgentService']['GetConvoOutput'](arg1);
}

export function ListAgents() {
  return window['go']['main']['AgentService']['ListAgents']();
}

export function RespondApproval(arg1, arg2) {
  return window['go']['main']['AgentService']['RespondApproval'](arg1, arg2);
}

export function RespondEscalation(arg1, arg2) {
  return window['go']['main']['AgentService']['RespondEscalation'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['AgentService']['SendMessage'](arg1, arg2);
}

export function StopAgent(arg1) {
  return window['go']['main']['AgentService']['StopAgent'](arg1);
}
