// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notification} from '../models';
import {agent} from '../models';

export function ListNotifications():Promise<Array<notification.Notification>>;

export function RegisterSpotlightHotkey():Promise<void>;

export function SetDesktopNotifications(arg1:boolean):Promise<void>;

export function StartAgent(arg1:string,arg2:string,arg3:string):Promise<agent.Agent>;
