// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {project} from '../models';
import {agent} from '../models';
import {github} from '../models';
import {main} from '../models';
import {stats} from '../models';
import {todoist} from '../models';
import {notification} from '../models';
import {tmux} from '../models';

export function AddReviewComment(arg1:string,arg2:number,arg3:string):Promise<task.ReviewComment>;

export function ApprovePlan(arg1:string):Promise<task.Task>;

export function ApproveRenovatePR(arg1:string,arg2:number):Promise<void>;

export function AttachAgent(arg1:string):Promise<void>;

export function AttachOrchestrator():Promise<void>;

export function AttachTmuxSession(arg1:string):Promise<void>;

export function CaptureAgentPane(arg1:string):Promise<string>;

export function CaptureOrchestratorPane():Promise<string>;

export function CreateProject(arg1:string,arg2:string):Promise<project.Project>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<task.Task>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteReviewComment(arg1:string,arg2:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DiscoverAgents():Promise<Array<agent.Agent>>;

export function EvaluateTask(arg1:string,arg2:string):Promise<void>;

export function FetchAssignedIssues():Promise<Array<github.Issue>>;

export function FetchRenovatePRs():Promise<Array<github.RenovatePR>>;

export function FixRenovateCI(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function FetchReviews():Promise<github.ReviewSummary>;

export function GetAgentOutput(arg1:string):Promise<Array<agent.StreamEvent>>;

export function GetProject(arg1:string):Promise<project.Project>;

export function GetSettings():Promise<main.AppSettings>;

export function GetStats():Promise<stats.StatsResponse>;

export function GetTask(arg1:string):Promise<task.Task>;

export function GetTodoistProjects():Promise<Array<todoist.Project>>;

export function HasLivePlanAgent(arg1:string):Promise<boolean>;

export function IsOrchestratorRunning():Promise<boolean>;

export function KillTmuxSession(arg1:string):Promise<void>;

export function ListAgents():Promise<Array<agent.Agent>>;

export function ListNotifications():Promise<Array<notification.Notification>>;

export function ListProjects():Promise<Array<project.Project>>;

export function ListReviewComments(arg1:string):Promise<Array<task.ReviewComment>>;

export function ListTasks():Promise<Array<task.Task>>;

export function ListTmuxSessions():Promise<Array<tmux.SessionInfo>>;

export function ListWorktrees(arg1:string):Promise<Array<project.Worktree>>;

export function MarkPRReady(arg1:string,arg2:number):Promise<void>;

export function MergeRenovatePR(arg1:string,arg2:number):Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function PlanTask(arg1:string):Promise<void>;

export function RegisterSpotlightHotkey():Promise<void>;

export function RejectPlan(arg1:string,arg2:string):Promise<task.Task>;

export function RerunRenovateChecks(arg1:string,arg2:number):Promise<void>;

export function ResolveReviewComment(arg1:string,arg2:string):Promise<void>;

export function SendPlanMessage(arg1:string,arg2:string):Promise<void>;

export function SetDesktopNotifications(arg1:boolean):Promise<void>;

export function StartAgent(arg1:string,arg2:string,arg3:string):Promise<agent.Agent>;

export function StartOrchestrator():Promise<void>;

export function StartReview(arg1:string):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function StopOrchestrator():Promise<void>;

export function SyncTodoist():Promise<void>;

export function TodoistEnabled():Promise<boolean>;

export function TriageTask(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:string):Promise<project.Project>;

export function UpdateSettings(arg1:main.AppSettings):Promise<void>;

export function UpdateTask(arg1:string,arg2:Record<string, any>):Promise<task.Task>;
