// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAgent'](arg1, arg2, arg3);
}

export function ListNotifications() {
  return window['go']['main']['App']['ListNotifications']();
}

export function SetDesktopNotifications(arg1) {
  return window['go']['main']['App']['SetDesktopNotifications'](arg1);
}
