// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.AppSettings>;

export function UpdateSettings(arg1:main.AppSettings):Promise<void>;
