// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SyncTodoist() {
  return window['go']['main']['IntegrationService']['SyncTodoist']();
}

export function GetTodoistProjects() {
  return window['go']['main']['IntegrationService']['GetTodoistProjects']();
}

export function TodoistEnabled() {
  return window['go']['main']['IntegrationService']['TodoistEnabled']();
}

export function FetchRenovatePRs() {
  return window['go']['main']['IntegrationService']['FetchRenovatePRs']();
}

export function MergeRenovatePR(arg1, arg2) {
  return window['go']['main']['IntegrationService']['MergeRenovatePR'](arg1, arg2);
}

export function ApproveRenovatePR(arg1, arg2) {
  return window['go']['main']['IntegrationService']['ApproveRenovatePR'](arg1, arg2);
}

export function RerunRenovateChecks(arg1, arg2) {
  return window['go']['main']['IntegrationService']['RerunRenovateChecks'](arg1, arg2);
}

export function FixRenovateCI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['IntegrationService']['FixRenovateCI'](arg1, arg2, arg3, arg4);
}

export function FetchAssignedIssues() {
  return window['go']['main']['IntegrationService']['FetchAssignedIssues']();
}
