// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartOrchestrator() {
  return window['go']['main']['OrchestratorService']['StartOrchestrator']();
}

export function StopOrchestrator() {
  return window['go']['main']['OrchestratorService']['StopOrchestrator']();
}

export function IsOrchestratorRunning() {
  return window['go']['main']['OrchestratorService']['IsOrchestratorRunning']();
}

export function CaptureOrchestratorPane() {
  return window['go']['main']['OrchestratorService']['CaptureOrchestratorPane']();
}

export function AttachOrchestrator() {
  return window['go']['main']['OrchestratorService']['AttachOrchestrator']();
}
