// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartOrchestrator():Promise<void>;

export function StopOrchestrator():Promise<void>;

export function IsOrchestratorRunning():Promise<boolean>;

export function CaptureOrchestratorPane():Promise<string>;

export function AttachOrchestrator():Promise<void>;
