// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePlan(arg1) {
  return window['go']['main']['PlanningService']['ApprovePlan'](arg1);
}

export function HasLivePlanAgent(arg1) {
  return window['go']['main']['PlanningService']['HasLivePlanAgent'](arg1);
}

export function PlanTask(arg1) {
  return window['go']['main']['PlanningService']['PlanTask'](arg1);
}

export function RejectPlan(arg1, arg2) {
  return window['go']['main']['PlanningService']['RejectPlan'](arg1, arg2);
}

export function SendPlanMessage(arg1, arg2) {
  return window['go']['main']['PlanningService']['SendPlanMessage'](arg1, arg2);
}

export function TriageTask(arg1) {
  return window['go']['main']['PlanningService']['TriageTask'](arg1);
}
