// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';

export function CreateProject(arg1:string,arg2:string):Promise<project.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<project.Project>;

export function ListProjects():Promise<Array<project.Project>>;

export function ListWorktrees(arg1:string):Promise<Array<project.Worktree>>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:string):Promise<project.Project>;
