// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReviewComment(arg1, arg2, arg3) {
  return window['go']['main']['ReviewService']['AddReviewComment'](arg1, arg2, arg3);
}

export function DeleteReviewComment(arg1, arg2) {
  return window['go']['main']['ReviewService']['DeleteReviewComment'](arg1, arg2);
}

export function FetchReviews() {
  return window['go']['main']['ReviewService']['FetchReviews']();
}

export function ListReviewComments(arg1) {
  return window['go']['main']['ReviewService']['ListReviewComments'](arg1);
}

export function MarkPRReady(arg1, arg2) {
  return window['go']['main']['ReviewService']['MarkPRReady'](arg1, arg2);
}

export function ResolveReviewComment(arg1, arg2) {
  return window['go']['main']['ReviewService']['ResolveReviewComment'](arg1, arg2);
}

export function StartReview(arg1) {
  return window['go']['main']['ReviewService']['StartReview'](arg1);
}
