// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';

export function ListTasks():Promise<Array<task.Task>>;

export function GetTask(arg1:string):Promise<task.Task>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<task.Task>;

export function UpdateTask(arg1:string,arg2:Record<string, any>):Promise<task.Task>;

export function DeleteTask(arg1:string):Promise<void>;
