// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LoopAgent is a recurring headless agent: every IntervalSec seconds the
 * scheduler spawns a fresh `claude -p Prompt` process. Records are persisted
 * one-per-file under ~/.sybra/loop-agents/<id>.yaml.
 */
export class LoopAgent {
    "id": string;
    "name": string;
    "prompt": string;
    "intervalSec": number;
    "allowedTools": string[];
    "provider": string;
    "model": string;
    "enabled": boolean;
    "lastRunAt": string;
    "lastRunId": string;
    "lastRunCost": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new LoopAgent instance. */
    constructor($$source: Partial<LoopAgent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("intervalSec" in $$source)) {
            this["intervalSec"] = 0;
        }
        if (!("allowedTools" in $$source)) {
            this["allowedTools"] = [];
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("lastRunAt" in $$source)) {
            this["lastRunAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastRunId" in $$source)) {
            this["lastRunId"] = "";
        }
        if (!("lastRunCost" in $$source)) {
            this["lastRunCost"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoopAgent instance from a string or object.
     */
    static createFrom($$source: any = {}): LoopAgent {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedTools" in $$parsedSource) {
            $$parsedSource["allowedTools"] = $$createField4_0($$parsedSource["allowedTools"]);
        }
        return new LoopAgent($$parsedSource as Partial<LoopAgent>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
