// The frontend's single import surface for everything the server exposes.
//
// There is one transport. The desktop window loads this bundle from the app's
// own loopback server and reaches state over HTTP exactly as a browser pointed
// at sybra-server does, so a method added to the service registry is reachable
// from both builds without a second shim.
//
// Types still come from frontend/bindings/* (generated by `wails3 generate
// bindings`); only the call path stopped going through them.
export * from './api-http.js'
