// Code generated by cmd/gen-events from internal/events/events.go. DO NOT EDIT.
//
// Run `go generate ./internal/events/...` to regenerate after changing the Go
// source. The drift guard test TestEventsTSFile_InSyncWithGoSource catches
// any manual edits in CI.

export const TaskCreated = "task:created"
export const TaskUpdated = "task:updated"
export const TaskDeleted = "task:deleted"
export const AgentStatePrefix = "agent:state:"
export const AgentOutputPrefix = "agent:output:"
export const AgentErrorPrefix = "agent:error:"
export const AgentStuckPrefix = "agent:stuck:"
export const AgentConvoPrefix = "agent:convo:"
export const AgentApprovalPrefix = "agent:approval:"
export const AgentEscalationPrefix = "agent:escalation:"
export const OrchestratorState = "orchestrator:state"
export const MonitorHeartbeat = "monitor:heartbeat"
export const LoopAgentUpdated = "loopagent:updated"
export const ReviewsUpdated = "reviews:updated"
export const RenovateUpdated = "renovate:updated"
export const Notification = "notification"
export const TodoistSynced = "todoist:synced"
export const IssuesUpdated = "issues:updated"
export const AppQuitConfirm = "app:quit-confirm"
export const StartupDegraded = "startup:degraded"

export const agentApproval = (id: string) => `${AgentApprovalPrefix}${id}`
export const agentConvo = (id: string) => `${AgentConvoPrefix}${id}`
export const agentError = (id: string) => `${AgentErrorPrefix}${id}`
export const agentEscalation = (id: string) => `${AgentEscalationPrefix}${id}`
export const agentOutput = (id: string) => `${AgentOutputPrefix}${id}`
export const agentState = (id: string) => `${AgentStatePrefix}${id}`
export const agentStuck = (id: string) => `${AgentStuckPrefix}${id}`
