// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Operation is a single tracked background operation.
 */
export class Operation {
    "id": string;
    "type": Type;
    "label": string;
    "status": Status;
    "phase"?: string;
    "projectId"?: string;
    "taskId"?: string;
    "startedAt": string;
    "completedAt"?: string;
    "error"?: string;

    /** Creates a new Operation instance. */
    constructor($$source: Partial<Operation> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = Type.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operation instance from a string or object.
     */
    static createFrom($$source: any = {}): Operation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Operation($$parsedSource as Partial<Operation>);
    }
}

/**
 * Status is the lifecycle state of an operation.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusRunning = "running",
    StatusDone = "done",
    StatusFailed = "failed",
};

/**
 * Type classifies a background operation.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TypeClone is a bare-repo git clone.
     */
    TypeClone = "clone",

    /**
     * TypeWorktreePrep is worktree creation/rebase/push for an agent.
     */
    TypeWorktreePrep = "worktree_prep",
};
